// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package overlay

import (
	"context"
	"umineko_city_of_books/internal/dto"

	"github.com/gofiber/fiber/v3"
	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// BuildSEF provides a mock function for the type MockService
func (_mock *MockService) BuildSEF(ctx context.Context, userID uuid.UUID) (string, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for BuildSEF")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (string, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) string); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_BuildSEF_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BuildSEF'
type MockService_BuildSEF_Call struct {
	*mock.Call
}

// BuildSEF is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockService_Expecter) BuildSEF(ctx any, userID any) *MockService_BuildSEF_Call {
	return &MockService_BuildSEF_Call{Call: _e.mock.On("BuildSEF", ctx, userID)}
}

func (_c *MockService_BuildSEF_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockService_BuildSEF_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_BuildSEF_Call) Return(s string, err error) *MockService_BuildSEF_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockService_BuildSEF_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (string, error)) *MockService_BuildSEF_Call {
	_c.Call.Return(run)
	return _c
}

// ConnectURL provides a mock function for the type MockService
func (_mock *MockService) ConnectURL(ctx context.Context, userID uuid.UUID) (string, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ConnectURL")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (string, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) string); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ConnectURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ConnectURL'
type MockService_ConnectURL_Call struct {
	*mock.Call
}

// ConnectURL is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockService_Expecter) ConnectURL(ctx any, userID any) *MockService_ConnectURL_Call {
	return &MockService_ConnectURL_Call{Call: _e.mock.On("ConnectURL", ctx, userID)}
}

func (_c *MockService_ConnectURL_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockService_ConnectURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_ConnectURL_Call) Return(s string, err error) *MockService_ConnectURL_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockService_ConnectURL_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (string, error)) *MockService_ConnectURL_Call {
	_c.Call.Return(run)
	return _c
}

// DispatchNotification provides a mock function for the type MockService
func (_mock *MockService) DispatchNotification(recipientID uuid.UUID, resp dto.NotificationResponse) {
	_mock.Called(recipientID, resp)
	return
}

// MockService_DispatchNotification_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DispatchNotification'
type MockService_DispatchNotification_Call struct {
	*mock.Call
}

// DispatchNotification is a helper method to define mock.On call
//   - recipientID uuid.UUID
//   - resp dto.NotificationResponse
func (_e *MockService_Expecter) DispatchNotification(recipientID any, resp any) *MockService_DispatchNotification_Call {
	return &MockService_DispatchNotification_Call{Call: _e.mock.On("DispatchNotification", recipientID, resp)}
}

func (_c *MockService_DispatchNotification_Call) Run(run func(recipientID uuid.UUID, resp dto.NotificationResponse)) *MockService_DispatchNotification_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		var arg1 dto.NotificationResponse
		if args[1] != nil {
			arg1 = args[1].(dto.NotificationResponse)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_DispatchNotification_Call) Return() *MockService_DispatchNotification_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockService_DispatchNotification_Call) RunAndReturn(run func(recipientID uuid.UUID, resp dto.NotificationResponse)) *MockService_DispatchNotification_Call {
	_c.Run(run)
	return _c
}

// Handler provides a mock function for the type MockService
func (_mock *MockService) Handler() fiber.Handler {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Handler")
	}

	var r0 fiber.Handler
	if returnFunc, ok := ret.Get(0).(func() fiber.Handler); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(fiber.Handler)
		}
	}
	return r0
}

// MockService_Handler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Handler'
type MockService_Handler_Call struct {
	*mock.Call
}

// Handler is a helper method to define mock.On call
func (_e *MockService_Expecter) Handler() *MockService_Handler_Call {
	return &MockService_Handler_Call{Call: _e.mock.On("Handler")}
}

func (_c *MockService_Handler_Call) Run(run func()) *MockService_Handler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockService_Handler_Call) Return(handler fiber.Handler) *MockService_Handler_Call {
	_c.Call.Return(handler)
	return _c
}

func (_c *MockService_Handler_Call) RunAndReturn(run func() fiber.Handler) *MockService_Handler_Call {
	_c.Call.Return(run)
	return _c
}

// IsConnected provides a mock function for the type MockService
func (_mock *MockService) IsConnected(userID uuid.UUID) bool {
	ret := _mock.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for IsConnected")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) bool); ok {
		r0 = returnFunc(userID)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockService_IsConnected_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsConnected'
type MockService_IsConnected_Call struct {
	*mock.Call
}

// IsConnected is a helper method to define mock.On call
//   - userID uuid.UUID
func (_e *MockService_Expecter) IsConnected(userID any) *MockService_IsConnected_Call {
	return &MockService_IsConnected_Call{Call: _e.mock.On("IsConnected", userID)}
}

func (_c *MockService_IsConnected_Call) Run(run func(userID uuid.UUID)) *MockService_IsConnected_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_IsConnected_Call) Return(b bool) *MockService_IsConnected_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockService_IsConnected_Call) RunAndReturn(run func(userID uuid.UUID) bool) *MockService_IsConnected_Call {
	_c.Call.Return(run)
	return _c
}

// ResetToken provides a mock function for the type MockService
func (_mock *MockService) ResetToken(ctx context.Context, userID uuid.UUID) (string, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for ResetToken")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (string, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) string); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ResetToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ResetToken'
type MockService_ResetToken_Call struct {
	*mock.Call
}

// ResetToken is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockService_Expecter) ResetToken(ctx any, userID any) *MockService_ResetToken_Call {
	return &MockService_ResetToken_Call{Call: _e.mock.On("ResetToken", ctx, userID)}
}

func (_c *MockService_ResetToken_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockService_ResetToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_ResetToken_Call) Return(s string, err error) *MockService_ResetToken_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockService_ResetToken_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (string, error)) *MockService_ResetToken_Call {
	_c.Call.Return(run)
	return _c
}

// TestFire provides a mock function for the type MockService
func (_mock *MockService) TestFire(userID uuid.UUID) error {
	ret := _mock.Called(userID)

	if len(ret) == 0 {
		panic("no return value specified for TestFire")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(uuid.UUID) error); ok {
		r0 = returnFunc(userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_TestFire_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TestFire'
type MockService_TestFire_Call struct {
	*mock.Call
}

// TestFire is a helper method to define mock.On call
//   - userID uuid.UUID
func (_e *MockService_Expecter) TestFire(userID any) *MockService_TestFire_Call {
	return &MockService_TestFire_Call{Call: _e.mock.On("TestFire", userID)}
}

func (_c *MockService_TestFire_Call) Run(run func(userID uuid.UUID)) *MockService_TestFire_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 uuid.UUID
		if args[0] != nil {
			arg0 = args[0].(uuid.UUID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_TestFire_Call) Return(err error) *MockService_TestFire_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_TestFire_Call) RunAndReturn(run func(userID uuid.UUID) error) *MockService_TestFire_Call {
	_c.Call.Return(run)
	return _c
}

// Token provides a mock function for the type MockService
func (_mock *MockService) Token(ctx context.Context, userID uuid.UUID) (string, error) {
	ret := _mock.Called(ctx, userID)

	if len(ret) == 0 {
		panic("no return value specified for Token")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) (string, error)); ok {
		return returnFunc(ctx, userID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID) string); ok {
		r0 = returnFunc(ctx, userID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, userID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Token_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Token'
type MockService_Token_Call struct {
	*mock.Call
}

// Token is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
func (_e *MockService_Expecter) Token(ctx any, userID any) *MockService_Token_Call {
	return &MockService_Token_Call{Call: _e.mock.On("Token", ctx, userID)}
}

func (_c *MockService_Token_Call) Run(run func(ctx context.Context, userID uuid.UUID)) *MockService_Token_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Token_Call) Return(s string, err error) *MockService_Token_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockService_Token_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID) (string, error)) *MockService_Token_Call {
	_c.Call.Return(run)
	return _c
}

// Validate provides a mock function for the type MockService
func (_mock *MockService) Validate(ctx context.Context, token string) (uuid.UUID, error) {
	ret := _mock.Called(ctx, token)

	if len(ret) == 0 {
		panic("no return value specified for Validate")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) (uuid.UUID, error)); ok {
		return returnFunc(ctx, token)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) uuid.UUID); ok {
		r0 = returnFunc(ctx, token)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = returnFunc(ctx, token)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_Validate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Validate'
type MockService_Validate_Call struct {
	*mock.Call
}

// Validate is a helper method to define mock.On call
//   - ctx context.Context
//   - token string
func (_e *MockService_Expecter) Validate(ctx any, token any) *MockService_Validate_Call {
	return &MockService_Validate_Call{Call: _e.mock.On("Validate", ctx, token)}
}

func (_c *MockService_Validate_Call) Run(run func(ctx context.Context, token string)) *MockService_Validate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *MockService_Validate_Call) Return(uUID uuid.UUID, err error) *MockService_Validate_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockService_Validate_Call) RunAndReturn(run func(ctx context.Context, token string) (uuid.UUID, error)) *MockService_Validate_Call {
	_c.Call.Return(run)
	return _c
}
