import { makeChatThread } from "./useChatThread.fixture";
import type { RoomController } from "./useRoomController";

function noop(): void {}

function never(): Promise<void> {
    return Promise.resolve();
}

export function makeRoomController(overrides: Partial<RoomController> = {}): RoomController {
    const { thread, session, capabilities, toast } = makeChatThread();

    return {
        room: {
            data: thread.data,
            id: thread.id,
            loading: thread.loading,
            joining: false,
            viewerTimeoutUntil: undefined,
            viewerTimedOut: false,
            set: thread.set,
            join: never,
            toggleMute: thread.toggleMute,
            leave: never,
            remove: never,
            backToRooms: noop,
        },
        session: {
            viewer: session.viewer,
            messages: session.messages,
            hasMore: session.hasMore,
            loadingMore: session.loadingMore,
            containerRef: session.containerRef,
            contentRef: session.contentRef,
            endRef: session.endRef,
            onScroll: session.onScroll,
            toBottom: session.toBottom,
            editingMessageId: session.editingMessageId,
            startEditing: session.startEditing,
            cancelEditing: session.cancelEditing,
            replyingTo: session.replyingTo,
            setReplyingTo: session.setReplyingTo,
            typingNames: [],
            notifyTyping: session.notifyTyping,
            matchesViewerMention: session.matchesViewerMention,
            onSent: session.onSent,
            deleteMessage: session.deleteMessage,
            editMessage: session.editMessage,
            editLast: session.editLast,
            toggleReaction: session.toggleReaction,
            togglePin: session.togglePin,
        },
        members: {
            list: [],
            groups: [],
            presence: {},
            onlineWeight: () => 1,
            current: null,
            set: noop,
        },
        moderation: {
            busy: null,
            setBusy: noop,
            openMemberMenu: null,
            setOpenMemberMenu: noop,
            nicknameDialogTarget: null,
            setNicknameDialogTarget: noop,
            nicknameDialogValue: "",
            setNicknameDialogValue: noop,
            nicknameDialogError: "",
            nicknameDialogSaving: false,
            timeoutDialogTarget: null,
            setTimeoutDialogTarget: noop,
            timeoutDialogAmount: "10",
            setTimeoutDialogAmount: noop,
            timeoutDialogUnit: "seconds",
            setTimeoutDialogUnit: noop,
            timeoutDialogError: "",
            timeoutDialogSaving: false,
            formatTimeoutUntil: () => "",
            openNicknameDialog: noop,
            openTimeoutDialog: noop,
            handleModSetNickname: never,
            handleModUnlockNickname: never,
            handleSetTimeout: never,
            handleClearTimeout: never,
            handleKick: never,
            handleBan: never,
        },
        capabilities,
        prefs: {
            sidebarCollapsed: false,
            toggleSidebar: noop,
            descExpanded: false,
            toggleDescExpanded: noop,
            mobileView: "chat",
            setMobileView: noop,
        },
        anchor: {
            highlightedMsgId: null,
            jumpTo: never,
        },
        voice: thread.voice,
        watchParty: {
            enabled: true,
            screenShareEnabled: true,
            loaded: true,
            sessions: [],
            activeSession: null,
            openSessionId: null,
            error: "",
            refresh: never,
            start: () => Promise.resolve(null),
            join: never,
            leave: never,
            end: never,
            transferControl: never,
            kick: never,
            identify: never,
            openExisting: noop,
            close: noop,
            clearError: noop,
            invitedPartyMissing: false,
        },
        panels: {
            pinnedOpen: false,
            setPinnedOpen: noop,
            searchOpen: false,
            setSearchOpen: noop,
            lightboxSrc: null,
            setLightboxSrc: noop,
            editProfileOpen: false,
            setEditProfileOpen: noop,
            inviteModalOpen: false,
            setInviteModalOpen: noop,
            moderationDialogOpen: false,
            setModerationDialogOpen: noop,
        },
        toast: {
            message: toast.message,
            show: toast.show,
        },
        ...overrides,
    };
}
