// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"
	"database/sql"
	"umineko_city_of_books/internal/model"
	"umineko_city_of_books/internal/model/spec"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockChatWatchPartyRepository creates a new instance of MockChatWatchPartyRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChatWatchPartyRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChatWatchPartyRepository {
	mock := &MockChatWatchPartyRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChatWatchPartyRepository is an autogenerated mock type for the ChatWatchPartyRepository type
type MockChatWatchPartyRepository struct {
	mock.Mock
}

type MockChatWatchPartyRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChatWatchPartyRepository) EXPECT() *MockChatWatchPartyRepository_Expecter {
	return &MockChatWatchPartyRepository_Expecter{mock: &_m.Mock}
}

// CountActiveParticipants provides a mock function for the type MockChatWatchPartyRepository
func (_mock *MockChatWatchPartyRepository) CountActiveParticipants(ctx context.Context, sessionID uuid.UUID, tx ...*sql.Tx) (int, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, sessionID, tx)
	} else {
		tmpRet = _mock.Called(ctx, sessionID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for CountActiveParticipants")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...*sql.Tx) (int, error)); ok {
		return returnFunc(ctx, sessionID, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...*sql.Tx) int); ok {
		r0 = returnFunc(ctx, sessionID, tx...)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, sessionID, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatWatchPartyRepository_CountActiveParticipants_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountActiveParticipants'
type MockChatWatchPartyRepository_CountActiveParticipants_Call struct {
	*mock.Call
}

// CountActiveParticipants is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID uuid.UUID
//   - tx ...*sql.Tx
func (_e *MockChatWatchPartyRepository_Expecter) CountActiveParticipants(ctx any, sessionID any, tx ...any) *MockChatWatchPartyRepository_CountActiveParticipants_Call {
	return &MockChatWatchPartyRepository_CountActiveParticipants_Call{Call: _e.mock.On("CountActiveParticipants",
		append([]any{ctx, sessionID}, tx...)...)}
}

func (_c *MockChatWatchPartyRepository_CountActiveParticipants_Call) Run(run func(ctx context.Context, sessionID uuid.UUID, tx ...*sql.Tx)) *MockChatWatchPartyRepository_CountActiveParticipants_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockChatWatchPartyRepository_CountActiveParticipants_Call) Return(n int, err error) *MockChatWatchPartyRepository_CountActiveParticipants_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockChatWatchPartyRepository_CountActiveParticipants_Call) RunAndReturn(run func(ctx context.Context, sessionID uuid.UUID, tx ...*sql.Tx) (int, error)) *MockChatWatchPartyRepository_CountActiveParticipants_Call {
	_c.Call.Return(run)
	return _c
}

// CreateSession provides a mock function for the type MockChatWatchPartyRepository
func (_mock *MockChatWatchPartyRepository) CreateSession(ctx context.Context, row model.ChatWatchPartySessionRow, tx ...*sql.Tx) (*model.ChatWatchPartySessionRow, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, row, tx)
	} else {
		tmpRet = _mock.Called(ctx, row)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for CreateSession")
	}

	var r0 *model.ChatWatchPartySessionRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.ChatWatchPartySessionRow, ...*sql.Tx) (*model.ChatWatchPartySessionRow, error)); ok {
		return returnFunc(ctx, row, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, model.ChatWatchPartySessionRow, ...*sql.Tx) *model.ChatWatchPartySessionRow); ok {
		r0 = returnFunc(ctx, row, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ChatWatchPartySessionRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, model.ChatWatchPartySessionRow, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, row, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatWatchPartyRepository_CreateSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateSession'
type MockChatWatchPartyRepository_CreateSession_Call struct {
	*mock.Call
}

// CreateSession is a helper method to define mock.On call
//   - ctx context.Context
//   - row model.ChatWatchPartySessionRow
//   - tx ...*sql.Tx
func (_e *MockChatWatchPartyRepository_Expecter) CreateSession(ctx any, row any, tx ...any) *MockChatWatchPartyRepository_CreateSession_Call {
	return &MockChatWatchPartyRepository_CreateSession_Call{Call: _e.mock.On("CreateSession",
		append([]any{ctx, row}, tx...)...)}
}

func (_c *MockChatWatchPartyRepository_CreateSession_Call) Run(run func(ctx context.Context, row model.ChatWatchPartySessionRow, tx ...*sql.Tx)) *MockChatWatchPartyRepository_CreateSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 model.ChatWatchPartySessionRow
		if args[1] != nil {
			arg1 = args[1].(model.ChatWatchPartySessionRow)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockChatWatchPartyRepository_CreateSession_Call) Return(chatWatchPartySessionRow *model.ChatWatchPartySessionRow, err error) *MockChatWatchPartyRepository_CreateSession_Call {
	_c.Call.Return(chatWatchPartySessionRow, err)
	return _c
}

func (_c *MockChatWatchPartyRepository_CreateSession_Call) RunAndReturn(run func(ctx context.Context, row model.ChatWatchPartySessionRow, tx ...*sql.Tx) (*model.ChatWatchPartySessionRow, error)) *MockChatWatchPartyRepository_CreateSession_Call {
	_c.Call.Return(run)
	return _c
}

// EndSession provides a mock function for the type MockChatWatchPartyRepository
func (_mock *MockChatWatchPartyRepository) EndSession(ctx context.Context, s spec.WatchPartySessionEnd, tx ...*sql.Tx) error {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, s, tx)
	} else {
		tmpRet = _mock.Called(ctx, s)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for EndSession")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.WatchPartySessionEnd, ...*sql.Tx) error); ok {
		r0 = returnFunc(ctx, s, tx...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChatWatchPartyRepository_EndSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'EndSession'
type MockChatWatchPartyRepository_EndSession_Call struct {
	*mock.Call
}

// EndSession is a helper method to define mock.On call
//   - ctx context.Context
//   - s spec.WatchPartySessionEnd
//   - tx ...*sql.Tx
func (_e *MockChatWatchPartyRepository_Expecter) EndSession(ctx any, s any, tx ...any) *MockChatWatchPartyRepository_EndSession_Call {
	return &MockChatWatchPartyRepository_EndSession_Call{Call: _e.mock.On("EndSession",
		append([]any{ctx, s}, tx...)...)}
}

func (_c *MockChatWatchPartyRepository_EndSession_Call) Run(run func(ctx context.Context, s spec.WatchPartySessionEnd, tx ...*sql.Tx)) *MockChatWatchPartyRepository_EndSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.WatchPartySessionEnd
		if args[1] != nil {
			arg1 = args[1].(spec.WatchPartySessionEnd)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockChatWatchPartyRepository_EndSession_Call) Return(err error) *MockChatWatchPartyRepository_EndSession_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChatWatchPartyRepository_EndSession_Call) RunAndReturn(run func(ctx context.Context, s spec.WatchPartySessionEnd, tx ...*sql.Tx) error) *MockChatWatchPartyRepository_EndSession_Call {
	_c.Call.Return(run)
	return _c
}

// GetActiveParticipants provides a mock function for the type MockChatWatchPartyRepository
func (_mock *MockChatWatchPartyRepository) GetActiveParticipants(ctx context.Context, sessionID uuid.UUID, tx ...*sql.Tx) ([]model.ChatWatchPartyParticipantRow, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, sessionID, tx)
	} else {
		tmpRet = _mock.Called(ctx, sessionID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetActiveParticipants")
	}

	var r0 []model.ChatWatchPartyParticipantRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...*sql.Tx) ([]model.ChatWatchPartyParticipantRow, error)); ok {
		return returnFunc(ctx, sessionID, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...*sql.Tx) []model.ChatWatchPartyParticipantRow); ok {
		r0 = returnFunc(ctx, sessionID, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ChatWatchPartyParticipantRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, sessionID, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatWatchPartyRepository_GetActiveParticipants_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetActiveParticipants'
type MockChatWatchPartyRepository_GetActiveParticipants_Call struct {
	*mock.Call
}

// GetActiveParticipants is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID uuid.UUID
//   - tx ...*sql.Tx
func (_e *MockChatWatchPartyRepository_Expecter) GetActiveParticipants(ctx any, sessionID any, tx ...any) *MockChatWatchPartyRepository_GetActiveParticipants_Call {
	return &MockChatWatchPartyRepository_GetActiveParticipants_Call{Call: _e.mock.On("GetActiveParticipants",
		append([]any{ctx, sessionID}, tx...)...)}
}

func (_c *MockChatWatchPartyRepository_GetActiveParticipants_Call) Run(run func(ctx context.Context, sessionID uuid.UUID, tx ...*sql.Tx)) *MockChatWatchPartyRepository_GetActiveParticipants_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockChatWatchPartyRepository_GetActiveParticipants_Call) Return(chatWatchPartyParticipantRows []model.ChatWatchPartyParticipantRow, err error) *MockChatWatchPartyRepository_GetActiveParticipants_Call {
	_c.Call.Return(chatWatchPartyParticipantRows, err)
	return _c
}

func (_c *MockChatWatchPartyRepository_GetActiveParticipants_Call) RunAndReturn(run func(ctx context.Context, sessionID uuid.UUID, tx ...*sql.Tx) ([]model.ChatWatchPartyParticipantRow, error)) *MockChatWatchPartyRepository_GetActiveParticipants_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockChatWatchPartyRepository
func (_mock *MockChatWatchPartyRepository) GetByID(ctx context.Context, sessionID uuid.UUID, tx ...*sql.Tx) (*model.ChatWatchPartySessionRow, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, sessionID, tx)
	} else {
		tmpRet = _mock.Called(ctx, sessionID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.ChatWatchPartySessionRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...*sql.Tx) (*model.ChatWatchPartySessionRow, error)); ok {
		return returnFunc(ctx, sessionID, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...*sql.Tx) *model.ChatWatchPartySessionRow); ok {
		r0 = returnFunc(ctx, sessionID, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ChatWatchPartySessionRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, sessionID, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatWatchPartyRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockChatWatchPartyRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID uuid.UUID
//   - tx ...*sql.Tx
func (_e *MockChatWatchPartyRepository_Expecter) GetByID(ctx any, sessionID any, tx ...any) *MockChatWatchPartyRepository_GetByID_Call {
	return &MockChatWatchPartyRepository_GetByID_Call{Call: _e.mock.On("GetByID",
		append([]any{ctx, sessionID}, tx...)...)}
}

func (_c *MockChatWatchPartyRepository_GetByID_Call) Run(run func(ctx context.Context, sessionID uuid.UUID, tx ...*sql.Tx)) *MockChatWatchPartyRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockChatWatchPartyRepository_GetByID_Call) Return(chatWatchPartySessionRow *model.ChatWatchPartySessionRow, err error) *MockChatWatchPartyRepository_GetByID_Call {
	_c.Call.Return(chatWatchPartySessionRow, err)
	return _c
}

func (_c *MockChatWatchPartyRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, sessionID uuid.UUID, tx ...*sql.Tx) (*model.ChatWatchPartySessionRow, error)) *MockChatWatchPartyRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetParticipant provides a mock function for the type MockChatWatchPartyRepository
func (_mock *MockChatWatchPartyRepository) GetParticipant(ctx context.Context, s spec.WatchPartyParticipantRef, tx ...*sql.Tx) (*model.ChatWatchPartyParticipantRow, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, s, tx)
	} else {
		tmpRet = _mock.Called(ctx, s)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetParticipant")
	}

	var r0 *model.ChatWatchPartyParticipantRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.WatchPartyParticipantRef, ...*sql.Tx) (*model.ChatWatchPartyParticipantRow, error)); ok {
		return returnFunc(ctx, s, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.WatchPartyParticipantRef, ...*sql.Tx) *model.ChatWatchPartyParticipantRow); ok {
		r0 = returnFunc(ctx, s, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ChatWatchPartyParticipantRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, spec.WatchPartyParticipantRef, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, s, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatWatchPartyRepository_GetParticipant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetParticipant'
type MockChatWatchPartyRepository_GetParticipant_Call struct {
	*mock.Call
}

// GetParticipant is a helper method to define mock.On call
//   - ctx context.Context
//   - s spec.WatchPartyParticipantRef
//   - tx ...*sql.Tx
func (_e *MockChatWatchPartyRepository_Expecter) GetParticipant(ctx any, s any, tx ...any) *MockChatWatchPartyRepository_GetParticipant_Call {
	return &MockChatWatchPartyRepository_GetParticipant_Call{Call: _e.mock.On("GetParticipant",
		append([]any{ctx, s}, tx...)...)}
}

func (_c *MockChatWatchPartyRepository_GetParticipant_Call) Run(run func(ctx context.Context, s spec.WatchPartyParticipantRef, tx ...*sql.Tx)) *MockChatWatchPartyRepository_GetParticipant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.WatchPartyParticipantRef
		if args[1] != nil {
			arg1 = args[1].(spec.WatchPartyParticipantRef)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockChatWatchPartyRepository_GetParticipant_Call) Return(chatWatchPartyParticipantRow *model.ChatWatchPartyParticipantRow, err error) *MockChatWatchPartyRepository_GetParticipant_Call {
	_c.Call.Return(chatWatchPartyParticipantRow, err)
	return _c
}

func (_c *MockChatWatchPartyRepository_GetParticipant_Call) RunAndReturn(run func(ctx context.Context, s spec.WatchPartyParticipantRef, tx ...*sql.Tx) (*model.ChatWatchPartyParticipantRow, error)) *MockChatWatchPartyRepository_GetParticipant_Call {
	_c.Call.Return(run)
	return _c
}

// ListActiveByRoom provides a mock function for the type MockChatWatchPartyRepository
func (_mock *MockChatWatchPartyRepository) ListActiveByRoom(ctx context.Context, roomID uuid.UUID, tx ...*sql.Tx) ([]model.ChatWatchPartySessionRow, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, roomID, tx)
	} else {
		tmpRet = _mock.Called(ctx, roomID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListActiveByRoom")
	}

	var r0 []model.ChatWatchPartySessionRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...*sql.Tx) ([]model.ChatWatchPartySessionRow, error)); ok {
		return returnFunc(ctx, roomID, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...*sql.Tx) []model.ChatWatchPartySessionRow); ok {
		r0 = returnFunc(ctx, roomID, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ChatWatchPartySessionRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, roomID, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatWatchPartyRepository_ListActiveByRoom_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListActiveByRoom'
type MockChatWatchPartyRepository_ListActiveByRoom_Call struct {
	*mock.Call
}

// ListActiveByRoom is a helper method to define mock.On call
//   - ctx context.Context
//   - roomID uuid.UUID
//   - tx ...*sql.Tx
func (_e *MockChatWatchPartyRepository_Expecter) ListActiveByRoom(ctx any, roomID any, tx ...any) *MockChatWatchPartyRepository_ListActiveByRoom_Call {
	return &MockChatWatchPartyRepository_ListActiveByRoom_Call{Call: _e.mock.On("ListActiveByRoom",
		append([]any{ctx, roomID}, tx...)...)}
}

func (_c *MockChatWatchPartyRepository_ListActiveByRoom_Call) Run(run func(ctx context.Context, roomID uuid.UUID, tx ...*sql.Tx)) *MockChatWatchPartyRepository_ListActiveByRoom_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockChatWatchPartyRepository_ListActiveByRoom_Call) Return(chatWatchPartySessionRows []model.ChatWatchPartySessionRow, err error) *MockChatWatchPartyRepository_ListActiveByRoom_Call {
	_c.Call.Return(chatWatchPartySessionRows, err)
	return _c
}

func (_c *MockChatWatchPartyRepository_ListActiveByRoom_Call) RunAndReturn(run func(ctx context.Context, roomID uuid.UUID, tx ...*sql.Tx) ([]model.ChatWatchPartySessionRow, error)) *MockChatWatchPartyRepository_ListActiveByRoom_Call {
	_c.Call.Return(run)
	return _c
}

// ListIdleActiveSessions provides a mock function for the type MockChatWatchPartyRepository
func (_mock *MockChatWatchPartyRepository) ListIdleActiveSessions(ctx context.Context, idleBefore string, tx ...*sql.Tx) ([]model.ChatWatchPartySessionRow, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, idleBefore, tx)
	} else {
		tmpRet = _mock.Called(ctx, idleBefore)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListIdleActiveSessions")
	}

	var r0 []model.ChatWatchPartySessionRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...*sql.Tx) ([]model.ChatWatchPartySessionRow, error)); ok {
		return returnFunc(ctx, idleBefore, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...*sql.Tx) []model.ChatWatchPartySessionRow); ok {
		r0 = returnFunc(ctx, idleBefore, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ChatWatchPartySessionRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, idleBefore, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatWatchPartyRepository_ListIdleActiveSessions_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListIdleActiveSessions'
type MockChatWatchPartyRepository_ListIdleActiveSessions_Call struct {
	*mock.Call
}

// ListIdleActiveSessions is a helper method to define mock.On call
//   - ctx context.Context
//   - idleBefore string
//   - tx ...*sql.Tx
func (_e *MockChatWatchPartyRepository_Expecter) ListIdleActiveSessions(ctx any, idleBefore any, tx ...any) *MockChatWatchPartyRepository_ListIdleActiveSessions_Call {
	return &MockChatWatchPartyRepository_ListIdleActiveSessions_Call{Call: _e.mock.On("ListIdleActiveSessions",
		append([]any{ctx, idleBefore}, tx...)...)}
}

func (_c *MockChatWatchPartyRepository_ListIdleActiveSessions_Call) Run(run func(ctx context.Context, idleBefore string, tx ...*sql.Tx)) *MockChatWatchPartyRepository_ListIdleActiveSessions_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockChatWatchPartyRepository_ListIdleActiveSessions_Call) Return(chatWatchPartySessionRows []model.ChatWatchPartySessionRow, err error) *MockChatWatchPartyRepository_ListIdleActiveSessions_Call {
	_c.Call.Return(chatWatchPartySessionRows, err)
	return _c
}

func (_c *MockChatWatchPartyRepository_ListIdleActiveSessions_Call) RunAndReturn(run func(ctx context.Context, idleBefore string, tx ...*sql.Tx) ([]model.ChatWatchPartySessionRow, error)) *MockChatWatchPartyRepository_ListIdleActiveSessions_Call {
	_c.Call.Return(run)
	return _c
}

// MarkAllParticipantsLeft provides a mock function for the type MockChatWatchPartyRepository
func (_mock *MockChatWatchPartyRepository) MarkAllParticipantsLeft(ctx context.Context, sessionID uuid.UUID, tx ...*sql.Tx) error {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, sessionID, tx)
	} else {
		tmpRet = _mock.Called(ctx, sessionID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for MarkAllParticipantsLeft")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...*sql.Tx) error); ok {
		r0 = returnFunc(ctx, sessionID, tx...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChatWatchPartyRepository_MarkAllParticipantsLeft_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkAllParticipantsLeft'
type MockChatWatchPartyRepository_MarkAllParticipantsLeft_Call struct {
	*mock.Call
}

// MarkAllParticipantsLeft is a helper method to define mock.On call
//   - ctx context.Context
//   - sessionID uuid.UUID
//   - tx ...*sql.Tx
func (_e *MockChatWatchPartyRepository_Expecter) MarkAllParticipantsLeft(ctx any, sessionID any, tx ...any) *MockChatWatchPartyRepository_MarkAllParticipantsLeft_Call {
	return &MockChatWatchPartyRepository_MarkAllParticipantsLeft_Call{Call: _e.mock.On("MarkAllParticipantsLeft",
		append([]any{ctx, sessionID}, tx...)...)}
}

func (_c *MockChatWatchPartyRepository_MarkAllParticipantsLeft_Call) Run(run func(ctx context.Context, sessionID uuid.UUID, tx ...*sql.Tx)) *MockChatWatchPartyRepository_MarkAllParticipantsLeft_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockChatWatchPartyRepository_MarkAllParticipantsLeft_Call) Return(err error) *MockChatWatchPartyRepository_MarkAllParticipantsLeft_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChatWatchPartyRepository_MarkAllParticipantsLeft_Call) RunAndReturn(run func(ctx context.Context, sessionID uuid.UUID, tx ...*sql.Tx) error) *MockChatWatchPartyRepository_MarkAllParticipantsLeft_Call {
	_c.Call.Return(run)
	return _c
}

// MarkParticipantLeft provides a mock function for the type MockChatWatchPartyRepository
func (_mock *MockChatWatchPartyRepository) MarkParticipantLeft(ctx context.Context, s spec.WatchPartyParticipantRef, tx ...*sql.Tx) error {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, s, tx)
	} else {
		tmpRet = _mock.Called(ctx, s)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for MarkParticipantLeft")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.WatchPartyParticipantRef, ...*sql.Tx) error); ok {
		r0 = returnFunc(ctx, s, tx...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChatWatchPartyRepository_MarkParticipantLeft_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkParticipantLeft'
type MockChatWatchPartyRepository_MarkParticipantLeft_Call struct {
	*mock.Call
}

// MarkParticipantLeft is a helper method to define mock.On call
//   - ctx context.Context
//   - s spec.WatchPartyParticipantRef
//   - tx ...*sql.Tx
func (_e *MockChatWatchPartyRepository_Expecter) MarkParticipantLeft(ctx any, s any, tx ...any) *MockChatWatchPartyRepository_MarkParticipantLeft_Call {
	return &MockChatWatchPartyRepository_MarkParticipantLeft_Call{Call: _e.mock.On("MarkParticipantLeft",
		append([]any{ctx, s}, tx...)...)}
}

func (_c *MockChatWatchPartyRepository_MarkParticipantLeft_Call) Run(run func(ctx context.Context, s spec.WatchPartyParticipantRef, tx ...*sql.Tx)) *MockChatWatchPartyRepository_MarkParticipantLeft_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.WatchPartyParticipantRef
		if args[1] != nil {
			arg1 = args[1].(spec.WatchPartyParticipantRef)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockChatWatchPartyRepository_MarkParticipantLeft_Call) Return(err error) *MockChatWatchPartyRepository_MarkParticipantLeft_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChatWatchPartyRepository_MarkParticipantLeft_Call) RunAndReturn(run func(ctx context.Context, s spec.WatchPartyParticipantRef, tx ...*sql.Tx) error) *MockChatWatchPartyRepository_MarkParticipantLeft_Call {
	_c.Call.Return(run)
	return _c
}

// RemoveParticipant provides a mock function for the type MockChatWatchPartyRepository
func (_mock *MockChatWatchPartyRepository) RemoveParticipant(ctx context.Context, s spec.WatchPartyParticipantRef, tx ...*sql.Tx) error {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, s, tx)
	} else {
		tmpRet = _mock.Called(ctx, s)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for RemoveParticipant")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.WatchPartyParticipantRef, ...*sql.Tx) error); ok {
		r0 = returnFunc(ctx, s, tx...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChatWatchPartyRepository_RemoveParticipant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RemoveParticipant'
type MockChatWatchPartyRepository_RemoveParticipant_Call struct {
	*mock.Call
}

// RemoveParticipant is a helper method to define mock.On call
//   - ctx context.Context
//   - s spec.WatchPartyParticipantRef
//   - tx ...*sql.Tx
func (_e *MockChatWatchPartyRepository_Expecter) RemoveParticipant(ctx any, s any, tx ...any) *MockChatWatchPartyRepository_RemoveParticipant_Call {
	return &MockChatWatchPartyRepository_RemoveParticipant_Call{Call: _e.mock.On("RemoveParticipant",
		append([]any{ctx, s}, tx...)...)}
}

func (_c *MockChatWatchPartyRepository_RemoveParticipant_Call) Run(run func(ctx context.Context, s spec.WatchPartyParticipantRef, tx ...*sql.Tx)) *MockChatWatchPartyRepository_RemoveParticipant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.WatchPartyParticipantRef
		if args[1] != nil {
			arg1 = args[1].(spec.WatchPartyParticipantRef)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockChatWatchPartyRepository_RemoveParticipant_Call) Return(err error) *MockChatWatchPartyRepository_RemoveParticipant_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChatWatchPartyRepository_RemoveParticipant_Call) RunAndReturn(run func(ctx context.Context, s spec.WatchPartyParticipantRef, tx ...*sql.Tx) error) *MockChatWatchPartyRepository_RemoveParticipant_Call {
	_c.Call.Return(run)
	return _c
}

// SetControllerID provides a mock function for the type MockChatWatchPartyRepository
func (_mock *MockChatWatchPartyRepository) SetControllerID(ctx context.Context, s spec.WatchPartyControllerUpdate, tx ...*sql.Tx) error {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, s, tx)
	} else {
		tmpRet = _mock.Called(ctx, s)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for SetControllerID")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.WatchPartyControllerUpdate, ...*sql.Tx) error); ok {
		r0 = returnFunc(ctx, s, tx...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChatWatchPartyRepository_SetControllerID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetControllerID'
type MockChatWatchPartyRepository_SetControllerID_Call struct {
	*mock.Call
}

// SetControllerID is a helper method to define mock.On call
//   - ctx context.Context
//   - s spec.WatchPartyControllerUpdate
//   - tx ...*sql.Tx
func (_e *MockChatWatchPartyRepository_Expecter) SetControllerID(ctx any, s any, tx ...any) *MockChatWatchPartyRepository_SetControllerID_Call {
	return &MockChatWatchPartyRepository_SetControllerID_Call{Call: _e.mock.On("SetControllerID",
		append([]any{ctx, s}, tx...)...)}
}

func (_c *MockChatWatchPartyRepository_SetControllerID_Call) Run(run func(ctx context.Context, s spec.WatchPartyControllerUpdate, tx ...*sql.Tx)) *MockChatWatchPartyRepository_SetControllerID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.WatchPartyControllerUpdate
		if args[1] != nil {
			arg1 = args[1].(spec.WatchPartyControllerUpdate)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockChatWatchPartyRepository_SetControllerID_Call) Return(err error) *MockChatWatchPartyRepository_SetControllerID_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChatWatchPartyRepository_SetControllerID_Call) RunAndReturn(run func(ctx context.Context, s spec.WatchPartyControllerUpdate, tx ...*sql.Tx) error) *MockChatWatchPartyRepository_SetControllerID_Call {
	_c.Call.Return(run)
	return _c
}

// SetParticipantControl provides a mock function for the type MockChatWatchPartyRepository
func (_mock *MockChatWatchPartyRepository) SetParticipantControl(ctx context.Context, s spec.WatchPartyControlUpdate, tx ...*sql.Tx) error {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, s, tx)
	} else {
		tmpRet = _mock.Called(ctx, s)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for SetParticipantControl")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.WatchPartyControlUpdate, ...*sql.Tx) error); ok {
		r0 = returnFunc(ctx, s, tx...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChatWatchPartyRepository_SetParticipantControl_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetParticipantControl'
type MockChatWatchPartyRepository_SetParticipantControl_Call struct {
	*mock.Call
}

// SetParticipantControl is a helper method to define mock.On call
//   - ctx context.Context
//   - s spec.WatchPartyControlUpdate
//   - tx ...*sql.Tx
func (_e *MockChatWatchPartyRepository_Expecter) SetParticipantControl(ctx any, s any, tx ...any) *MockChatWatchPartyRepository_SetParticipantControl_Call {
	return &MockChatWatchPartyRepository_SetParticipantControl_Call{Call: _e.mock.On("SetParticipantControl",
		append([]any{ctx, s}, tx...)...)}
}

func (_c *MockChatWatchPartyRepository_SetParticipantControl_Call) Run(run func(ctx context.Context, s spec.WatchPartyControlUpdate, tx ...*sql.Tx)) *MockChatWatchPartyRepository_SetParticipantControl_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.WatchPartyControlUpdate
		if args[1] != nil {
			arg1 = args[1].(spec.WatchPartyControlUpdate)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockChatWatchPartyRepository_SetParticipantControl_Call) Return(err error) *MockChatWatchPartyRepository_SetParticipantControl_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChatWatchPartyRepository_SetParticipantControl_Call) RunAndReturn(run func(ctx context.Context, s spec.WatchPartyControlUpdate, tx ...*sql.Tx) error) *MockChatWatchPartyRepository_SetParticipantControl_Call {
	_c.Call.Return(run)
	return _c
}

// SetParticipantIdentifier provides a mock function for the type MockChatWatchPartyRepository
func (_mock *MockChatWatchPartyRepository) SetParticipantIdentifier(ctx context.Context, s spec.WatchPartyIdentifierUpdate, tx ...*sql.Tx) error {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, s, tx)
	} else {
		tmpRet = _mock.Called(ctx, s)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for SetParticipantIdentifier")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.WatchPartyIdentifierUpdate, ...*sql.Tx) error); ok {
		r0 = returnFunc(ctx, s, tx...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChatWatchPartyRepository_SetParticipantIdentifier_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetParticipantIdentifier'
type MockChatWatchPartyRepository_SetParticipantIdentifier_Call struct {
	*mock.Call
}

// SetParticipantIdentifier is a helper method to define mock.On call
//   - ctx context.Context
//   - s spec.WatchPartyIdentifierUpdate
//   - tx ...*sql.Tx
func (_e *MockChatWatchPartyRepository_Expecter) SetParticipantIdentifier(ctx any, s any, tx ...any) *MockChatWatchPartyRepository_SetParticipantIdentifier_Call {
	return &MockChatWatchPartyRepository_SetParticipantIdentifier_Call{Call: _e.mock.On("SetParticipantIdentifier",
		append([]any{ctx, s}, tx...)...)}
}

func (_c *MockChatWatchPartyRepository_SetParticipantIdentifier_Call) Run(run func(ctx context.Context, s spec.WatchPartyIdentifierUpdate, tx ...*sql.Tx)) *MockChatWatchPartyRepository_SetParticipantIdentifier_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.WatchPartyIdentifierUpdate
		if args[1] != nil {
			arg1 = args[1].(spec.WatchPartyIdentifierUpdate)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockChatWatchPartyRepository_SetParticipantIdentifier_Call) Return(err error) *MockChatWatchPartyRepository_SetParticipantIdentifier_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChatWatchPartyRepository_SetParticipantIdentifier_Call) RunAndReturn(run func(ctx context.Context, s spec.WatchPartyIdentifierUpdate, tx ...*sql.Tx) error) *MockChatWatchPartyRepository_SetParticipantIdentifier_Call {
	_c.Call.Return(run)
	return _c
}

// StartSession provides a mock function for the type MockChatWatchPartyRepository
func (_mock *MockChatWatchPartyRepository) StartSession(ctx context.Context, party spec.NewWatchPartySession, tx ...*sql.Tx) (*model.ChatWatchPartySessionRow, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, party, tx)
	} else {
		tmpRet = _mock.Called(ctx, party)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for StartSession")
	}

	var r0 *model.ChatWatchPartySessionRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.NewWatchPartySession, ...*sql.Tx) (*model.ChatWatchPartySessionRow, error)); ok {
		return returnFunc(ctx, party, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.NewWatchPartySession, ...*sql.Tx) *model.ChatWatchPartySessionRow); ok {
		r0 = returnFunc(ctx, party, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ChatWatchPartySessionRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, spec.NewWatchPartySession, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, party, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatWatchPartyRepository_StartSession_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'StartSession'
type MockChatWatchPartyRepository_StartSession_Call struct {
	*mock.Call
}

// StartSession is a helper method to define mock.On call
//   - ctx context.Context
//   - party spec.NewWatchPartySession
//   - tx ...*sql.Tx
func (_e *MockChatWatchPartyRepository_Expecter) StartSession(ctx any, party any, tx ...any) *MockChatWatchPartyRepository_StartSession_Call {
	return &MockChatWatchPartyRepository_StartSession_Call{Call: _e.mock.On("StartSession",
		append([]any{ctx, party}, tx...)...)}
}

func (_c *MockChatWatchPartyRepository_StartSession_Call) Run(run func(ctx context.Context, party spec.NewWatchPartySession, tx ...*sql.Tx)) *MockChatWatchPartyRepository_StartSession_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.NewWatchPartySession
		if args[1] != nil {
			arg1 = args[1].(spec.NewWatchPartySession)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockChatWatchPartyRepository_StartSession_Call) Return(chatWatchPartySessionRow *model.ChatWatchPartySessionRow, err error) *MockChatWatchPartyRepository_StartSession_Call {
	_c.Call.Return(chatWatchPartySessionRow, err)
	return _c
}

func (_c *MockChatWatchPartyRepository_StartSession_Call) RunAndReturn(run func(ctx context.Context, party spec.NewWatchPartySession, tx ...*sql.Tx) (*model.ChatWatchPartySessionRow, error)) *MockChatWatchPartyRepository_StartSession_Call {
	_c.Call.Return(run)
	return _c
}

// TransferControl provides a mock function for the type MockChatWatchPartyRepository
func (_mock *MockChatWatchPartyRepository) TransferControl(ctx context.Context, s spec.WatchPartyControlTransfer, tx ...*sql.Tx) error {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, s, tx)
	} else {
		tmpRet = _mock.Called(ctx, s)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for TransferControl")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.WatchPartyControlTransfer, ...*sql.Tx) error); ok {
		r0 = returnFunc(ctx, s, tx...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChatWatchPartyRepository_TransferControl_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TransferControl'
type MockChatWatchPartyRepository_TransferControl_Call struct {
	*mock.Call
}

// TransferControl is a helper method to define mock.On call
//   - ctx context.Context
//   - s spec.WatchPartyControlTransfer
//   - tx ...*sql.Tx
func (_e *MockChatWatchPartyRepository_Expecter) TransferControl(ctx any, s any, tx ...any) *MockChatWatchPartyRepository_TransferControl_Call {
	return &MockChatWatchPartyRepository_TransferControl_Call{Call: _e.mock.On("TransferControl",
		append([]any{ctx, s}, tx...)...)}
}

func (_c *MockChatWatchPartyRepository_TransferControl_Call) Run(run func(ctx context.Context, s spec.WatchPartyControlTransfer, tx ...*sql.Tx)) *MockChatWatchPartyRepository_TransferControl_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.WatchPartyControlTransfer
		if args[1] != nil {
			arg1 = args[1].(spec.WatchPartyControlTransfer)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockChatWatchPartyRepository_TransferControl_Call) Return(err error) *MockChatWatchPartyRepository_TransferControl_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChatWatchPartyRepository_TransferControl_Call) RunAndReturn(run func(ctx context.Context, s spec.WatchPartyControlTransfer, tx ...*sql.Tx) error) *MockChatWatchPartyRepository_TransferControl_Call {
	_c.Call.Return(run)
	return _c
}

// UpsertParticipant provides a mock function for the type MockChatWatchPartyRepository
func (_mock *MockChatWatchPartyRepository) UpsertParticipant(ctx context.Context, s spec.WatchPartyParticipantUpsert, tx ...*sql.Tx) error {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, s, tx)
	} else {
		tmpRet = _mock.Called(ctx, s)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UpsertParticipant")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.WatchPartyParticipantUpsert, ...*sql.Tx) error); ok {
		r0 = returnFunc(ctx, s, tx...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChatWatchPartyRepository_UpsertParticipant_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpsertParticipant'
type MockChatWatchPartyRepository_UpsertParticipant_Call struct {
	*mock.Call
}

// UpsertParticipant is a helper method to define mock.On call
//   - ctx context.Context
//   - s spec.WatchPartyParticipantUpsert
//   - tx ...*sql.Tx
func (_e *MockChatWatchPartyRepository_Expecter) UpsertParticipant(ctx any, s any, tx ...any) *MockChatWatchPartyRepository_UpsertParticipant_Call {
	return &MockChatWatchPartyRepository_UpsertParticipant_Call{Call: _e.mock.On("UpsertParticipant",
		append([]any{ctx, s}, tx...)...)}
}

func (_c *MockChatWatchPartyRepository_UpsertParticipant_Call) Run(run func(ctx context.Context, s spec.WatchPartyParticipantUpsert, tx ...*sql.Tx)) *MockChatWatchPartyRepository_UpsertParticipant_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.WatchPartyParticipantUpsert
		if args[1] != nil {
			arg1 = args[1].(spec.WatchPartyParticipantUpsert)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockChatWatchPartyRepository_UpsertParticipant_Call) Return(err error) *MockChatWatchPartyRepository_UpsertParticipant_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChatWatchPartyRepository_UpsertParticipant_Call) RunAndReturn(run func(ctx context.Context, s spec.WatchPartyParticipantUpsert, tx ...*sql.Tx) error) *MockChatWatchPartyRepository_UpsertParticipant_Call {
	_c.Call.Return(run)
	return _c
}
