// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"
	"database/sql"
	"umineko_city_of_books/internal/model"
	"umineko_city_of_books/internal/model/spec"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockEmailVerificationRepository creates a new instance of MockEmailVerificationRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEmailVerificationRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEmailVerificationRepository {
	mock := &MockEmailVerificationRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEmailVerificationRepository is an autogenerated mock type for the EmailVerificationRepository type
type MockEmailVerificationRepository struct {
	mock.Mock
}

type MockEmailVerificationRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEmailVerificationRepository) EXPECT() *MockEmailVerificationRepository_Expecter {
	return &MockEmailVerificationRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockEmailVerificationRepository
func (_mock *MockEmailVerificationRepository) Create(ctx context.Context, s spec.NewEmailVerification, tx ...*sql.Tx) error {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, s, tx)
	} else {
		tmpRet = _mock.Called(ctx, s)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.NewEmailVerification, ...*sql.Tx) error); ok {
		r0 = returnFunc(ctx, s, tx...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEmailVerificationRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockEmailVerificationRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - s spec.NewEmailVerification
//   - tx ...*sql.Tx
func (_e *MockEmailVerificationRepository_Expecter) Create(ctx any, s any, tx ...any) *MockEmailVerificationRepository_Create_Call {
	return &MockEmailVerificationRepository_Create_Call{Call: _e.mock.On("Create",
		append([]any{ctx, s}, tx...)...)}
}

func (_c *MockEmailVerificationRepository_Create_Call) Run(run func(ctx context.Context, s spec.NewEmailVerification, tx ...*sql.Tx)) *MockEmailVerificationRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.NewEmailVerification
		if args[1] != nil {
			arg1 = args[1].(spec.NewEmailVerification)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockEmailVerificationRepository_Create_Call) Return(err error) *MockEmailVerificationRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEmailVerificationRepository_Create_Call) RunAndReturn(run func(ctx context.Context, s spec.NewEmailVerification, tx ...*sql.Tx) error) *MockEmailVerificationRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteUnusedForUser provides a mock function for the type MockEmailVerificationRepository
func (_mock *MockEmailVerificationRepository) DeleteUnusedForUser(ctx context.Context, userID uuid.UUID, tx ...*sql.Tx) error {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, userID, tx)
	} else {
		tmpRet = _mock.Called(ctx, userID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DeleteUnusedForUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...*sql.Tx) error); ok {
		r0 = returnFunc(ctx, userID, tx...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEmailVerificationRepository_DeleteUnusedForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteUnusedForUser'
type MockEmailVerificationRepository_DeleteUnusedForUser_Call struct {
	*mock.Call
}

// DeleteUnusedForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - tx ...*sql.Tx
func (_e *MockEmailVerificationRepository_Expecter) DeleteUnusedForUser(ctx any, userID any, tx ...any) *MockEmailVerificationRepository_DeleteUnusedForUser_Call {
	return &MockEmailVerificationRepository_DeleteUnusedForUser_Call{Call: _e.mock.On("DeleteUnusedForUser",
		append([]any{ctx, userID}, tx...)...)}
}

func (_c *MockEmailVerificationRepository_DeleteUnusedForUser_Call) Run(run func(ctx context.Context, userID uuid.UUID, tx ...*sql.Tx)) *MockEmailVerificationRepository_DeleteUnusedForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockEmailVerificationRepository_DeleteUnusedForUser_Call) Return(err error) *MockEmailVerificationRepository_DeleteUnusedForUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEmailVerificationRepository_DeleteUnusedForUser_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, tx ...*sql.Tx) error) *MockEmailVerificationRepository_DeleteUnusedForUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetByTokenHash provides a mock function for the type MockEmailVerificationRepository
func (_mock *MockEmailVerificationRepository) GetByTokenHash(ctx context.Context, tokenHash string, tx ...*sql.Tx) (*model.EmailVerificationToken, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, tokenHash, tx)
	} else {
		tmpRet = _mock.Called(ctx, tokenHash)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetByTokenHash")
	}

	var r0 *model.EmailVerificationToken
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...*sql.Tx) (*model.EmailVerificationToken, error)); ok {
		return returnFunc(ctx, tokenHash, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...*sql.Tx) *model.EmailVerificationToken); ok {
		r0 = returnFunc(ctx, tokenHash, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.EmailVerificationToken)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, tokenHash, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEmailVerificationRepository_GetByTokenHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByTokenHash'
type MockEmailVerificationRepository_GetByTokenHash_Call struct {
	*mock.Call
}

// GetByTokenHash is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
//   - tx ...*sql.Tx
func (_e *MockEmailVerificationRepository_Expecter) GetByTokenHash(ctx any, tokenHash any, tx ...any) *MockEmailVerificationRepository_GetByTokenHash_Call {
	return &MockEmailVerificationRepository_GetByTokenHash_Call{Call: _e.mock.On("GetByTokenHash",
		append([]any{ctx, tokenHash}, tx...)...)}
}

func (_c *MockEmailVerificationRepository_GetByTokenHash_Call) Run(run func(ctx context.Context, tokenHash string, tx ...*sql.Tx)) *MockEmailVerificationRepository_GetByTokenHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockEmailVerificationRepository_GetByTokenHash_Call) Return(emailVerificationToken *model.EmailVerificationToken, err error) *MockEmailVerificationRepository_GetByTokenHash_Call {
	_c.Call.Return(emailVerificationToken, err)
	return _c
}

func (_c *MockEmailVerificationRepository_GetByTokenHash_Call) RunAndReturn(run func(ctx context.Context, tokenHash string, tx ...*sql.Tx) (*model.EmailVerificationToken, error)) *MockEmailVerificationRepository_GetByTokenHash_Call {
	_c.Call.Return(run)
	return _c
}

// Issue provides a mock function for the type MockEmailVerificationRepository
func (_mock *MockEmailVerificationRepository) Issue(ctx context.Context, s spec.NewEmailVerification, tx ...*sql.Tx) error {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, s, tx)
	} else {
		tmpRet = _mock.Called(ctx, s)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Issue")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.NewEmailVerification, ...*sql.Tx) error); ok {
		r0 = returnFunc(ctx, s, tx...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEmailVerificationRepository_Issue_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Issue'
type MockEmailVerificationRepository_Issue_Call struct {
	*mock.Call
}

// Issue is a helper method to define mock.On call
//   - ctx context.Context
//   - s spec.NewEmailVerification
//   - tx ...*sql.Tx
func (_e *MockEmailVerificationRepository_Expecter) Issue(ctx any, s any, tx ...any) *MockEmailVerificationRepository_Issue_Call {
	return &MockEmailVerificationRepository_Issue_Call{Call: _e.mock.On("Issue",
		append([]any{ctx, s}, tx...)...)}
}

func (_c *MockEmailVerificationRepository_Issue_Call) Run(run func(ctx context.Context, s spec.NewEmailVerification, tx ...*sql.Tx)) *MockEmailVerificationRepository_Issue_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.NewEmailVerification
		if args[1] != nil {
			arg1 = args[1].(spec.NewEmailVerification)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockEmailVerificationRepository_Issue_Call) Return(err error) *MockEmailVerificationRepository_Issue_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEmailVerificationRepository_Issue_Call) RunAndReturn(run func(ctx context.Context, s spec.NewEmailVerification, tx ...*sql.Tx) error) *MockEmailVerificationRepository_Issue_Call {
	_c.Call.Return(run)
	return _c
}

// MarkUsed provides a mock function for the type MockEmailVerificationRepository
func (_mock *MockEmailVerificationRepository) MarkUsed(ctx context.Context, tokenHash string, tx ...*sql.Tx) error {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, tokenHash, tx)
	} else {
		tmpRet = _mock.Called(ctx, tokenHash)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for MarkUsed")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...*sql.Tx) error); ok {
		r0 = returnFunc(ctx, tokenHash, tx...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockEmailVerificationRepository_MarkUsed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkUsed'
type MockEmailVerificationRepository_MarkUsed_Call struct {
	*mock.Call
}

// MarkUsed is a helper method to define mock.On call
//   - ctx context.Context
//   - tokenHash string
//   - tx ...*sql.Tx
func (_e *MockEmailVerificationRepository_Expecter) MarkUsed(ctx any, tokenHash any, tx ...any) *MockEmailVerificationRepository_MarkUsed_Call {
	return &MockEmailVerificationRepository_MarkUsed_Call{Call: _e.mock.On("MarkUsed",
		append([]any{ctx, tokenHash}, tx...)...)}
}

func (_c *MockEmailVerificationRepository_MarkUsed_Call) Run(run func(ctx context.Context, tokenHash string, tx ...*sql.Tx)) *MockEmailVerificationRepository_MarkUsed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockEmailVerificationRepository_MarkUsed_Call) Return(err error) *MockEmailVerificationRepository_MarkUsed_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockEmailVerificationRepository_MarkUsed_Call) RunAndReturn(run func(ctx context.Context, tokenHash string, tx ...*sql.Tx) error) *MockEmailVerificationRepository_MarkUsed_Call {
	_c.Call.Return(run)
	return _c
}
