// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"
	"database/sql"
	"umineko_city_of_books/internal/model"
	"umineko_city_of_books/internal/model/spec"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockSecretRepository creates a new instance of MockSecretRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSecretRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSecretRepository {
	mock := &MockSecretRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSecretRepository is an autogenerated mock type for the SecretRepository type
type MockSecretRepository struct {
	mock.Mock
}

type MockSecretRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSecretRepository) EXPECT() *MockSecretRepository_Expecter {
	return &MockSecretRepository_Expecter{mock: &_m.Mock}
}

// AddCommentMedia provides a mock function for the type MockSecretRepository
func (_mock *MockSecretRepository) AddCommentMedia(ctx context.Context, s spec.NewMedia, tx ...*sql.Tx) (int64, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, s, tx)
	} else {
		tmpRet = _mock.Called(ctx, s)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for AddCommentMedia")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.NewMedia, ...*sql.Tx) (int64, error)); ok {
		return returnFunc(ctx, s, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.NewMedia, ...*sql.Tx) int64); ok {
		r0 = returnFunc(ctx, s, tx...)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, spec.NewMedia, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, s, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSecretRepository_AddCommentMedia_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddCommentMedia'
type MockSecretRepository_AddCommentMedia_Call struct {
	*mock.Call
}

// AddCommentMedia is a helper method to define mock.On call
//   - ctx context.Context
//   - s spec.NewMedia
//   - tx ...*sql.Tx
func (_e *MockSecretRepository_Expecter) AddCommentMedia(ctx any, s any, tx ...any) *MockSecretRepository_AddCommentMedia_Call {
	return &MockSecretRepository_AddCommentMedia_Call{Call: _e.mock.On("AddCommentMedia",
		append([]any{ctx, s}, tx...)...)}
}

func (_c *MockSecretRepository_AddCommentMedia_Call) Run(run func(ctx context.Context, s spec.NewMedia, tx ...*sql.Tx)) *MockSecretRepository_AddCommentMedia_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.NewMedia
		if args[1] != nil {
			arg1 = args[1].(spec.NewMedia)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockSecretRepository_AddCommentMedia_Call) Return(n int64, err error) *MockSecretRepository_AddCommentMedia_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockSecretRepository_AddCommentMedia_Call) RunAndReturn(run func(ctx context.Context, s spec.NewMedia, tx ...*sql.Tx) (int64, error)) *MockSecretRepository_AddCommentMedia_Call {
	_c.Call.Return(run)
	return _c
}

// CollectCommentMediaPaths provides a mock function for the type MockSecretRepository
func (_mock *MockSecretRepository) CollectCommentMediaPaths(ctx context.Context, entityID string, tx ...*sql.Tx) ([]string, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, entityID, tx)
	} else {
		tmpRet = _mock.Called(ctx, entityID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for CollectCommentMediaPaths")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...*sql.Tx) ([]string, error)); ok {
		return returnFunc(ctx, entityID, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...*sql.Tx) []string); ok {
		r0 = returnFunc(ctx, entityID, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, entityID, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSecretRepository_CollectCommentMediaPaths_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CollectCommentMediaPaths'
type MockSecretRepository_CollectCommentMediaPaths_Call struct {
	*mock.Call
}

// CollectCommentMediaPaths is a helper method to define mock.On call
//   - ctx context.Context
//   - entityID string
//   - tx ...*sql.Tx
func (_e *MockSecretRepository_Expecter) CollectCommentMediaPaths(ctx any, entityID any, tx ...any) *MockSecretRepository_CollectCommentMediaPaths_Call {
	return &MockSecretRepository_CollectCommentMediaPaths_Call{Call: _e.mock.On("CollectCommentMediaPaths",
		append([]any{ctx, entityID}, tx...)...)}
}

func (_c *MockSecretRepository_CollectCommentMediaPaths_Call) Run(run func(ctx context.Context, entityID string, tx ...*sql.Tx)) *MockSecretRepository_CollectCommentMediaPaths_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockSecretRepository_CollectCommentMediaPaths_Call) Return(strings []string, err error) *MockSecretRepository_CollectCommentMediaPaths_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockSecretRepository_CollectCommentMediaPaths_Call) RunAndReturn(run func(ctx context.Context, entityID string, tx ...*sql.Tx) ([]string, error)) *MockSecretRepository_CollectCommentMediaPaths_Call {
	_c.Call.Return(run)
	return _c
}

// CollectSingleCommentMediaPaths provides a mock function for the type MockSecretRepository
func (_mock *MockSecretRepository) CollectSingleCommentMediaPaths(ctx context.Context, commentID uuid.UUID, tx ...*sql.Tx) ([]string, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, commentID, tx)
	} else {
		tmpRet = _mock.Called(ctx, commentID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for CollectSingleCommentMediaPaths")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...*sql.Tx) ([]string, error)); ok {
		return returnFunc(ctx, commentID, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...*sql.Tx) []string); ok {
		r0 = returnFunc(ctx, commentID, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, commentID, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSecretRepository_CollectSingleCommentMediaPaths_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CollectSingleCommentMediaPaths'
type MockSecretRepository_CollectSingleCommentMediaPaths_Call struct {
	*mock.Call
}

// CollectSingleCommentMediaPaths is a helper method to define mock.On call
//   - ctx context.Context
//   - commentID uuid.UUID
//   - tx ...*sql.Tx
func (_e *MockSecretRepository_Expecter) CollectSingleCommentMediaPaths(ctx any, commentID any, tx ...any) *MockSecretRepository_CollectSingleCommentMediaPaths_Call {
	return &MockSecretRepository_CollectSingleCommentMediaPaths_Call{Call: _e.mock.On("CollectSingleCommentMediaPaths",
		append([]any{ctx, commentID}, tx...)...)}
}

func (_c *MockSecretRepository_CollectSingleCommentMediaPaths_Call) Run(run func(ctx context.Context, commentID uuid.UUID, tx ...*sql.Tx)) *MockSecretRepository_CollectSingleCommentMediaPaths_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockSecretRepository_CollectSingleCommentMediaPaths_Call) Return(strings []string, err error) *MockSecretRepository_CollectSingleCommentMediaPaths_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockSecretRepository_CollectSingleCommentMediaPaths_Call) RunAndReturn(run func(ctx context.Context, commentID uuid.UUID, tx ...*sql.Tx) ([]string, error)) *MockSecretRepository_CollectSingleCommentMediaPaths_Call {
	_c.Call.Return(run)
	return _c
}

// CountCommentsBySecret provides a mock function for the type MockSecretRepository
func (_mock *MockSecretRepository) CountCommentsBySecret(ctx context.Context, secretIDs []string, tx ...*sql.Tx) (map[string]int, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, secretIDs, tx)
	} else {
		tmpRet = _mock.Called(ctx, secretIDs)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for CountCommentsBySecret")
	}

	var r0 map[string]int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, ...*sql.Tx) (map[string]int, error)); ok {
		return returnFunc(ctx, secretIDs, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, ...*sql.Tx) map[string]int); ok {
		r0 = returnFunc(ctx, secretIDs, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]int)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, secretIDs, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSecretRepository_CountCommentsBySecret_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CountCommentsBySecret'
type MockSecretRepository_CountCommentsBySecret_Call struct {
	*mock.Call
}

// CountCommentsBySecret is a helper method to define mock.On call
//   - ctx context.Context
//   - secretIDs []string
//   - tx ...*sql.Tx
func (_e *MockSecretRepository_Expecter) CountCommentsBySecret(ctx any, secretIDs any, tx ...any) *MockSecretRepository_CountCommentsBySecret_Call {
	return &MockSecretRepository_CountCommentsBySecret_Call{Call: _e.mock.On("CountCommentsBySecret",
		append([]any{ctx, secretIDs}, tx...)...)}
}

func (_c *MockSecretRepository_CountCommentsBySecret_Call) Run(run func(ctx context.Context, secretIDs []string, tx ...*sql.Tx)) *MockSecretRepository_CountCommentsBySecret_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockSecretRepository_CountCommentsBySecret_Call) Return(stringToInt map[string]int, err error) *MockSecretRepository_CountCommentsBySecret_Call {
	_c.Call.Return(stringToInt, err)
	return _c
}

func (_c *MockSecretRepository_CountCommentsBySecret_Call) RunAndReturn(run func(ctx context.Context, secretIDs []string, tx ...*sql.Tx) (map[string]int, error)) *MockSecretRepository_CountCommentsBySecret_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteComment provides a mock function for the type MockSecretRepository
func (_mock *MockSecretRepository) DeleteComment(ctx context.Context, s spec.CommentDeletion, tx ...*sql.Tx) error {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, s, tx)
	} else {
		tmpRet = _mock.Called(ctx, s)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DeleteComment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.CommentDeletion, ...*sql.Tx) error); ok {
		r0 = returnFunc(ctx, s, tx...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSecretRepository_DeleteComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteComment'
type MockSecretRepository_DeleteComment_Call struct {
	*mock.Call
}

// DeleteComment is a helper method to define mock.On call
//   - ctx context.Context
//   - s spec.CommentDeletion
//   - tx ...*sql.Tx
func (_e *MockSecretRepository_Expecter) DeleteComment(ctx any, s any, tx ...any) *MockSecretRepository_DeleteComment_Call {
	return &MockSecretRepository_DeleteComment_Call{Call: _e.mock.On("DeleteComment",
		append([]any{ctx, s}, tx...)...)}
}

func (_c *MockSecretRepository_DeleteComment_Call) Run(run func(ctx context.Context, s spec.CommentDeletion, tx ...*sql.Tx)) *MockSecretRepository_DeleteComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.CommentDeletion
		if args[1] != nil {
			arg1 = args[1].(spec.CommentDeletion)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockSecretRepository_DeleteComment_Call) Return(err error) *MockSecretRepository_DeleteComment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSecretRepository_DeleteComment_Call) RunAndReturn(run func(ctx context.Context, s spec.CommentDeletion, tx ...*sql.Tx) error) *MockSecretRepository_DeleteComment_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCommentWithAudit provides a mock function for the type MockSecretRepository
func (_mock *MockSecretRepository) DeleteCommentWithAudit(ctx context.Context, deletion spec.CommentDeletion, tx ...*sql.Tx) ([]string, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, deletion, tx)
	} else {
		tmpRet = _mock.Called(ctx, deletion)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DeleteCommentWithAudit")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.CommentDeletion, ...*sql.Tx) ([]string, error)); ok {
		return returnFunc(ctx, deletion, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.CommentDeletion, ...*sql.Tx) []string); ok {
		r0 = returnFunc(ctx, deletion, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, spec.CommentDeletion, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, deletion, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSecretRepository_DeleteCommentWithAudit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCommentWithAudit'
type MockSecretRepository_DeleteCommentWithAudit_Call struct {
	*mock.Call
}

// DeleteCommentWithAudit is a helper method to define mock.On call
//   - ctx context.Context
//   - deletion spec.CommentDeletion
//   - tx ...*sql.Tx
func (_e *MockSecretRepository_Expecter) DeleteCommentWithAudit(ctx any, deletion any, tx ...any) *MockSecretRepository_DeleteCommentWithAudit_Call {
	return &MockSecretRepository_DeleteCommentWithAudit_Call{Call: _e.mock.On("DeleteCommentWithAudit",
		append([]any{ctx, deletion}, tx...)...)}
}

func (_c *MockSecretRepository_DeleteCommentWithAudit_Call) Run(run func(ctx context.Context, deletion spec.CommentDeletion, tx ...*sql.Tx)) *MockSecretRepository_DeleteCommentWithAudit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.CommentDeletion
		if args[1] != nil {
			arg1 = args[1].(spec.CommentDeletion)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockSecretRepository_DeleteCommentWithAudit_Call) Return(strings []string, err error) *MockSecretRepository_DeleteCommentWithAudit_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockSecretRepository_DeleteCommentWithAudit_Call) RunAndReturn(run func(ctx context.Context, deletion spec.CommentDeletion, tx ...*sql.Tx) ([]string, error)) *MockSecretRepository_DeleteCommentWithAudit_Call {
	_c.Call.Return(run)
	return _c
}

// GetCommentAuthorID provides a mock function for the type MockSecretRepository
func (_mock *MockSecretRepository) GetCommentAuthorID(ctx context.Context, commentID uuid.UUID, tx ...*sql.Tx) (uuid.UUID, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, commentID, tx)
	} else {
		tmpRet = _mock.Called(ctx, commentID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetCommentAuthorID")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...*sql.Tx) (uuid.UUID, error)); ok {
		return returnFunc(ctx, commentID, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...*sql.Tx) uuid.UUID); ok {
		r0 = returnFunc(ctx, commentID, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, commentID, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSecretRepository_GetCommentAuthorID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCommentAuthorID'
type MockSecretRepository_GetCommentAuthorID_Call struct {
	*mock.Call
}

// GetCommentAuthorID is a helper method to define mock.On call
//   - ctx context.Context
//   - commentID uuid.UUID
//   - tx ...*sql.Tx
func (_e *MockSecretRepository_Expecter) GetCommentAuthorID(ctx any, commentID any, tx ...any) *MockSecretRepository_GetCommentAuthorID_Call {
	return &MockSecretRepository_GetCommentAuthorID_Call{Call: _e.mock.On("GetCommentAuthorID",
		append([]any{ctx, commentID}, tx...)...)}
}

func (_c *MockSecretRepository_GetCommentAuthorID_Call) Run(run func(ctx context.Context, commentID uuid.UUID, tx ...*sql.Tx)) *MockSecretRepository_GetCommentAuthorID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockSecretRepository_GetCommentAuthorID_Call) Return(uUID uuid.UUID, err error) *MockSecretRepository_GetCommentAuthorID_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockSecretRepository_GetCommentAuthorID_Call) RunAndReturn(run func(ctx context.Context, commentID uuid.UUID, tx ...*sql.Tx) (uuid.UUID, error)) *MockSecretRepository_GetCommentAuthorID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCommentByID provides a mock function for the type MockSecretRepository
func (_mock *MockSecretRepository) GetCommentByID(ctx context.Context, id uuid.UUID, tx ...*sql.Tx) (*model.CommentRow, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, id, tx)
	} else {
		tmpRet = _mock.Called(ctx, id)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetCommentByID")
	}

	var r0 *model.CommentRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...*sql.Tx) (*model.CommentRow, error)); ok {
		return returnFunc(ctx, id, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...*sql.Tx) *model.CommentRow); ok {
		r0 = returnFunc(ctx, id, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.CommentRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, id, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSecretRepository_GetCommentByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCommentByID'
type MockSecretRepository_GetCommentByID_Call struct {
	*mock.Call
}

// GetCommentByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - tx ...*sql.Tx
func (_e *MockSecretRepository_Expecter) GetCommentByID(ctx any, id any, tx ...any) *MockSecretRepository_GetCommentByID_Call {
	return &MockSecretRepository_GetCommentByID_Call{Call: _e.mock.On("GetCommentByID",
		append([]any{ctx, id}, tx...)...)}
}

func (_c *MockSecretRepository_GetCommentByID_Call) Run(run func(ctx context.Context, id uuid.UUID, tx ...*sql.Tx)) *MockSecretRepository_GetCommentByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockSecretRepository_GetCommentByID_Call) Return(commentRow *model.CommentRow, err error) *MockSecretRepository_GetCommentByID_Call {
	_c.Call.Return(commentRow, err)
	return _c
}

func (_c *MockSecretRepository_GetCommentByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, tx ...*sql.Tx) (*model.CommentRow, error)) *MockSecretRepository_GetCommentByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCommentEntityID provides a mock function for the type MockSecretRepository
func (_mock *MockSecretRepository) GetCommentEntityID(ctx context.Context, commentID uuid.UUID, tx ...*sql.Tx) (string, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, commentID, tx)
	} else {
		tmpRet = _mock.Called(ctx, commentID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetCommentEntityID")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...*sql.Tx) (string, error)); ok {
		return returnFunc(ctx, commentID, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...*sql.Tx) string); ok {
		r0 = returnFunc(ctx, commentID, tx...)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, commentID, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSecretRepository_GetCommentEntityID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCommentEntityID'
type MockSecretRepository_GetCommentEntityID_Call struct {
	*mock.Call
}

// GetCommentEntityID is a helper method to define mock.On call
//   - ctx context.Context
//   - commentID uuid.UUID
//   - tx ...*sql.Tx
func (_e *MockSecretRepository_Expecter) GetCommentEntityID(ctx any, commentID any, tx ...any) *MockSecretRepository_GetCommentEntityID_Call {
	return &MockSecretRepository_GetCommentEntityID_Call{Call: _e.mock.On("GetCommentEntityID",
		append([]any{ctx, commentID}, tx...)...)}
}

func (_c *MockSecretRepository_GetCommentEntityID_Call) Run(run func(ctx context.Context, commentID uuid.UUID, tx ...*sql.Tx)) *MockSecretRepository_GetCommentEntityID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockSecretRepository_GetCommentEntityID_Call) Return(s string, err error) *MockSecretRepository_GetCommentEntityID_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockSecretRepository_GetCommentEntityID_Call) RunAndReturn(run func(ctx context.Context, commentID uuid.UUID, tx ...*sql.Tx) (string, error)) *MockSecretRepository_GetCommentEntityID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCommentMedia provides a mock function for the type MockSecretRepository
func (_mock *MockSecretRepository) GetCommentMedia(ctx context.Context, commentID uuid.UUID, tx ...*sql.Tx) ([]model.PostMediaRow, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, commentID, tx)
	} else {
		tmpRet = _mock.Called(ctx, commentID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetCommentMedia")
	}

	var r0 []model.PostMediaRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...*sql.Tx) ([]model.PostMediaRow, error)); ok {
		return returnFunc(ctx, commentID, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...*sql.Tx) []model.PostMediaRow); ok {
		r0 = returnFunc(ctx, commentID, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.PostMediaRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, commentID, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSecretRepository_GetCommentMedia_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCommentMedia'
type MockSecretRepository_GetCommentMedia_Call struct {
	*mock.Call
}

// GetCommentMedia is a helper method to define mock.On call
//   - ctx context.Context
//   - commentID uuid.UUID
//   - tx ...*sql.Tx
func (_e *MockSecretRepository_Expecter) GetCommentMedia(ctx any, commentID any, tx ...any) *MockSecretRepository_GetCommentMedia_Call {
	return &MockSecretRepository_GetCommentMedia_Call{Call: _e.mock.On("GetCommentMedia",
		append([]any{ctx, commentID}, tx...)...)}
}

func (_c *MockSecretRepository_GetCommentMedia_Call) Run(run func(ctx context.Context, commentID uuid.UUID, tx ...*sql.Tx)) *MockSecretRepository_GetCommentMedia_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockSecretRepository_GetCommentMedia_Call) Return(postMediaRows []model.PostMediaRow, err error) *MockSecretRepository_GetCommentMedia_Call {
	_c.Call.Return(postMediaRows, err)
	return _c
}

func (_c *MockSecretRepository_GetCommentMedia_Call) RunAndReturn(run func(ctx context.Context, commentID uuid.UUID, tx ...*sql.Tx) ([]model.PostMediaRow, error)) *MockSecretRepository_GetCommentMedia_Call {
	_c.Call.Return(run)
	return _c
}

// GetCommentMediaBatch provides a mock function for the type MockSecretRepository
func (_mock *MockSecretRepository) GetCommentMediaBatch(ctx context.Context, commentIDs []uuid.UUID, tx ...*sql.Tx) (map[uuid.UUID][]model.PostMediaRow, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, commentIDs, tx)
	} else {
		tmpRet = _mock.Called(ctx, commentIDs)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetCommentMediaBatch")
	}

	var r0 map[uuid.UUID][]model.PostMediaRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID, ...*sql.Tx) (map[uuid.UUID][]model.PostMediaRow, error)); ok {
		return returnFunc(ctx, commentIDs, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID, ...*sql.Tx) map[uuid.UUID][]model.PostMediaRow); ok {
		r0 = returnFunc(ctx, commentIDs, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[uuid.UUID][]model.PostMediaRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []uuid.UUID, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, commentIDs, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSecretRepository_GetCommentMediaBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCommentMediaBatch'
type MockSecretRepository_GetCommentMediaBatch_Call struct {
	*mock.Call
}

// GetCommentMediaBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - commentIDs []uuid.UUID
//   - tx ...*sql.Tx
func (_e *MockSecretRepository_Expecter) GetCommentMediaBatch(ctx any, commentIDs any, tx ...any) *MockSecretRepository_GetCommentMediaBatch_Call {
	return &MockSecretRepository_GetCommentMediaBatch_Call{Call: _e.mock.On("GetCommentMediaBatch",
		append([]any{ctx, commentIDs}, tx...)...)}
}

func (_c *MockSecretRepository_GetCommentMediaBatch_Call) Run(run func(ctx context.Context, commentIDs []uuid.UUID, tx ...*sql.Tx)) *MockSecretRepository_GetCommentMediaBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockSecretRepository_GetCommentMediaBatch_Call) Return(uUIDToPostMediaRows map[uuid.UUID][]model.PostMediaRow, err error) *MockSecretRepository_GetCommentMediaBatch_Call {
	_c.Call.Return(uUIDToPostMediaRows, err)
	return _c
}

func (_c *MockSecretRepository_GetCommentMediaBatch_Call) RunAndReturn(run func(ctx context.Context, commentIDs []uuid.UUID, tx ...*sql.Tx) (map[uuid.UUID][]model.PostMediaRow, error)) *MockSecretRepository_GetCommentMediaBatch_Call {
	_c.Call.Return(run)
	return _c
}

// GetCommenterIDs provides a mock function for the type MockSecretRepository
func (_mock *MockSecretRepository) GetCommenterIDs(ctx context.Context, secretID string, tx ...*sql.Tx) ([]uuid.UUID, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, secretID, tx)
	} else {
		tmpRet = _mock.Called(ctx, secretID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetCommenterIDs")
	}

	var r0 []uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...*sql.Tx) ([]uuid.UUID, error)); ok {
		return returnFunc(ctx, secretID, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...*sql.Tx) []uuid.UUID); ok {
		r0 = returnFunc(ctx, secretID, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, secretID, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSecretRepository_GetCommenterIDs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCommenterIDs'
type MockSecretRepository_GetCommenterIDs_Call struct {
	*mock.Call
}

// GetCommenterIDs is a helper method to define mock.On call
//   - ctx context.Context
//   - secretID string
//   - tx ...*sql.Tx
func (_e *MockSecretRepository_Expecter) GetCommenterIDs(ctx any, secretID any, tx ...any) *MockSecretRepository_GetCommenterIDs_Call {
	return &MockSecretRepository_GetCommenterIDs_Call{Call: _e.mock.On("GetCommenterIDs",
		append([]any{ctx, secretID}, tx...)...)}
}

func (_c *MockSecretRepository_GetCommenterIDs_Call) Run(run func(ctx context.Context, secretID string, tx ...*sql.Tx)) *MockSecretRepository_GetCommenterIDs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockSecretRepository_GetCommenterIDs_Call) Return(uUIDs []uuid.UUID, err error) *MockSecretRepository_GetCommenterIDs_Call {
	_c.Call.Return(uUIDs, err)
	return _c
}

func (_c *MockSecretRepository_GetCommenterIDs_Call) RunAndReturn(run func(ctx context.Context, secretID string, tx ...*sql.Tx) ([]uuid.UUID, error)) *MockSecretRepository_GetCommenterIDs_Call {
	_c.Call.Return(run)
	return _c
}

// GetComments provides a mock function for the type MockSecretRepository
func (_mock *MockSecretRepository) GetComments(ctx context.Context, q spec.CommentQuery[string], tx ...*sql.Tx) ([]model.CommentRow, int, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, q, tx)
	} else {
		tmpRet = _mock.Called(ctx, q)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetComments")
	}

	var r0 []model.CommentRow
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.CommentQuery[string], ...*sql.Tx) ([]model.CommentRow, int, error)); ok {
		return returnFunc(ctx, q, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.CommentQuery[string], ...*sql.Tx) []model.CommentRow); ok {
		r0 = returnFunc(ctx, q, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.CommentRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, spec.CommentQuery[string], ...*sql.Tx) int); ok {
		r1 = returnFunc(ctx, q, tx...)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, spec.CommentQuery[string], ...*sql.Tx) error); ok {
		r2 = returnFunc(ctx, q, tx...)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockSecretRepository_GetComments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetComments'
type MockSecretRepository_GetComments_Call struct {
	*mock.Call
}

// GetComments is a helper method to define mock.On call
//   - ctx context.Context
//   - q spec.CommentQuery[string]
//   - tx ...*sql.Tx
func (_e *MockSecretRepository_Expecter) GetComments(ctx any, q any, tx ...any) *MockSecretRepository_GetComments_Call {
	return &MockSecretRepository_GetComments_Call{Call: _e.mock.On("GetComments",
		append([]any{ctx, q}, tx...)...)}
}

func (_c *MockSecretRepository_GetComments_Call) Run(run func(ctx context.Context, q spec.CommentQuery[string], tx ...*sql.Tx)) *MockSecretRepository_GetComments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.CommentQuery[string]
		if args[1] != nil {
			arg1 = args[1].(spec.CommentQuery[string])
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockSecretRepository_GetComments_Call) Return(commentRows []model.CommentRow, n int, err error) *MockSecretRepository_GetComments_Call {
	_c.Call.Return(commentRows, n, err)
	return _c
}

func (_c *MockSecretRepository_GetComments_Call) RunAndReturn(run func(ctx context.Context, q spec.CommentQuery[string], tx ...*sql.Tx) ([]model.CommentRow, int, error)) *MockSecretRepository_GetComments_Call {
	_c.Call.Return(run)
	return _c
}

// GetFirstSolver provides a mock function for the type MockSecretRepository
func (_mock *MockSecretRepository) GetFirstSolver(ctx context.Context, secretID string, tx ...*sql.Tx) (*model.SecretSolver, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, secretID, tx)
	} else {
		tmpRet = _mock.Called(ctx, secretID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetFirstSolver")
	}

	var r0 *model.SecretSolver
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...*sql.Tx) (*model.SecretSolver, error)); ok {
		return returnFunc(ctx, secretID, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...*sql.Tx) *model.SecretSolver); ok {
		r0 = returnFunc(ctx, secretID, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.SecretSolver)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, secretID, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSecretRepository_GetFirstSolver_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetFirstSolver'
type MockSecretRepository_GetFirstSolver_Call struct {
	*mock.Call
}

// GetFirstSolver is a helper method to define mock.On call
//   - ctx context.Context
//   - secretID string
//   - tx ...*sql.Tx
func (_e *MockSecretRepository_Expecter) GetFirstSolver(ctx any, secretID any, tx ...any) *MockSecretRepository_GetFirstSolver_Call {
	return &MockSecretRepository_GetFirstSolver_Call{Call: _e.mock.On("GetFirstSolver",
		append([]any{ctx, secretID}, tx...)...)}
}

func (_c *MockSecretRepository_GetFirstSolver_Call) Run(run func(ctx context.Context, secretID string, tx ...*sql.Tx)) *MockSecretRepository_GetFirstSolver_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockSecretRepository_GetFirstSolver_Call) Return(secretSolver *model.SecretSolver, err error) *MockSecretRepository_GetFirstSolver_Call {
	_c.Call.Return(secretSolver, err)
	return _c
}

func (_c *MockSecretRepository_GetFirstSolver_Call) RunAndReturn(run func(ctx context.Context, secretID string, tx ...*sql.Tx) (*model.SecretSolver, error)) *MockSecretRepository_GetFirstSolver_Call {
	_c.Call.Return(run)
	return _c
}

// GetPieceCountForUser provides a mock function for the type MockSecretRepository
func (_mock *MockSecretRepository) GetPieceCountForUser(ctx context.Context, s spec.SecretPieceCount, tx ...*sql.Tx) (int, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, s, tx)
	} else {
		tmpRet = _mock.Called(ctx, s)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetPieceCountForUser")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.SecretPieceCount, ...*sql.Tx) (int, error)); ok {
		return returnFunc(ctx, s, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.SecretPieceCount, ...*sql.Tx) int); ok {
		r0 = returnFunc(ctx, s, tx...)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, spec.SecretPieceCount, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, s, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSecretRepository_GetPieceCountForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPieceCountForUser'
type MockSecretRepository_GetPieceCountForUser_Call struct {
	*mock.Call
}

// GetPieceCountForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - s spec.SecretPieceCount
//   - tx ...*sql.Tx
func (_e *MockSecretRepository_Expecter) GetPieceCountForUser(ctx any, s any, tx ...any) *MockSecretRepository_GetPieceCountForUser_Call {
	return &MockSecretRepository_GetPieceCountForUser_Call{Call: _e.mock.On("GetPieceCountForUser",
		append([]any{ctx, s}, tx...)...)}
}

func (_c *MockSecretRepository_GetPieceCountForUser_Call) Run(run func(ctx context.Context, s spec.SecretPieceCount, tx ...*sql.Tx)) *MockSecretRepository_GetPieceCountForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.SecretPieceCount
		if args[1] != nil {
			arg1 = args[1].(spec.SecretPieceCount)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockSecretRepository_GetPieceCountForUser_Call) Return(n int, err error) *MockSecretRepository_GetPieceCountForUser_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockSecretRepository_GetPieceCountForUser_Call) RunAndReturn(run func(ctx context.Context, s spec.SecretPieceCount, tx ...*sql.Tx) (int, error)) *MockSecretRepository_GetPieceCountForUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetProgressLeaderboard provides a mock function for the type MockSecretRepository
func (_mock *MockSecretRepository) GetProgressLeaderboard(ctx context.Context, pieceIDs []string, tx ...*sql.Tx) ([]model.SecretLeaderboardRow, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, pieceIDs, tx)
	} else {
		tmpRet = _mock.Called(ctx, pieceIDs)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetProgressLeaderboard")
	}

	var r0 []model.SecretLeaderboardRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, ...*sql.Tx) ([]model.SecretLeaderboardRow, error)); ok {
		return returnFunc(ctx, pieceIDs, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, ...*sql.Tx) []model.SecretLeaderboardRow); ok {
		r0 = returnFunc(ctx, pieceIDs, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.SecretLeaderboardRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, pieceIDs, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSecretRepository_GetProgressLeaderboard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetProgressLeaderboard'
type MockSecretRepository_GetProgressLeaderboard_Call struct {
	*mock.Call
}

// GetProgressLeaderboard is a helper method to define mock.On call
//   - ctx context.Context
//   - pieceIDs []string
//   - tx ...*sql.Tx
func (_e *MockSecretRepository_Expecter) GetProgressLeaderboard(ctx any, pieceIDs any, tx ...any) *MockSecretRepository_GetProgressLeaderboard_Call {
	return &MockSecretRepository_GetProgressLeaderboard_Call{Call: _e.mock.On("GetProgressLeaderboard",
		append([]any{ctx, pieceIDs}, tx...)...)}
}

func (_c *MockSecretRepository_GetProgressLeaderboard_Call) Run(run func(ctx context.Context, pieceIDs []string, tx ...*sql.Tx)) *MockSecretRepository_GetProgressLeaderboard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockSecretRepository_GetProgressLeaderboard_Call) Return(secretLeaderboardRows []model.SecretLeaderboardRow, err error) *MockSecretRepository_GetProgressLeaderboard_Call {
	_c.Call.Return(secretLeaderboardRows, err)
	return _c
}

func (_c *MockSecretRepository_GetProgressLeaderboard_Call) RunAndReturn(run func(ctx context.Context, pieceIDs []string, tx ...*sql.Tx) ([]model.SecretLeaderboardRow, error)) *MockSecretRepository_GetProgressLeaderboard_Call {
	_c.Call.Return(run)
	return _c
}

// GetSolversLeaderboard provides a mock function for the type MockSecretRepository
func (_mock *MockSecretRepository) GetSolversLeaderboard(ctx context.Context, parentSecretIDs []string, tx ...*sql.Tx) ([]model.SecretSolverRow, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, parentSecretIDs, tx)
	} else {
		tmpRet = _mock.Called(ctx, parentSecretIDs)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetSolversLeaderboard")
	}

	var r0 []model.SecretSolverRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, ...*sql.Tx) ([]model.SecretSolverRow, error)); ok {
		return returnFunc(ctx, parentSecretIDs, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []string, ...*sql.Tx) []model.SecretSolverRow); ok {
		r0 = returnFunc(ctx, parentSecretIDs, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.SecretSolverRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []string, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, parentSecretIDs, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSecretRepository_GetSolversLeaderboard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetSolversLeaderboard'
type MockSecretRepository_GetSolversLeaderboard_Call struct {
	*mock.Call
}

// GetSolversLeaderboard is a helper method to define mock.On call
//   - ctx context.Context
//   - parentSecretIDs []string
//   - tx ...*sql.Tx
func (_e *MockSecretRepository_Expecter) GetSolversLeaderboard(ctx any, parentSecretIDs any, tx ...any) *MockSecretRepository_GetSolversLeaderboard_Call {
	return &MockSecretRepository_GetSolversLeaderboard_Call{Call: _e.mock.On("GetSolversLeaderboard",
		append([]any{ctx, parentSecretIDs}, tx...)...)}
}

func (_c *MockSecretRepository_GetSolversLeaderboard_Call) Run(run func(ctx context.Context, parentSecretIDs []string, tx ...*sql.Tx)) *MockSecretRepository_GetSolversLeaderboard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []string
		if args[1] != nil {
			arg1 = args[1].([]string)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockSecretRepository_GetSolversLeaderboard_Call) Return(secretSolverRows []model.SecretSolverRow, err error) *MockSecretRepository_GetSolversLeaderboard_Call {
	_c.Call.Return(secretSolverRows, err)
	return _c
}

func (_c *MockSecretRepository_GetSolversLeaderboard_Call) RunAndReturn(run func(ctx context.Context, parentSecretIDs []string, tx ...*sql.Tx) ([]model.SecretSolverRow, error)) *MockSecretRepository_GetSolversLeaderboard_Call {
	_c.Call.Return(run)
	return _c
}

// GetUserProgressSummary provides a mock function for the type MockSecretRepository
func (_mock *MockSecretRepository) GetUserProgressSummary(ctx context.Context, s spec.SecretPieceCount, tx ...*sql.Tx) (*model.SecretLeaderboardRow, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, s, tx)
	} else {
		tmpRet = _mock.Called(ctx, s)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetUserProgressSummary")
	}

	var r0 *model.SecretLeaderboardRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.SecretPieceCount, ...*sql.Tx) (*model.SecretLeaderboardRow, error)); ok {
		return returnFunc(ctx, s, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.SecretPieceCount, ...*sql.Tx) *model.SecretLeaderboardRow); ok {
		r0 = returnFunc(ctx, s, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.SecretLeaderboardRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, spec.SecretPieceCount, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, s, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSecretRepository_GetUserProgressSummary_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUserProgressSummary'
type MockSecretRepository_GetUserProgressSummary_Call struct {
	*mock.Call
}

// GetUserProgressSummary is a helper method to define mock.On call
//   - ctx context.Context
//   - s spec.SecretPieceCount
//   - tx ...*sql.Tx
func (_e *MockSecretRepository_Expecter) GetUserProgressSummary(ctx any, s any, tx ...any) *MockSecretRepository_GetUserProgressSummary_Call {
	return &MockSecretRepository_GetUserProgressSummary_Call{Call: _e.mock.On("GetUserProgressSummary",
		append([]any{ctx, s}, tx...)...)}
}

func (_c *MockSecretRepository_GetUserProgressSummary_Call) Run(run func(ctx context.Context, s spec.SecretPieceCount, tx ...*sql.Tx)) *MockSecretRepository_GetUserProgressSummary_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.SecretPieceCount
		if args[1] != nil {
			arg1 = args[1].(spec.SecretPieceCount)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockSecretRepository_GetUserProgressSummary_Call) Return(secretLeaderboardRow *model.SecretLeaderboardRow, err error) *MockSecretRepository_GetUserProgressSummary_Call {
	_c.Call.Return(secretLeaderboardRow, err)
	return _c
}

func (_c *MockSecretRepository_GetUserProgressSummary_Call) RunAndReturn(run func(ctx context.Context, s spec.SecretPieceCount, tx ...*sql.Tx) (*model.SecretLeaderboardRow, error)) *MockSecretRepository_GetUserProgressSummary_Call {
	_c.Call.Return(run)
	return _c
}

// LikeComment provides a mock function for the type MockSecretRepository
func (_mock *MockSecretRepository) LikeComment(ctx context.Context, s spec.CommentLike, tx ...*sql.Tx) error {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, s, tx)
	} else {
		tmpRet = _mock.Called(ctx, s)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for LikeComment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.CommentLike, ...*sql.Tx) error); ok {
		r0 = returnFunc(ctx, s, tx...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSecretRepository_LikeComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LikeComment'
type MockSecretRepository_LikeComment_Call struct {
	*mock.Call
}

// LikeComment is a helper method to define mock.On call
//   - ctx context.Context
//   - s spec.CommentLike
//   - tx ...*sql.Tx
func (_e *MockSecretRepository_Expecter) LikeComment(ctx any, s any, tx ...any) *MockSecretRepository_LikeComment_Call {
	return &MockSecretRepository_LikeComment_Call{Call: _e.mock.On("LikeComment",
		append([]any{ctx, s}, tx...)...)}
}

func (_c *MockSecretRepository_LikeComment_Call) Run(run func(ctx context.Context, s spec.CommentLike, tx ...*sql.Tx)) *MockSecretRepository_LikeComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.CommentLike
		if args[1] != nil {
			arg1 = args[1].(spec.CommentLike)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockSecretRepository_LikeComment_Call) Return(err error) *MockSecretRepository_LikeComment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSecretRepository_LikeComment_Call) RunAndReturn(run func(ctx context.Context, s spec.CommentLike, tx ...*sql.Tx) error) *MockSecretRepository_LikeComment_Call {
	_c.Call.Return(run)
	return _c
}

// UnlikeComment provides a mock function for the type MockSecretRepository
func (_mock *MockSecretRepository) UnlikeComment(ctx context.Context, s spec.CommentLike, tx ...*sql.Tx) error {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, s, tx)
	} else {
		tmpRet = _mock.Called(ctx, s)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UnlikeComment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.CommentLike, ...*sql.Tx) error); ok {
		r0 = returnFunc(ctx, s, tx...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSecretRepository_UnlikeComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnlikeComment'
type MockSecretRepository_UnlikeComment_Call struct {
	*mock.Call
}

// UnlikeComment is a helper method to define mock.On call
//   - ctx context.Context
//   - s spec.CommentLike
//   - tx ...*sql.Tx
func (_e *MockSecretRepository_Expecter) UnlikeComment(ctx any, s any, tx ...any) *MockSecretRepository_UnlikeComment_Call {
	return &MockSecretRepository_UnlikeComment_Call{Call: _e.mock.On("UnlikeComment",
		append([]any{ctx, s}, tx...)...)}
}

func (_c *MockSecretRepository_UnlikeComment_Call) Run(run func(ctx context.Context, s spec.CommentLike, tx ...*sql.Tx)) *MockSecretRepository_UnlikeComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.CommentLike
		if args[1] != nil {
			arg1 = args[1].(spec.CommentLike)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockSecretRepository_UnlikeComment_Call) Return(err error) *MockSecretRepository_UnlikeComment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSecretRepository_UnlikeComment_Call) RunAndReturn(run func(ctx context.Context, s spec.CommentLike, tx ...*sql.Tx) error) *MockSecretRepository_UnlikeComment_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateComment provides a mock function for the type MockSecretRepository
func (_mock *MockSecretRepository) UpdateComment(ctx context.Context, s spec.CommentUpdate, tx ...*sql.Tx) error {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, s, tx)
	} else {
		tmpRet = _mock.Called(ctx, s)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UpdateComment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.CommentUpdate, ...*sql.Tx) error); ok {
		r0 = returnFunc(ctx, s, tx...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSecretRepository_UpdateComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateComment'
type MockSecretRepository_UpdateComment_Call struct {
	*mock.Call
}

// UpdateComment is a helper method to define mock.On call
//   - ctx context.Context
//   - s spec.CommentUpdate
//   - tx ...*sql.Tx
func (_e *MockSecretRepository_Expecter) UpdateComment(ctx any, s any, tx ...any) *MockSecretRepository_UpdateComment_Call {
	return &MockSecretRepository_UpdateComment_Call{Call: _e.mock.On("UpdateComment",
		append([]any{ctx, s}, tx...)...)}
}

func (_c *MockSecretRepository_UpdateComment_Call) Run(run func(ctx context.Context, s spec.CommentUpdate, tx ...*sql.Tx)) *MockSecretRepository_UpdateComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.CommentUpdate
		if args[1] != nil {
			arg1 = args[1].(spec.CommentUpdate)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockSecretRepository_UpdateComment_Call) Return(err error) *MockSecretRepository_UpdateComment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSecretRepository_UpdateComment_Call) RunAndReturn(run func(ctx context.Context, s spec.CommentUpdate, tx ...*sql.Tx) error) *MockSecretRepository_UpdateComment_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCommentBody provides a mock function for the type MockSecretRepository
func (_mock *MockSecretRepository) UpdateCommentBody(ctx context.Context, update spec.CommentUpdate, tx ...*sql.Tx) error {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, update, tx)
	} else {
		tmpRet = _mock.Called(ctx, update)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UpdateCommentBody")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.CommentUpdate, ...*sql.Tx) error); ok {
		r0 = returnFunc(ctx, update, tx...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSecretRepository_UpdateCommentBody_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCommentBody'
type MockSecretRepository_UpdateCommentBody_Call struct {
	*mock.Call
}

// UpdateCommentBody is a helper method to define mock.On call
//   - ctx context.Context
//   - update spec.CommentUpdate
//   - tx ...*sql.Tx
func (_e *MockSecretRepository_Expecter) UpdateCommentBody(ctx any, update any, tx ...any) *MockSecretRepository_UpdateCommentBody_Call {
	return &MockSecretRepository_UpdateCommentBody_Call{Call: _e.mock.On("UpdateCommentBody",
		append([]any{ctx, update}, tx...)...)}
}

func (_c *MockSecretRepository_UpdateCommentBody_Call) Run(run func(ctx context.Context, update spec.CommentUpdate, tx ...*sql.Tx)) *MockSecretRepository_UpdateCommentBody_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.CommentUpdate
		if args[1] != nil {
			arg1 = args[1].(spec.CommentUpdate)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockSecretRepository_UpdateCommentBody_Call) Return(err error) *MockSecretRepository_UpdateCommentBody_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSecretRepository_UpdateCommentBody_Call) RunAndReturn(run func(ctx context.Context, update spec.CommentUpdate, tx ...*sql.Tx) error) *MockSecretRepository_UpdateCommentBody_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCommentMediaThumbnail provides a mock function for the type MockSecretRepository
func (_mock *MockSecretRepository) UpdateCommentMediaThumbnail(ctx context.Context, s spec.MediaURLUpdate, tx ...*sql.Tx) error {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, s, tx)
	} else {
		tmpRet = _mock.Called(ctx, s)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UpdateCommentMediaThumbnail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.MediaURLUpdate, ...*sql.Tx) error); ok {
		r0 = returnFunc(ctx, s, tx...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSecretRepository_UpdateCommentMediaThumbnail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCommentMediaThumbnail'
type MockSecretRepository_UpdateCommentMediaThumbnail_Call struct {
	*mock.Call
}

// UpdateCommentMediaThumbnail is a helper method to define mock.On call
//   - ctx context.Context
//   - s spec.MediaURLUpdate
//   - tx ...*sql.Tx
func (_e *MockSecretRepository_Expecter) UpdateCommentMediaThumbnail(ctx any, s any, tx ...any) *MockSecretRepository_UpdateCommentMediaThumbnail_Call {
	return &MockSecretRepository_UpdateCommentMediaThumbnail_Call{Call: _e.mock.On("UpdateCommentMediaThumbnail",
		append([]any{ctx, s}, tx...)...)}
}

func (_c *MockSecretRepository_UpdateCommentMediaThumbnail_Call) Run(run func(ctx context.Context, s spec.MediaURLUpdate, tx ...*sql.Tx)) *MockSecretRepository_UpdateCommentMediaThumbnail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.MediaURLUpdate
		if args[1] != nil {
			arg1 = args[1].(spec.MediaURLUpdate)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockSecretRepository_UpdateCommentMediaThumbnail_Call) Return(err error) *MockSecretRepository_UpdateCommentMediaThumbnail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSecretRepository_UpdateCommentMediaThumbnail_Call) RunAndReturn(run func(ctx context.Context, s spec.MediaURLUpdate, tx ...*sql.Tx) error) *MockSecretRepository_UpdateCommentMediaThumbnail_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCommentMediaURL provides a mock function for the type MockSecretRepository
func (_mock *MockSecretRepository) UpdateCommentMediaURL(ctx context.Context, s spec.MediaURLUpdate, tx ...*sql.Tx) error {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, s, tx)
	} else {
		tmpRet = _mock.Called(ctx, s)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UpdateCommentMediaURL")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.MediaURLUpdate, ...*sql.Tx) error); ok {
		r0 = returnFunc(ctx, s, tx...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockSecretRepository_UpdateCommentMediaURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCommentMediaURL'
type MockSecretRepository_UpdateCommentMediaURL_Call struct {
	*mock.Call
}

// UpdateCommentMediaURL is a helper method to define mock.On call
//   - ctx context.Context
//   - s spec.MediaURLUpdate
//   - tx ...*sql.Tx
func (_e *MockSecretRepository_Expecter) UpdateCommentMediaURL(ctx any, s any, tx ...any) *MockSecretRepository_UpdateCommentMediaURL_Call {
	return &MockSecretRepository_UpdateCommentMediaURL_Call{Call: _e.mock.On("UpdateCommentMediaURL",
		append([]any{ctx, s}, tx...)...)}
}

func (_c *MockSecretRepository_UpdateCommentMediaURL_Call) Run(run func(ctx context.Context, s spec.MediaURLUpdate, tx ...*sql.Tx)) *MockSecretRepository_UpdateCommentMediaURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.MediaURLUpdate
		if args[1] != nil {
			arg1 = args[1].(spec.MediaURLUpdate)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockSecretRepository_UpdateCommentMediaURL_Call) Return(err error) *MockSecretRepository_UpdateCommentMediaURL_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockSecretRepository_UpdateCommentMediaURL_Call) RunAndReturn(run func(ctx context.Context, s spec.MediaURLUpdate, tx ...*sql.Tx) error) *MockSecretRepository_UpdateCommentMediaURL_Call {
	_c.Call.Return(run)
	return _c
}
