// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"
	"database/sql"
	"umineko_city_of_books/internal/model"
	"umineko_city_of_books/internal/model/spec"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockShipRepository creates a new instance of MockShipRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockShipRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockShipRepository {
	mock := &MockShipRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockShipRepository is an autogenerated mock type for the ShipRepository type
type MockShipRepository struct {
	mock.Mock
}

type MockShipRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockShipRepository) EXPECT() *MockShipRepository_Expecter {
	return &MockShipRepository_Expecter{mock: &_m.Mock}
}

// AddCommentMedia provides a mock function for the type MockShipRepository
func (_mock *MockShipRepository) AddCommentMedia(ctx context.Context, s spec.NewMedia, tx ...*sql.Tx) (int64, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, s, tx)
	} else {
		tmpRet = _mock.Called(ctx, s)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for AddCommentMedia")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.NewMedia, ...*sql.Tx) (int64, error)); ok {
		return returnFunc(ctx, s, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.NewMedia, ...*sql.Tx) int64); ok {
		r0 = returnFunc(ctx, s, tx...)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, spec.NewMedia, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, s, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockShipRepository_AddCommentMedia_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AddCommentMedia'
type MockShipRepository_AddCommentMedia_Call struct {
	*mock.Call
}

// AddCommentMedia is a helper method to define mock.On call
//   - ctx context.Context
//   - s spec.NewMedia
//   - tx ...*sql.Tx
func (_e *MockShipRepository_Expecter) AddCommentMedia(ctx any, s any, tx ...any) *MockShipRepository_AddCommentMedia_Call {
	return &MockShipRepository_AddCommentMedia_Call{Call: _e.mock.On("AddCommentMedia",
		append([]any{ctx, s}, tx...)...)}
}

func (_c *MockShipRepository_AddCommentMedia_Call) Run(run func(ctx context.Context, s spec.NewMedia, tx ...*sql.Tx)) *MockShipRepository_AddCommentMedia_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.NewMedia
		if args[1] != nil {
			arg1 = args[1].(spec.NewMedia)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockShipRepository_AddCommentMedia_Call) Return(n int64, err error) *MockShipRepository_AddCommentMedia_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockShipRepository_AddCommentMedia_Call) RunAndReturn(run func(ctx context.Context, s spec.NewMedia, tx ...*sql.Tx) (int64, error)) *MockShipRepository_AddCommentMedia_Call {
	_c.Call.Return(run)
	return _c
}

// CollectCommentMediaPaths provides a mock function for the type MockShipRepository
func (_mock *MockShipRepository) CollectCommentMediaPaths(ctx context.Context, entityID uuid.UUID, tx ...*sql.Tx) ([]string, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, entityID, tx)
	} else {
		tmpRet = _mock.Called(ctx, entityID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for CollectCommentMediaPaths")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...*sql.Tx) ([]string, error)); ok {
		return returnFunc(ctx, entityID, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...*sql.Tx) []string); ok {
		r0 = returnFunc(ctx, entityID, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, entityID, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockShipRepository_CollectCommentMediaPaths_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CollectCommentMediaPaths'
type MockShipRepository_CollectCommentMediaPaths_Call struct {
	*mock.Call
}

// CollectCommentMediaPaths is a helper method to define mock.On call
//   - ctx context.Context
//   - entityID uuid.UUID
//   - tx ...*sql.Tx
func (_e *MockShipRepository_Expecter) CollectCommentMediaPaths(ctx any, entityID any, tx ...any) *MockShipRepository_CollectCommentMediaPaths_Call {
	return &MockShipRepository_CollectCommentMediaPaths_Call{Call: _e.mock.On("CollectCommentMediaPaths",
		append([]any{ctx, entityID}, tx...)...)}
}

func (_c *MockShipRepository_CollectCommentMediaPaths_Call) Run(run func(ctx context.Context, entityID uuid.UUID, tx ...*sql.Tx)) *MockShipRepository_CollectCommentMediaPaths_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockShipRepository_CollectCommentMediaPaths_Call) Return(strings []string, err error) *MockShipRepository_CollectCommentMediaPaths_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockShipRepository_CollectCommentMediaPaths_Call) RunAndReturn(run func(ctx context.Context, entityID uuid.UUID, tx ...*sql.Tx) ([]string, error)) *MockShipRepository_CollectCommentMediaPaths_Call {
	_c.Call.Return(run)
	return _c
}

// CollectSingleCommentMediaPaths provides a mock function for the type MockShipRepository
func (_mock *MockShipRepository) CollectSingleCommentMediaPaths(ctx context.Context, commentID uuid.UUID, tx ...*sql.Tx) ([]string, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, commentID, tx)
	} else {
		tmpRet = _mock.Called(ctx, commentID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for CollectSingleCommentMediaPaths")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...*sql.Tx) ([]string, error)); ok {
		return returnFunc(ctx, commentID, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...*sql.Tx) []string); ok {
		r0 = returnFunc(ctx, commentID, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, commentID, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockShipRepository_CollectSingleCommentMediaPaths_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CollectSingleCommentMediaPaths'
type MockShipRepository_CollectSingleCommentMediaPaths_Call struct {
	*mock.Call
}

// CollectSingleCommentMediaPaths is a helper method to define mock.On call
//   - ctx context.Context
//   - commentID uuid.UUID
//   - tx ...*sql.Tx
func (_e *MockShipRepository_Expecter) CollectSingleCommentMediaPaths(ctx any, commentID any, tx ...any) *MockShipRepository_CollectSingleCommentMediaPaths_Call {
	return &MockShipRepository_CollectSingleCommentMediaPaths_Call{Call: _e.mock.On("CollectSingleCommentMediaPaths",
		append([]any{ctx, commentID}, tx...)...)}
}

func (_c *MockShipRepository_CollectSingleCommentMediaPaths_Call) Run(run func(ctx context.Context, commentID uuid.UUID, tx ...*sql.Tx)) *MockShipRepository_CollectSingleCommentMediaPaths_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockShipRepository_CollectSingleCommentMediaPaths_Call) Return(strings []string, err error) *MockShipRepository_CollectSingleCommentMediaPaths_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockShipRepository_CollectSingleCommentMediaPaths_Call) RunAndReturn(run func(ctx context.Context, commentID uuid.UUID, tx ...*sql.Tx) ([]string, error)) *MockShipRepository_CollectSingleCommentMediaPaths_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockShipRepository
func (_mock *MockShipRepository) Create(ctx context.Context, s spec.NewShip, tx ...*sql.Tx) (*model.ShipRow, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, s, tx)
	} else {
		tmpRet = _mock.Called(ctx, s)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.ShipRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.NewShip, ...*sql.Tx) (*model.ShipRow, error)); ok {
		return returnFunc(ctx, s, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.NewShip, ...*sql.Tx) *model.ShipRow); ok {
		r0 = returnFunc(ctx, s, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ShipRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, spec.NewShip, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, s, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockShipRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockShipRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - s spec.NewShip
//   - tx ...*sql.Tx
func (_e *MockShipRepository_Expecter) Create(ctx any, s any, tx ...any) *MockShipRepository_Create_Call {
	return &MockShipRepository_Create_Call{Call: _e.mock.On("Create",
		append([]any{ctx, s}, tx...)...)}
}

func (_c *MockShipRepository_Create_Call) Run(run func(ctx context.Context, s spec.NewShip, tx ...*sql.Tx)) *MockShipRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.NewShip
		if args[1] != nil {
			arg1 = args[1].(spec.NewShip)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockShipRepository_Create_Call) Return(shipRow *model.ShipRow, err error) *MockShipRepository_Create_Call {
	_c.Call.Return(shipRow, err)
	return _c
}

func (_c *MockShipRepository_Create_Call) RunAndReturn(run func(ctx context.Context, s spec.NewShip, tx ...*sql.Tx) (*model.ShipRow, error)) *MockShipRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// CreateWithCharacters provides a mock function for the type MockShipRepository
func (_mock *MockShipRepository) CreateWithCharacters(ctx context.Context, s spec.NewShipWithCharacters, tx ...*sql.Tx) (*model.ShipRow, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, s, tx)
	} else {
		tmpRet = _mock.Called(ctx, s)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for CreateWithCharacters")
	}

	var r0 *model.ShipRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.NewShipWithCharacters, ...*sql.Tx) (*model.ShipRow, error)); ok {
		return returnFunc(ctx, s, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.NewShipWithCharacters, ...*sql.Tx) *model.ShipRow); ok {
		r0 = returnFunc(ctx, s, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ShipRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, spec.NewShipWithCharacters, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, s, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockShipRepository_CreateWithCharacters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateWithCharacters'
type MockShipRepository_CreateWithCharacters_Call struct {
	*mock.Call
}

// CreateWithCharacters is a helper method to define mock.On call
//   - ctx context.Context
//   - s spec.NewShipWithCharacters
//   - tx ...*sql.Tx
func (_e *MockShipRepository_Expecter) CreateWithCharacters(ctx any, s any, tx ...any) *MockShipRepository_CreateWithCharacters_Call {
	return &MockShipRepository_CreateWithCharacters_Call{Call: _e.mock.On("CreateWithCharacters",
		append([]any{ctx, s}, tx...)...)}
}

func (_c *MockShipRepository_CreateWithCharacters_Call) Run(run func(ctx context.Context, s spec.NewShipWithCharacters, tx ...*sql.Tx)) *MockShipRepository_CreateWithCharacters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.NewShipWithCharacters
		if args[1] != nil {
			arg1 = args[1].(spec.NewShipWithCharacters)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockShipRepository_CreateWithCharacters_Call) Return(shipRow *model.ShipRow, err error) *MockShipRepository_CreateWithCharacters_Call {
	_c.Call.Return(shipRow, err)
	return _c
}

func (_c *MockShipRepository_CreateWithCharacters_Call) RunAndReturn(run func(ctx context.Context, s spec.NewShipWithCharacters, tx ...*sql.Tx) (*model.ShipRow, error)) *MockShipRepository_CreateWithCharacters_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockShipRepository
func (_mock *MockShipRepository) Delete(ctx context.Context, s spec.OwnedDeletion, tx ...*sql.Tx) error {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, s, tx)
	} else {
		tmpRet = _mock.Called(ctx, s)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.OwnedDeletion, ...*sql.Tx) error); ok {
		r0 = returnFunc(ctx, s, tx...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockShipRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockShipRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - s spec.OwnedDeletion
//   - tx ...*sql.Tx
func (_e *MockShipRepository_Expecter) Delete(ctx any, s any, tx ...any) *MockShipRepository_Delete_Call {
	return &MockShipRepository_Delete_Call{Call: _e.mock.On("Delete",
		append([]any{ctx, s}, tx...)...)}
}

func (_c *MockShipRepository_Delete_Call) Run(run func(ctx context.Context, s spec.OwnedDeletion, tx ...*sql.Tx)) *MockShipRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.OwnedDeletion
		if args[1] != nil {
			arg1 = args[1].(spec.OwnedDeletion)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockShipRepository_Delete_Call) Return(err error) *MockShipRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockShipRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, s spec.OwnedDeletion, tx ...*sql.Tx) error) *MockShipRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteAsAdmin provides a mock function for the type MockShipRepository
func (_mock *MockShipRepository) DeleteAsAdmin(ctx context.Context, id uuid.UUID, tx ...*sql.Tx) error {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, id, tx)
	} else {
		tmpRet = _mock.Called(ctx, id)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DeleteAsAdmin")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...*sql.Tx) error); ok {
		r0 = returnFunc(ctx, id, tx...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockShipRepository_DeleteAsAdmin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteAsAdmin'
type MockShipRepository_DeleteAsAdmin_Call struct {
	*mock.Call
}

// DeleteAsAdmin is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - tx ...*sql.Tx
func (_e *MockShipRepository_Expecter) DeleteAsAdmin(ctx any, id any, tx ...any) *MockShipRepository_DeleteAsAdmin_Call {
	return &MockShipRepository_DeleteAsAdmin_Call{Call: _e.mock.On("DeleteAsAdmin",
		append([]any{ctx, id}, tx...)...)}
}

func (_c *MockShipRepository_DeleteAsAdmin_Call) Run(run func(ctx context.Context, id uuid.UUID, tx ...*sql.Tx)) *MockShipRepository_DeleteAsAdmin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockShipRepository_DeleteAsAdmin_Call) Return(err error) *MockShipRepository_DeleteAsAdmin_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockShipRepository_DeleteAsAdmin_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, tx ...*sql.Tx) error) *MockShipRepository_DeleteAsAdmin_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCharacters provides a mock function for the type MockShipRepository
func (_mock *MockShipRepository) DeleteCharacters(ctx context.Context, shipID uuid.UUID, tx ...*sql.Tx) error {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, shipID, tx)
	} else {
		tmpRet = _mock.Called(ctx, shipID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DeleteCharacters")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...*sql.Tx) error); ok {
		r0 = returnFunc(ctx, shipID, tx...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockShipRepository_DeleteCharacters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCharacters'
type MockShipRepository_DeleteCharacters_Call struct {
	*mock.Call
}

// DeleteCharacters is a helper method to define mock.On call
//   - ctx context.Context
//   - shipID uuid.UUID
//   - tx ...*sql.Tx
func (_e *MockShipRepository_Expecter) DeleteCharacters(ctx any, shipID any, tx ...any) *MockShipRepository_DeleteCharacters_Call {
	return &MockShipRepository_DeleteCharacters_Call{Call: _e.mock.On("DeleteCharacters",
		append([]any{ctx, shipID}, tx...)...)}
}

func (_c *MockShipRepository_DeleteCharacters_Call) Run(run func(ctx context.Context, shipID uuid.UUID, tx ...*sql.Tx)) *MockShipRepository_DeleteCharacters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockShipRepository_DeleteCharacters_Call) Return(err error) *MockShipRepository_DeleteCharacters_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockShipRepository_DeleteCharacters_Call) RunAndReturn(run func(ctx context.Context, shipID uuid.UUID, tx ...*sql.Tx) error) *MockShipRepository_DeleteCharacters_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteComment provides a mock function for the type MockShipRepository
func (_mock *MockShipRepository) DeleteComment(ctx context.Context, s spec.CommentDeletion, tx ...*sql.Tx) error {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, s, tx)
	} else {
		tmpRet = _mock.Called(ctx, s)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DeleteComment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.CommentDeletion, ...*sql.Tx) error); ok {
		r0 = returnFunc(ctx, s, tx...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockShipRepository_DeleteComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteComment'
type MockShipRepository_DeleteComment_Call struct {
	*mock.Call
}

// DeleteComment is a helper method to define mock.On call
//   - ctx context.Context
//   - s spec.CommentDeletion
//   - tx ...*sql.Tx
func (_e *MockShipRepository_Expecter) DeleteComment(ctx any, s any, tx ...any) *MockShipRepository_DeleteComment_Call {
	return &MockShipRepository_DeleteComment_Call{Call: _e.mock.On("DeleteComment",
		append([]any{ctx, s}, tx...)...)}
}

func (_c *MockShipRepository_DeleteComment_Call) Run(run func(ctx context.Context, s spec.CommentDeletion, tx ...*sql.Tx)) *MockShipRepository_DeleteComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.CommentDeletion
		if args[1] != nil {
			arg1 = args[1].(spec.CommentDeletion)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockShipRepository_DeleteComment_Call) Return(err error) *MockShipRepository_DeleteComment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockShipRepository_DeleteComment_Call) RunAndReturn(run func(ctx context.Context, s spec.CommentDeletion, tx ...*sql.Tx) error) *MockShipRepository_DeleteComment_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteCommentWithAudit provides a mock function for the type MockShipRepository
func (_mock *MockShipRepository) DeleteCommentWithAudit(ctx context.Context, deletion spec.CommentDeletion, tx ...*sql.Tx) ([]string, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, deletion, tx)
	} else {
		tmpRet = _mock.Called(ctx, deletion)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DeleteCommentWithAudit")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.CommentDeletion, ...*sql.Tx) ([]string, error)); ok {
		return returnFunc(ctx, deletion, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.CommentDeletion, ...*sql.Tx) []string); ok {
		r0 = returnFunc(ctx, deletion, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, spec.CommentDeletion, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, deletion, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockShipRepository_DeleteCommentWithAudit_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteCommentWithAudit'
type MockShipRepository_DeleteCommentWithAudit_Call struct {
	*mock.Call
}

// DeleteCommentWithAudit is a helper method to define mock.On call
//   - ctx context.Context
//   - deletion spec.CommentDeletion
//   - tx ...*sql.Tx
func (_e *MockShipRepository_Expecter) DeleteCommentWithAudit(ctx any, deletion any, tx ...any) *MockShipRepository_DeleteCommentWithAudit_Call {
	return &MockShipRepository_DeleteCommentWithAudit_Call{Call: _e.mock.On("DeleteCommentWithAudit",
		append([]any{ctx, deletion}, tx...)...)}
}

func (_c *MockShipRepository_DeleteCommentWithAudit_Call) Run(run func(ctx context.Context, deletion spec.CommentDeletion, tx ...*sql.Tx)) *MockShipRepository_DeleteCommentWithAudit_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.CommentDeletion
		if args[1] != nil {
			arg1 = args[1].(spec.CommentDeletion)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockShipRepository_DeleteCommentWithAudit_Call) Return(strings []string, err error) *MockShipRepository_DeleteCommentWithAudit_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockShipRepository_DeleteCommentWithAudit_Call) RunAndReturn(run func(ctx context.Context, deletion spec.CommentDeletion, tx ...*sql.Tx) ([]string, error)) *MockShipRepository_DeleteCommentWithAudit_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteShip provides a mock function for the type MockShipRepository
func (_mock *MockShipRepository) DeleteShip(ctx context.Context, deletion spec.ShipDeletion, tx ...*sql.Tx) ([]string, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, deletion, tx)
	} else {
		tmpRet = _mock.Called(ctx, deletion)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DeleteShip")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.ShipDeletion, ...*sql.Tx) ([]string, error)); ok {
		return returnFunc(ctx, deletion, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.ShipDeletion, ...*sql.Tx) []string); ok {
		r0 = returnFunc(ctx, deletion, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, spec.ShipDeletion, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, deletion, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockShipRepository_DeleteShip_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteShip'
type MockShipRepository_DeleteShip_Call struct {
	*mock.Call
}

// DeleteShip is a helper method to define mock.On call
//   - ctx context.Context
//   - deletion spec.ShipDeletion
//   - tx ...*sql.Tx
func (_e *MockShipRepository_Expecter) DeleteShip(ctx any, deletion any, tx ...any) *MockShipRepository_DeleteShip_Call {
	return &MockShipRepository_DeleteShip_Call{Call: _e.mock.On("DeleteShip",
		append([]any{ctx, deletion}, tx...)...)}
}

func (_c *MockShipRepository_DeleteShip_Call) Run(run func(ctx context.Context, deletion spec.ShipDeletion, tx ...*sql.Tx)) *MockShipRepository_DeleteShip_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.ShipDeletion
		if args[1] != nil {
			arg1 = args[1].(spec.ShipDeletion)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockShipRepository_DeleteShip_Call) Return(strings []string, err error) *MockShipRepository_DeleteShip_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockShipRepository_DeleteShip_Call) RunAndReturn(run func(ctx context.Context, deletion spec.ShipDeletion, tx ...*sql.Tx) ([]string, error)) *MockShipRepository_DeleteShip_Call {
	_c.Call.Return(run)
	return _c
}

// GetAuthorID provides a mock function for the type MockShipRepository
func (_mock *MockShipRepository) GetAuthorID(ctx context.Context, shipID uuid.UUID, tx ...*sql.Tx) (uuid.UUID, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, shipID, tx)
	} else {
		tmpRet = _mock.Called(ctx, shipID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetAuthorID")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...*sql.Tx) (uuid.UUID, error)); ok {
		return returnFunc(ctx, shipID, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...*sql.Tx) uuid.UUID); ok {
		r0 = returnFunc(ctx, shipID, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, shipID, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockShipRepository_GetAuthorID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAuthorID'
type MockShipRepository_GetAuthorID_Call struct {
	*mock.Call
}

// GetAuthorID is a helper method to define mock.On call
//   - ctx context.Context
//   - shipID uuid.UUID
//   - tx ...*sql.Tx
func (_e *MockShipRepository_Expecter) GetAuthorID(ctx any, shipID any, tx ...any) *MockShipRepository_GetAuthorID_Call {
	return &MockShipRepository_GetAuthorID_Call{Call: _e.mock.On("GetAuthorID",
		append([]any{ctx, shipID}, tx...)...)}
}

func (_c *MockShipRepository_GetAuthorID_Call) Run(run func(ctx context.Context, shipID uuid.UUID, tx ...*sql.Tx)) *MockShipRepository_GetAuthorID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockShipRepository_GetAuthorID_Call) Return(uUID uuid.UUID, err error) *MockShipRepository_GetAuthorID_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockShipRepository_GetAuthorID_Call) RunAndReturn(run func(ctx context.Context, shipID uuid.UUID, tx ...*sql.Tx) (uuid.UUID, error)) *MockShipRepository_GetAuthorID_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockShipRepository
func (_mock *MockShipRepository) GetByID(ctx context.Context, q spec.ShipLookup, tx ...*sql.Tx) (*model.ShipRow, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, q, tx)
	} else {
		tmpRet = _mock.Called(ctx, q)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.ShipRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.ShipLookup, ...*sql.Tx) (*model.ShipRow, error)); ok {
		return returnFunc(ctx, q, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.ShipLookup, ...*sql.Tx) *model.ShipRow); ok {
		r0 = returnFunc(ctx, q, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ShipRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, spec.ShipLookup, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, q, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockShipRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockShipRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - q spec.ShipLookup
//   - tx ...*sql.Tx
func (_e *MockShipRepository_Expecter) GetByID(ctx any, q any, tx ...any) *MockShipRepository_GetByID_Call {
	return &MockShipRepository_GetByID_Call{Call: _e.mock.On("GetByID",
		append([]any{ctx, q}, tx...)...)}
}

func (_c *MockShipRepository_GetByID_Call) Run(run func(ctx context.Context, q spec.ShipLookup, tx ...*sql.Tx)) *MockShipRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.ShipLookup
		if args[1] != nil {
			arg1 = args[1].(spec.ShipLookup)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockShipRepository_GetByID_Call) Return(shipRow *model.ShipRow, err error) *MockShipRepository_GetByID_Call {
	_c.Call.Return(shipRow, err)
	return _c
}

func (_c *MockShipRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, q spec.ShipLookup, tx ...*sql.Tx) (*model.ShipRow, error)) *MockShipRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCharacters provides a mock function for the type MockShipRepository
func (_mock *MockShipRepository) GetCharacters(ctx context.Context, shipID uuid.UUID, tx ...*sql.Tx) ([]model.ShipCharacterRow, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, shipID, tx)
	} else {
		tmpRet = _mock.Called(ctx, shipID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetCharacters")
	}

	var r0 []model.ShipCharacterRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...*sql.Tx) ([]model.ShipCharacterRow, error)); ok {
		return returnFunc(ctx, shipID, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...*sql.Tx) []model.ShipCharacterRow); ok {
		r0 = returnFunc(ctx, shipID, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ShipCharacterRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, shipID, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockShipRepository_GetCharacters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCharacters'
type MockShipRepository_GetCharacters_Call struct {
	*mock.Call
}

// GetCharacters is a helper method to define mock.On call
//   - ctx context.Context
//   - shipID uuid.UUID
//   - tx ...*sql.Tx
func (_e *MockShipRepository_Expecter) GetCharacters(ctx any, shipID any, tx ...any) *MockShipRepository_GetCharacters_Call {
	return &MockShipRepository_GetCharacters_Call{Call: _e.mock.On("GetCharacters",
		append([]any{ctx, shipID}, tx...)...)}
}

func (_c *MockShipRepository_GetCharacters_Call) Run(run func(ctx context.Context, shipID uuid.UUID, tx ...*sql.Tx)) *MockShipRepository_GetCharacters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockShipRepository_GetCharacters_Call) Return(shipCharacterRows []model.ShipCharacterRow, err error) *MockShipRepository_GetCharacters_Call {
	_c.Call.Return(shipCharacterRows, err)
	return _c
}

func (_c *MockShipRepository_GetCharacters_Call) RunAndReturn(run func(ctx context.Context, shipID uuid.UUID, tx ...*sql.Tx) ([]model.ShipCharacterRow, error)) *MockShipRepository_GetCharacters_Call {
	_c.Call.Return(run)
	return _c
}

// GetCharactersBatch provides a mock function for the type MockShipRepository
func (_mock *MockShipRepository) GetCharactersBatch(ctx context.Context, shipIDs []uuid.UUID, tx ...*sql.Tx) (map[uuid.UUID][]model.ShipCharacterRow, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, shipIDs, tx)
	} else {
		tmpRet = _mock.Called(ctx, shipIDs)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetCharactersBatch")
	}

	var r0 map[uuid.UUID][]model.ShipCharacterRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID, ...*sql.Tx) (map[uuid.UUID][]model.ShipCharacterRow, error)); ok {
		return returnFunc(ctx, shipIDs, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID, ...*sql.Tx) map[uuid.UUID][]model.ShipCharacterRow); ok {
		r0 = returnFunc(ctx, shipIDs, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[uuid.UUID][]model.ShipCharacterRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []uuid.UUID, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, shipIDs, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockShipRepository_GetCharactersBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCharactersBatch'
type MockShipRepository_GetCharactersBatch_Call struct {
	*mock.Call
}

// GetCharactersBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - shipIDs []uuid.UUID
//   - tx ...*sql.Tx
func (_e *MockShipRepository_Expecter) GetCharactersBatch(ctx any, shipIDs any, tx ...any) *MockShipRepository_GetCharactersBatch_Call {
	return &MockShipRepository_GetCharactersBatch_Call{Call: _e.mock.On("GetCharactersBatch",
		append([]any{ctx, shipIDs}, tx...)...)}
}

func (_c *MockShipRepository_GetCharactersBatch_Call) Run(run func(ctx context.Context, shipIDs []uuid.UUID, tx ...*sql.Tx)) *MockShipRepository_GetCharactersBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockShipRepository_GetCharactersBatch_Call) Return(uUIDToShipCharacterRows map[uuid.UUID][]model.ShipCharacterRow, err error) *MockShipRepository_GetCharactersBatch_Call {
	_c.Call.Return(uUIDToShipCharacterRows, err)
	return _c
}

func (_c *MockShipRepository_GetCharactersBatch_Call) RunAndReturn(run func(ctx context.Context, shipIDs []uuid.UUID, tx ...*sql.Tx) (map[uuid.UUID][]model.ShipCharacterRow, error)) *MockShipRepository_GetCharactersBatch_Call {
	_c.Call.Return(run)
	return _c
}

// GetCommentAuthorID provides a mock function for the type MockShipRepository
func (_mock *MockShipRepository) GetCommentAuthorID(ctx context.Context, commentID uuid.UUID, tx ...*sql.Tx) (uuid.UUID, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, commentID, tx)
	} else {
		tmpRet = _mock.Called(ctx, commentID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetCommentAuthorID")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...*sql.Tx) (uuid.UUID, error)); ok {
		return returnFunc(ctx, commentID, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...*sql.Tx) uuid.UUID); ok {
		r0 = returnFunc(ctx, commentID, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, commentID, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockShipRepository_GetCommentAuthorID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCommentAuthorID'
type MockShipRepository_GetCommentAuthorID_Call struct {
	*mock.Call
}

// GetCommentAuthorID is a helper method to define mock.On call
//   - ctx context.Context
//   - commentID uuid.UUID
//   - tx ...*sql.Tx
func (_e *MockShipRepository_Expecter) GetCommentAuthorID(ctx any, commentID any, tx ...any) *MockShipRepository_GetCommentAuthorID_Call {
	return &MockShipRepository_GetCommentAuthorID_Call{Call: _e.mock.On("GetCommentAuthorID",
		append([]any{ctx, commentID}, tx...)...)}
}

func (_c *MockShipRepository_GetCommentAuthorID_Call) Run(run func(ctx context.Context, commentID uuid.UUID, tx ...*sql.Tx)) *MockShipRepository_GetCommentAuthorID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockShipRepository_GetCommentAuthorID_Call) Return(uUID uuid.UUID, err error) *MockShipRepository_GetCommentAuthorID_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockShipRepository_GetCommentAuthorID_Call) RunAndReturn(run func(ctx context.Context, commentID uuid.UUID, tx ...*sql.Tx) (uuid.UUID, error)) *MockShipRepository_GetCommentAuthorID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCommentEntityID provides a mock function for the type MockShipRepository
func (_mock *MockShipRepository) GetCommentEntityID(ctx context.Context, commentID uuid.UUID, tx ...*sql.Tx) (uuid.UUID, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, commentID, tx)
	} else {
		tmpRet = _mock.Called(ctx, commentID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetCommentEntityID")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...*sql.Tx) (uuid.UUID, error)); ok {
		return returnFunc(ctx, commentID, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...*sql.Tx) uuid.UUID); ok {
		r0 = returnFunc(ctx, commentID, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, commentID, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockShipRepository_GetCommentEntityID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCommentEntityID'
type MockShipRepository_GetCommentEntityID_Call struct {
	*mock.Call
}

// GetCommentEntityID is a helper method to define mock.On call
//   - ctx context.Context
//   - commentID uuid.UUID
//   - tx ...*sql.Tx
func (_e *MockShipRepository_Expecter) GetCommentEntityID(ctx any, commentID any, tx ...any) *MockShipRepository_GetCommentEntityID_Call {
	return &MockShipRepository_GetCommentEntityID_Call{Call: _e.mock.On("GetCommentEntityID",
		append([]any{ctx, commentID}, tx...)...)}
}

func (_c *MockShipRepository_GetCommentEntityID_Call) Run(run func(ctx context.Context, commentID uuid.UUID, tx ...*sql.Tx)) *MockShipRepository_GetCommentEntityID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockShipRepository_GetCommentEntityID_Call) Return(uUID uuid.UUID, err error) *MockShipRepository_GetCommentEntityID_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockShipRepository_GetCommentEntityID_Call) RunAndReturn(run func(ctx context.Context, commentID uuid.UUID, tx ...*sql.Tx) (uuid.UUID, error)) *MockShipRepository_GetCommentEntityID_Call {
	_c.Call.Return(run)
	return _c
}

// GetCommentMedia provides a mock function for the type MockShipRepository
func (_mock *MockShipRepository) GetCommentMedia(ctx context.Context, commentID uuid.UUID, tx ...*sql.Tx) ([]model.PostMediaRow, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, commentID, tx)
	} else {
		tmpRet = _mock.Called(ctx, commentID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetCommentMedia")
	}

	var r0 []model.PostMediaRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...*sql.Tx) ([]model.PostMediaRow, error)); ok {
		return returnFunc(ctx, commentID, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...*sql.Tx) []model.PostMediaRow); ok {
		r0 = returnFunc(ctx, commentID, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.PostMediaRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, commentID, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockShipRepository_GetCommentMedia_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCommentMedia'
type MockShipRepository_GetCommentMedia_Call struct {
	*mock.Call
}

// GetCommentMedia is a helper method to define mock.On call
//   - ctx context.Context
//   - commentID uuid.UUID
//   - tx ...*sql.Tx
func (_e *MockShipRepository_Expecter) GetCommentMedia(ctx any, commentID any, tx ...any) *MockShipRepository_GetCommentMedia_Call {
	return &MockShipRepository_GetCommentMedia_Call{Call: _e.mock.On("GetCommentMedia",
		append([]any{ctx, commentID}, tx...)...)}
}

func (_c *MockShipRepository_GetCommentMedia_Call) Run(run func(ctx context.Context, commentID uuid.UUID, tx ...*sql.Tx)) *MockShipRepository_GetCommentMedia_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockShipRepository_GetCommentMedia_Call) Return(postMediaRows []model.PostMediaRow, err error) *MockShipRepository_GetCommentMedia_Call {
	_c.Call.Return(postMediaRows, err)
	return _c
}

func (_c *MockShipRepository_GetCommentMedia_Call) RunAndReturn(run func(ctx context.Context, commentID uuid.UUID, tx ...*sql.Tx) ([]model.PostMediaRow, error)) *MockShipRepository_GetCommentMedia_Call {
	_c.Call.Return(run)
	return _c
}

// GetCommentMediaBatch provides a mock function for the type MockShipRepository
func (_mock *MockShipRepository) GetCommentMediaBatch(ctx context.Context, commentIDs []uuid.UUID, tx ...*sql.Tx) (map[uuid.UUID][]model.PostMediaRow, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, commentIDs, tx)
	} else {
		tmpRet = _mock.Called(ctx, commentIDs)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetCommentMediaBatch")
	}

	var r0 map[uuid.UUID][]model.PostMediaRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID, ...*sql.Tx) (map[uuid.UUID][]model.PostMediaRow, error)); ok {
		return returnFunc(ctx, commentIDs, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID, ...*sql.Tx) map[uuid.UUID][]model.PostMediaRow); ok {
		r0 = returnFunc(ctx, commentIDs, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[uuid.UUID][]model.PostMediaRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []uuid.UUID, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, commentIDs, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockShipRepository_GetCommentMediaBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetCommentMediaBatch'
type MockShipRepository_GetCommentMediaBatch_Call struct {
	*mock.Call
}

// GetCommentMediaBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - commentIDs []uuid.UUID
//   - tx ...*sql.Tx
func (_e *MockShipRepository_Expecter) GetCommentMediaBatch(ctx any, commentIDs any, tx ...any) *MockShipRepository_GetCommentMediaBatch_Call {
	return &MockShipRepository_GetCommentMediaBatch_Call{Call: _e.mock.On("GetCommentMediaBatch",
		append([]any{ctx, commentIDs}, tx...)...)}
}

func (_c *MockShipRepository_GetCommentMediaBatch_Call) Run(run func(ctx context.Context, commentIDs []uuid.UUID, tx ...*sql.Tx)) *MockShipRepository_GetCommentMediaBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockShipRepository_GetCommentMediaBatch_Call) Return(uUIDToPostMediaRows map[uuid.UUID][]model.PostMediaRow, err error) *MockShipRepository_GetCommentMediaBatch_Call {
	_c.Call.Return(uUIDToPostMediaRows, err)
	return _c
}

func (_c *MockShipRepository_GetCommentMediaBatch_Call) RunAndReturn(run func(ctx context.Context, commentIDs []uuid.UUID, tx ...*sql.Tx) (map[uuid.UUID][]model.PostMediaRow, error)) *MockShipRepository_GetCommentMediaBatch_Call {
	_c.Call.Return(run)
	return _c
}

// GetComments provides a mock function for the type MockShipRepository
func (_mock *MockShipRepository) GetComments(ctx context.Context, q spec.CommentQuery[uuid.UUID], tx ...*sql.Tx) ([]model.CommentRow, int, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, q, tx)
	} else {
		tmpRet = _mock.Called(ctx, q)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetComments")
	}

	var r0 []model.CommentRow
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.CommentQuery[uuid.UUID], ...*sql.Tx) ([]model.CommentRow, int, error)); ok {
		return returnFunc(ctx, q, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.CommentQuery[uuid.UUID], ...*sql.Tx) []model.CommentRow); ok {
		r0 = returnFunc(ctx, q, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.CommentRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, spec.CommentQuery[uuid.UUID], ...*sql.Tx) int); ok {
		r1 = returnFunc(ctx, q, tx...)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, spec.CommentQuery[uuid.UUID], ...*sql.Tx) error); ok {
		r2 = returnFunc(ctx, q, tx...)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockShipRepository_GetComments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetComments'
type MockShipRepository_GetComments_Call struct {
	*mock.Call
}

// GetComments is a helper method to define mock.On call
//   - ctx context.Context
//   - q spec.CommentQuery[uuid.UUID]
//   - tx ...*sql.Tx
func (_e *MockShipRepository_Expecter) GetComments(ctx any, q any, tx ...any) *MockShipRepository_GetComments_Call {
	return &MockShipRepository_GetComments_Call{Call: _e.mock.On("GetComments",
		append([]any{ctx, q}, tx...)...)}
}

func (_c *MockShipRepository_GetComments_Call) Run(run func(ctx context.Context, q spec.CommentQuery[uuid.UUID], tx ...*sql.Tx)) *MockShipRepository_GetComments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.CommentQuery[uuid.UUID]
		if args[1] != nil {
			arg1 = args[1].(spec.CommentQuery[uuid.UUID])
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockShipRepository_GetComments_Call) Return(commentRows []model.CommentRow, n int, err error) *MockShipRepository_GetComments_Call {
	_c.Call.Return(commentRows, n, err)
	return _c
}

func (_c *MockShipRepository_GetComments_Call) RunAndReturn(run func(ctx context.Context, q spec.CommentQuery[uuid.UUID], tx ...*sql.Tx) ([]model.CommentRow, int, error)) *MockShipRepository_GetComments_Call {
	_c.Call.Return(run)
	return _c
}

// GetImagePaths provides a mock function for the type MockShipRepository
func (_mock *MockShipRepository) GetImagePaths(ctx context.Context, shipID uuid.UUID, tx ...*sql.Tx) ([]string, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, shipID, tx)
	} else {
		tmpRet = _mock.Called(ctx, shipID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetImagePaths")
	}

	var r0 []string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...*sql.Tx) ([]string, error)); ok {
		return returnFunc(ctx, shipID, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...*sql.Tx) []string); ok {
		r0 = returnFunc(ctx, shipID, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, shipID, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockShipRepository_GetImagePaths_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetImagePaths'
type MockShipRepository_GetImagePaths_Call struct {
	*mock.Call
}

// GetImagePaths is a helper method to define mock.On call
//   - ctx context.Context
//   - shipID uuid.UUID
//   - tx ...*sql.Tx
func (_e *MockShipRepository_Expecter) GetImagePaths(ctx any, shipID any, tx ...any) *MockShipRepository_GetImagePaths_Call {
	return &MockShipRepository_GetImagePaths_Call{Call: _e.mock.On("GetImagePaths",
		append([]any{ctx, shipID}, tx...)...)}
}

func (_c *MockShipRepository_GetImagePaths_Call) Run(run func(ctx context.Context, shipID uuid.UUID, tx ...*sql.Tx)) *MockShipRepository_GetImagePaths_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockShipRepository_GetImagePaths_Call) Return(strings []string, err error) *MockShipRepository_GetImagePaths_Call {
	_c.Call.Return(strings, err)
	return _c
}

func (_c *MockShipRepository_GetImagePaths_Call) RunAndReturn(run func(ctx context.Context, shipID uuid.UUID, tx ...*sql.Tx) ([]string, error)) *MockShipRepository_GetImagePaths_Call {
	_c.Call.Return(run)
	return _c
}

// InsertCharacters provides a mock function for the type MockShipRepository
func (_mock *MockShipRepository) InsertCharacters(ctx context.Context, s spec.NewShipCharacters, tx ...*sql.Tx) error {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, s, tx)
	} else {
		tmpRet = _mock.Called(ctx, s)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for InsertCharacters")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.NewShipCharacters, ...*sql.Tx) error); ok {
		r0 = returnFunc(ctx, s, tx...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockShipRepository_InsertCharacters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'InsertCharacters'
type MockShipRepository_InsertCharacters_Call struct {
	*mock.Call
}

// InsertCharacters is a helper method to define mock.On call
//   - ctx context.Context
//   - s spec.NewShipCharacters
//   - tx ...*sql.Tx
func (_e *MockShipRepository_Expecter) InsertCharacters(ctx any, s any, tx ...any) *MockShipRepository_InsertCharacters_Call {
	return &MockShipRepository_InsertCharacters_Call{Call: _e.mock.On("InsertCharacters",
		append([]any{ctx, s}, tx...)...)}
}

func (_c *MockShipRepository_InsertCharacters_Call) Run(run func(ctx context.Context, s spec.NewShipCharacters, tx ...*sql.Tx)) *MockShipRepository_InsertCharacters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.NewShipCharacters
		if args[1] != nil {
			arg1 = args[1].(spec.NewShipCharacters)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockShipRepository_InsertCharacters_Call) Return(err error) *MockShipRepository_InsertCharacters_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockShipRepository_InsertCharacters_Call) RunAndReturn(run func(ctx context.Context, s spec.NewShipCharacters, tx ...*sql.Tx) error) *MockShipRepository_InsertCharacters_Call {
	_c.Call.Return(run)
	return _c
}

// LikeComment provides a mock function for the type MockShipRepository
func (_mock *MockShipRepository) LikeComment(ctx context.Context, s spec.CommentLike, tx ...*sql.Tx) error {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, s, tx)
	} else {
		tmpRet = _mock.Called(ctx, s)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for LikeComment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.CommentLike, ...*sql.Tx) error); ok {
		r0 = returnFunc(ctx, s, tx...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockShipRepository_LikeComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LikeComment'
type MockShipRepository_LikeComment_Call struct {
	*mock.Call
}

// LikeComment is a helper method to define mock.On call
//   - ctx context.Context
//   - s spec.CommentLike
//   - tx ...*sql.Tx
func (_e *MockShipRepository_Expecter) LikeComment(ctx any, s any, tx ...any) *MockShipRepository_LikeComment_Call {
	return &MockShipRepository_LikeComment_Call{Call: _e.mock.On("LikeComment",
		append([]any{ctx, s}, tx...)...)}
}

func (_c *MockShipRepository_LikeComment_Call) Run(run func(ctx context.Context, s spec.CommentLike, tx ...*sql.Tx)) *MockShipRepository_LikeComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.CommentLike
		if args[1] != nil {
			arg1 = args[1].(spec.CommentLike)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockShipRepository_LikeComment_Call) Return(err error) *MockShipRepository_LikeComment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockShipRepository_LikeComment_Call) RunAndReturn(run func(ctx context.Context, s spec.CommentLike, tx ...*sql.Tx) error) *MockShipRepository_LikeComment_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockShipRepository
func (_mock *MockShipRepository) List(ctx context.Context, q spec.ShipListing, tx ...*sql.Tx) ([]model.ShipRow, int, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, q, tx)
	} else {
		tmpRet = _mock.Called(ctx, q)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.ShipRow
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.ShipListing, ...*sql.Tx) ([]model.ShipRow, int, error)); ok {
		return returnFunc(ctx, q, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.ShipListing, ...*sql.Tx) []model.ShipRow); ok {
		r0 = returnFunc(ctx, q, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ShipRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, spec.ShipListing, ...*sql.Tx) int); ok {
		r1 = returnFunc(ctx, q, tx...)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, spec.ShipListing, ...*sql.Tx) error); ok {
		r2 = returnFunc(ctx, q, tx...)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockShipRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockShipRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - q spec.ShipListing
//   - tx ...*sql.Tx
func (_e *MockShipRepository_Expecter) List(ctx any, q any, tx ...any) *MockShipRepository_List_Call {
	return &MockShipRepository_List_Call{Call: _e.mock.On("List",
		append([]any{ctx, q}, tx...)...)}
}

func (_c *MockShipRepository_List_Call) Run(run func(ctx context.Context, q spec.ShipListing, tx ...*sql.Tx)) *MockShipRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.ShipListing
		if args[1] != nil {
			arg1 = args[1].(spec.ShipListing)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockShipRepository_List_Call) Return(shipRows []model.ShipRow, n int, err error) *MockShipRepository_List_Call {
	_c.Call.Return(shipRows, n, err)
	return _c
}

func (_c *MockShipRepository_List_Call) RunAndReturn(run func(ctx context.Context, q spec.ShipListing, tx ...*sql.Tx) ([]model.ShipRow, int, error)) *MockShipRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUser provides a mock function for the type MockShipRepository
func (_mock *MockShipRepository) ListByUser(ctx context.Context, q spec.ShipUserListing, tx ...*sql.Tx) ([]model.ShipRow, int, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, q, tx)
	} else {
		tmpRet = _mock.Called(ctx, q)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListByUser")
	}

	var r0 []model.ShipRow
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.ShipUserListing, ...*sql.Tx) ([]model.ShipRow, int, error)); ok {
		return returnFunc(ctx, q, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.ShipUserListing, ...*sql.Tx) []model.ShipRow); ok {
		r0 = returnFunc(ctx, q, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ShipRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, spec.ShipUserListing, ...*sql.Tx) int); ok {
		r1 = returnFunc(ctx, q, tx...)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, spec.ShipUserListing, ...*sql.Tx) error); ok {
		r2 = returnFunc(ctx, q, tx...)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockShipRepository_ListByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUser'
type MockShipRepository_ListByUser_Call struct {
	*mock.Call
}

// ListByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - q spec.ShipUserListing
//   - tx ...*sql.Tx
func (_e *MockShipRepository_Expecter) ListByUser(ctx any, q any, tx ...any) *MockShipRepository_ListByUser_Call {
	return &MockShipRepository_ListByUser_Call{Call: _e.mock.On("ListByUser",
		append([]any{ctx, q}, tx...)...)}
}

func (_c *MockShipRepository_ListByUser_Call) Run(run func(ctx context.Context, q spec.ShipUserListing, tx ...*sql.Tx)) *MockShipRepository_ListByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.ShipUserListing
		if args[1] != nil {
			arg1 = args[1].(spec.ShipUserListing)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockShipRepository_ListByUser_Call) Return(shipRows []model.ShipRow, n int, err error) *MockShipRepository_ListByUser_Call {
	_c.Call.Return(shipRows, n, err)
	return _c
}

func (_c *MockShipRepository_ListByUser_Call) RunAndReturn(run func(ctx context.Context, q spec.ShipUserListing, tx ...*sql.Tx) ([]model.ShipRow, int, error)) *MockShipRepository_ListByUser_Call {
	_c.Call.Return(run)
	return _c
}

// UnlikeComment provides a mock function for the type MockShipRepository
func (_mock *MockShipRepository) UnlikeComment(ctx context.Context, s spec.CommentLike, tx ...*sql.Tx) error {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, s, tx)
	} else {
		tmpRet = _mock.Called(ctx, s)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UnlikeComment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.CommentLike, ...*sql.Tx) error); ok {
		r0 = returnFunc(ctx, s, tx...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockShipRepository_UnlikeComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnlikeComment'
type MockShipRepository_UnlikeComment_Call struct {
	*mock.Call
}

// UnlikeComment is a helper method to define mock.On call
//   - ctx context.Context
//   - s spec.CommentLike
//   - tx ...*sql.Tx
func (_e *MockShipRepository_Expecter) UnlikeComment(ctx any, s any, tx ...any) *MockShipRepository_UnlikeComment_Call {
	return &MockShipRepository_UnlikeComment_Call{Call: _e.mock.On("UnlikeComment",
		append([]any{ctx, s}, tx...)...)}
}

func (_c *MockShipRepository_UnlikeComment_Call) Run(run func(ctx context.Context, s spec.CommentLike, tx ...*sql.Tx)) *MockShipRepository_UnlikeComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.CommentLike
		if args[1] != nil {
			arg1 = args[1].(spec.CommentLike)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockShipRepository_UnlikeComment_Call) Return(err error) *MockShipRepository_UnlikeComment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockShipRepository_UnlikeComment_Call) RunAndReturn(run func(ctx context.Context, s spec.CommentLike, tx ...*sql.Tx) error) *MockShipRepository_UnlikeComment_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateComment provides a mock function for the type MockShipRepository
func (_mock *MockShipRepository) UpdateComment(ctx context.Context, s spec.CommentUpdate, tx ...*sql.Tx) error {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, s, tx)
	} else {
		tmpRet = _mock.Called(ctx, s)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UpdateComment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.CommentUpdate, ...*sql.Tx) error); ok {
		r0 = returnFunc(ctx, s, tx...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockShipRepository_UpdateComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateComment'
type MockShipRepository_UpdateComment_Call struct {
	*mock.Call
}

// UpdateComment is a helper method to define mock.On call
//   - ctx context.Context
//   - s spec.CommentUpdate
//   - tx ...*sql.Tx
func (_e *MockShipRepository_Expecter) UpdateComment(ctx any, s any, tx ...any) *MockShipRepository_UpdateComment_Call {
	return &MockShipRepository_UpdateComment_Call{Call: _e.mock.On("UpdateComment",
		append([]any{ctx, s}, tx...)...)}
}

func (_c *MockShipRepository_UpdateComment_Call) Run(run func(ctx context.Context, s spec.CommentUpdate, tx ...*sql.Tx)) *MockShipRepository_UpdateComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.CommentUpdate
		if args[1] != nil {
			arg1 = args[1].(spec.CommentUpdate)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockShipRepository_UpdateComment_Call) Return(err error) *MockShipRepository_UpdateComment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockShipRepository_UpdateComment_Call) RunAndReturn(run func(ctx context.Context, s spec.CommentUpdate, tx ...*sql.Tx) error) *MockShipRepository_UpdateComment_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCommentBody provides a mock function for the type MockShipRepository
func (_mock *MockShipRepository) UpdateCommentBody(ctx context.Context, update spec.CommentUpdate, tx ...*sql.Tx) error {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, update, tx)
	} else {
		tmpRet = _mock.Called(ctx, update)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UpdateCommentBody")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.CommentUpdate, ...*sql.Tx) error); ok {
		r0 = returnFunc(ctx, update, tx...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockShipRepository_UpdateCommentBody_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCommentBody'
type MockShipRepository_UpdateCommentBody_Call struct {
	*mock.Call
}

// UpdateCommentBody is a helper method to define mock.On call
//   - ctx context.Context
//   - update spec.CommentUpdate
//   - tx ...*sql.Tx
func (_e *MockShipRepository_Expecter) UpdateCommentBody(ctx any, update any, tx ...any) *MockShipRepository_UpdateCommentBody_Call {
	return &MockShipRepository_UpdateCommentBody_Call{Call: _e.mock.On("UpdateCommentBody",
		append([]any{ctx, update}, tx...)...)}
}

func (_c *MockShipRepository_UpdateCommentBody_Call) Run(run func(ctx context.Context, update spec.CommentUpdate, tx ...*sql.Tx)) *MockShipRepository_UpdateCommentBody_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.CommentUpdate
		if args[1] != nil {
			arg1 = args[1].(spec.CommentUpdate)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockShipRepository_UpdateCommentBody_Call) Return(err error) *MockShipRepository_UpdateCommentBody_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockShipRepository_UpdateCommentBody_Call) RunAndReturn(run func(ctx context.Context, update spec.CommentUpdate, tx ...*sql.Tx) error) *MockShipRepository_UpdateCommentBody_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCommentMediaThumbnail provides a mock function for the type MockShipRepository
func (_mock *MockShipRepository) UpdateCommentMediaThumbnail(ctx context.Context, s spec.MediaURLUpdate, tx ...*sql.Tx) error {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, s, tx)
	} else {
		tmpRet = _mock.Called(ctx, s)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UpdateCommentMediaThumbnail")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.MediaURLUpdate, ...*sql.Tx) error); ok {
		r0 = returnFunc(ctx, s, tx...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockShipRepository_UpdateCommentMediaThumbnail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCommentMediaThumbnail'
type MockShipRepository_UpdateCommentMediaThumbnail_Call struct {
	*mock.Call
}

// UpdateCommentMediaThumbnail is a helper method to define mock.On call
//   - ctx context.Context
//   - s spec.MediaURLUpdate
//   - tx ...*sql.Tx
func (_e *MockShipRepository_Expecter) UpdateCommentMediaThumbnail(ctx any, s any, tx ...any) *MockShipRepository_UpdateCommentMediaThumbnail_Call {
	return &MockShipRepository_UpdateCommentMediaThumbnail_Call{Call: _e.mock.On("UpdateCommentMediaThumbnail",
		append([]any{ctx, s}, tx...)...)}
}

func (_c *MockShipRepository_UpdateCommentMediaThumbnail_Call) Run(run func(ctx context.Context, s spec.MediaURLUpdate, tx ...*sql.Tx)) *MockShipRepository_UpdateCommentMediaThumbnail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.MediaURLUpdate
		if args[1] != nil {
			arg1 = args[1].(spec.MediaURLUpdate)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockShipRepository_UpdateCommentMediaThumbnail_Call) Return(err error) *MockShipRepository_UpdateCommentMediaThumbnail_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockShipRepository_UpdateCommentMediaThumbnail_Call) RunAndReturn(run func(ctx context.Context, s spec.MediaURLUpdate, tx ...*sql.Tx) error) *MockShipRepository_UpdateCommentMediaThumbnail_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateCommentMediaURL provides a mock function for the type MockShipRepository
func (_mock *MockShipRepository) UpdateCommentMediaURL(ctx context.Context, s spec.MediaURLUpdate, tx ...*sql.Tx) error {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, s, tx)
	} else {
		tmpRet = _mock.Called(ctx, s)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UpdateCommentMediaURL")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.MediaURLUpdate, ...*sql.Tx) error); ok {
		r0 = returnFunc(ctx, s, tx...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockShipRepository_UpdateCommentMediaURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateCommentMediaURL'
type MockShipRepository_UpdateCommentMediaURL_Call struct {
	*mock.Call
}

// UpdateCommentMediaURL is a helper method to define mock.On call
//   - ctx context.Context
//   - s spec.MediaURLUpdate
//   - tx ...*sql.Tx
func (_e *MockShipRepository_Expecter) UpdateCommentMediaURL(ctx any, s any, tx ...any) *MockShipRepository_UpdateCommentMediaURL_Call {
	return &MockShipRepository_UpdateCommentMediaURL_Call{Call: _e.mock.On("UpdateCommentMediaURL",
		append([]any{ctx, s}, tx...)...)}
}

func (_c *MockShipRepository_UpdateCommentMediaURL_Call) Run(run func(ctx context.Context, s spec.MediaURLUpdate, tx ...*sql.Tx)) *MockShipRepository_UpdateCommentMediaURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.MediaURLUpdate
		if args[1] != nil {
			arg1 = args[1].(spec.MediaURLUpdate)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockShipRepository_UpdateCommentMediaURL_Call) Return(err error) *MockShipRepository_UpdateCommentMediaURL_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockShipRepository_UpdateCommentMediaURL_Call) RunAndReturn(run func(ctx context.Context, s spec.MediaURLUpdate, tx ...*sql.Tx) error) *MockShipRepository_UpdateCommentMediaURL_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateDetails provides a mock function for the type MockShipRepository
func (_mock *MockShipRepository) UpdateDetails(ctx context.Context, s spec.ShipDetailsUpdate, tx ...*sql.Tx) error {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, s, tx)
	} else {
		tmpRet = _mock.Called(ctx, s)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UpdateDetails")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.ShipDetailsUpdate, ...*sql.Tx) error); ok {
		r0 = returnFunc(ctx, s, tx...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockShipRepository_UpdateDetails_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateDetails'
type MockShipRepository_UpdateDetails_Call struct {
	*mock.Call
}

// UpdateDetails is a helper method to define mock.On call
//   - ctx context.Context
//   - s spec.ShipDetailsUpdate
//   - tx ...*sql.Tx
func (_e *MockShipRepository_Expecter) UpdateDetails(ctx any, s any, tx ...any) *MockShipRepository_UpdateDetails_Call {
	return &MockShipRepository_UpdateDetails_Call{Call: _e.mock.On("UpdateDetails",
		append([]any{ctx, s}, tx...)...)}
}

func (_c *MockShipRepository_UpdateDetails_Call) Run(run func(ctx context.Context, s spec.ShipDetailsUpdate, tx ...*sql.Tx)) *MockShipRepository_UpdateDetails_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.ShipDetailsUpdate
		if args[1] != nil {
			arg1 = args[1].(spec.ShipDetailsUpdate)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockShipRepository_UpdateDetails_Call) Return(err error) *MockShipRepository_UpdateDetails_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockShipRepository_UpdateDetails_Call) RunAndReturn(run func(ctx context.Context, s spec.ShipDetailsUpdate, tx ...*sql.Tx) error) *MockShipRepository_UpdateDetails_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateImage provides a mock function for the type MockShipRepository
func (_mock *MockShipRepository) UpdateImage(ctx context.Context, s spec.ShipImageUpdate, tx ...*sql.Tx) error {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, s, tx)
	} else {
		tmpRet = _mock.Called(ctx, s)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UpdateImage")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.ShipImageUpdate, ...*sql.Tx) error); ok {
		r0 = returnFunc(ctx, s, tx...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockShipRepository_UpdateImage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateImage'
type MockShipRepository_UpdateImage_Call struct {
	*mock.Call
}

// UpdateImage is a helper method to define mock.On call
//   - ctx context.Context
//   - s spec.ShipImageUpdate
//   - tx ...*sql.Tx
func (_e *MockShipRepository_Expecter) UpdateImage(ctx any, s any, tx ...any) *MockShipRepository_UpdateImage_Call {
	return &MockShipRepository_UpdateImage_Call{Call: _e.mock.On("UpdateImage",
		append([]any{ctx, s}, tx...)...)}
}

func (_c *MockShipRepository_UpdateImage_Call) Run(run func(ctx context.Context, s spec.ShipImageUpdate, tx ...*sql.Tx)) *MockShipRepository_UpdateImage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.ShipImageUpdate
		if args[1] != nil {
			arg1 = args[1].(spec.ShipImageUpdate)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockShipRepository_UpdateImage_Call) Return(err error) *MockShipRepository_UpdateImage_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockShipRepository_UpdateImage_Call) RunAndReturn(run func(ctx context.Context, s spec.ShipImageUpdate, tx ...*sql.Tx) error) *MockShipRepository_UpdateImage_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateWithCharacters provides a mock function for the type MockShipRepository
func (_mock *MockShipRepository) UpdateWithCharacters(ctx context.Context, update spec.ShipUpdate, tx ...*sql.Tx) error {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, update, tx)
	} else {
		tmpRet = _mock.Called(ctx, update)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UpdateWithCharacters")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.ShipUpdate, ...*sql.Tx) error); ok {
		r0 = returnFunc(ctx, update, tx...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockShipRepository_UpdateWithCharacters_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateWithCharacters'
type MockShipRepository_UpdateWithCharacters_Call struct {
	*mock.Call
}

// UpdateWithCharacters is a helper method to define mock.On call
//   - ctx context.Context
//   - update spec.ShipUpdate
//   - tx ...*sql.Tx
func (_e *MockShipRepository_Expecter) UpdateWithCharacters(ctx any, update any, tx ...any) *MockShipRepository_UpdateWithCharacters_Call {
	return &MockShipRepository_UpdateWithCharacters_Call{Call: _e.mock.On("UpdateWithCharacters",
		append([]any{ctx, update}, tx...)...)}
}

func (_c *MockShipRepository_UpdateWithCharacters_Call) Run(run func(ctx context.Context, update spec.ShipUpdate, tx ...*sql.Tx)) *MockShipRepository_UpdateWithCharacters_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.ShipUpdate
		if args[1] != nil {
			arg1 = args[1].(spec.ShipUpdate)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockShipRepository_UpdateWithCharacters_Call) Return(err error) *MockShipRepository_UpdateWithCharacters_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockShipRepository_UpdateWithCharacters_Call) RunAndReturn(run func(ctx context.Context, update spec.ShipUpdate, tx ...*sql.Tx) error) *MockShipRepository_UpdateWithCharacters_Call {
	_c.Call.Return(run)
	return _c
}

// Vote provides a mock function for the type MockShipRepository
func (_mock *MockShipRepository) Vote(ctx context.Context, s spec.Vote, tx ...*sql.Tx) error {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, s, tx)
	} else {
		tmpRet = _mock.Called(ctx, s)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Vote")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.Vote, ...*sql.Tx) error); ok {
		r0 = returnFunc(ctx, s, tx...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockShipRepository_Vote_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Vote'
type MockShipRepository_Vote_Call struct {
	*mock.Call
}

// Vote is a helper method to define mock.On call
//   - ctx context.Context
//   - s spec.Vote
//   - tx ...*sql.Tx
func (_e *MockShipRepository_Expecter) Vote(ctx any, s any, tx ...any) *MockShipRepository_Vote_Call {
	return &MockShipRepository_Vote_Call{Call: _e.mock.On("Vote",
		append([]any{ctx, s}, tx...)...)}
}

func (_c *MockShipRepository_Vote_Call) Run(run func(ctx context.Context, s spec.Vote, tx ...*sql.Tx)) *MockShipRepository_Vote_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.Vote
		if args[1] != nil {
			arg1 = args[1].(spec.Vote)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockShipRepository_Vote_Call) Return(err error) *MockShipRepository_Vote_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockShipRepository_Vote_Call) RunAndReturn(run func(ctx context.Context, s spec.Vote, tx ...*sql.Tx) error) *MockShipRepository_Vote_Call {
	_c.Call.Return(run)
	return _c
}
