// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package repository

import (
	"context"
	"database/sql"
	"umineko_city_of_books/internal/model"
	"umineko_city_of_books/internal/model/spec"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockVanityRoleRepository creates a new instance of MockVanityRoleRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockVanityRoleRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockVanityRoleRepository {
	mock := &MockVanityRoleRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockVanityRoleRepository is an autogenerated mock type for the VanityRoleRepository type
type MockVanityRoleRepository struct {
	mock.Mock
}

type MockVanityRoleRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockVanityRoleRepository) EXPECT() *MockVanityRoleRepository_Expecter {
	return &MockVanityRoleRepository_Expecter{mock: &_m.Mock}
}

// AssignToUser provides a mock function for the type MockVanityRoleRepository
func (_mock *MockVanityRoleRepository) AssignToUser(ctx context.Context, s spec.VanityRoleAssignment, tx ...*sql.Tx) error {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, s, tx)
	} else {
		tmpRet = _mock.Called(ctx, s)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for AssignToUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.VanityRoleAssignment, ...*sql.Tx) error); ok {
		r0 = returnFunc(ctx, s, tx...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVanityRoleRepository_AssignToUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'AssignToUser'
type MockVanityRoleRepository_AssignToUser_Call struct {
	*mock.Call
}

// AssignToUser is a helper method to define mock.On call
//   - ctx context.Context
//   - s spec.VanityRoleAssignment
//   - tx ...*sql.Tx
func (_e *MockVanityRoleRepository_Expecter) AssignToUser(ctx any, s any, tx ...any) *MockVanityRoleRepository_AssignToUser_Call {
	return &MockVanityRoleRepository_AssignToUser_Call{Call: _e.mock.On("AssignToUser",
		append([]any{ctx, s}, tx...)...)}
}

func (_c *MockVanityRoleRepository_AssignToUser_Call) Run(run func(ctx context.Context, s spec.VanityRoleAssignment, tx ...*sql.Tx)) *MockVanityRoleRepository_AssignToUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.VanityRoleAssignment
		if args[1] != nil {
			arg1 = args[1].(spec.VanityRoleAssignment)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockVanityRoleRepository_AssignToUser_Call) Return(err error) *MockVanityRoleRepository_AssignToUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVanityRoleRepository_AssignToUser_Call) RunAndReturn(run func(ctx context.Context, s spec.VanityRoleAssignment, tx ...*sql.Tx) error) *MockVanityRoleRepository_AssignToUser_Call {
	_c.Call.Return(run)
	return _c
}

// Create provides a mock function for the type MockVanityRoleRepository
func (_mock *MockVanityRoleRepository) Create(ctx context.Context, s spec.NewVanityRole, tx ...*sql.Tx) error {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, s, tx)
	} else {
		tmpRet = _mock.Called(ctx, s)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.NewVanityRole, ...*sql.Tx) error); ok {
		r0 = returnFunc(ctx, s, tx...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVanityRoleRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockVanityRoleRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - s spec.NewVanityRole
//   - tx ...*sql.Tx
func (_e *MockVanityRoleRepository_Expecter) Create(ctx any, s any, tx ...any) *MockVanityRoleRepository_Create_Call {
	return &MockVanityRoleRepository_Create_Call{Call: _e.mock.On("Create",
		append([]any{ctx, s}, tx...)...)}
}

func (_c *MockVanityRoleRepository_Create_Call) Run(run func(ctx context.Context, s spec.NewVanityRole, tx ...*sql.Tx)) *MockVanityRoleRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.NewVanityRole
		if args[1] != nil {
			arg1 = args[1].(spec.NewVanityRole)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockVanityRoleRepository_Create_Call) Return(err error) *MockVanityRoleRepository_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVanityRoleRepository_Create_Call) RunAndReturn(run func(ctx context.Context, s spec.NewVanityRole, tx ...*sql.Tx) error) *MockVanityRoleRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockVanityRoleRepository
func (_mock *MockVanityRoleRepository) Delete(ctx context.Context, id string, tx ...*sql.Tx) error {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, id, tx)
	} else {
		tmpRet = _mock.Called(ctx, id)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...*sql.Tx) error); ok {
		r0 = returnFunc(ctx, id, tx...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVanityRoleRepository_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockVanityRoleRepository_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - tx ...*sql.Tx
func (_e *MockVanityRoleRepository_Expecter) Delete(ctx any, id any, tx ...any) *MockVanityRoleRepository_Delete_Call {
	return &MockVanityRoleRepository_Delete_Call{Call: _e.mock.On("Delete",
		append([]any{ctx, id}, tx...)...)}
}

func (_c *MockVanityRoleRepository_Delete_Call) Run(run func(ctx context.Context, id string, tx ...*sql.Tx)) *MockVanityRoleRepository_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockVanityRoleRepository_Delete_Call) Return(err error) *MockVanityRoleRepository_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVanityRoleRepository_Delete_Call) RunAndReturn(run func(ctx context.Context, id string, tx ...*sql.Tx) error) *MockVanityRoleRepository_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetAllAssignments provides a mock function for the type MockVanityRoleRepository
func (_mock *MockVanityRoleRepository) GetAllAssignments(ctx context.Context, tx ...*sql.Tx) (map[string][]string, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, tx)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetAllAssignments")
	}

	var r0 map[string][]string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...*sql.Tx) (map[string][]string, error)); ok {
		return returnFunc(ctx, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...*sql.Tx) map[string][]string); ok {
		r0 = returnFunc(ctx, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string][]string)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVanityRoleRepository_GetAllAssignments_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetAllAssignments'
type MockVanityRoleRepository_GetAllAssignments_Call struct {
	*mock.Call
}

// GetAllAssignments is a helper method to define mock.On call
//   - ctx context.Context
//   - tx ...*sql.Tx
func (_e *MockVanityRoleRepository_Expecter) GetAllAssignments(ctx any, tx ...any) *MockVanityRoleRepository_GetAllAssignments_Call {
	return &MockVanityRoleRepository_GetAllAssignments_Call{Call: _e.mock.On("GetAllAssignments",
		append([]any{ctx}, tx...)...)}
}

func (_c *MockVanityRoleRepository_GetAllAssignments_Call) Run(run func(ctx context.Context, tx ...*sql.Tx)) *MockVanityRoleRepository_GetAllAssignments_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 1 {
			variadicArgs = args[1].([]*sql.Tx)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockVanityRoleRepository_GetAllAssignments_Call) Return(stringToStrings map[string][]string, err error) *MockVanityRoleRepository_GetAllAssignments_Call {
	_c.Call.Return(stringToStrings, err)
	return _c
}

func (_c *MockVanityRoleRepository_GetAllAssignments_Call) RunAndReturn(run func(ctx context.Context, tx ...*sql.Tx) (map[string][]string, error)) *MockVanityRoleRepository_GetAllAssignments_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockVanityRoleRepository
func (_mock *MockVanityRoleRepository) GetByID(ctx context.Context, id string, tx ...*sql.Tx) (*model.VanityRoleRow, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, id, tx)
	} else {
		tmpRet = _mock.Called(ctx, id)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.VanityRoleRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...*sql.Tx) (*model.VanityRoleRow, error)); ok {
		return returnFunc(ctx, id, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...*sql.Tx) *model.VanityRoleRow); ok {
		r0 = returnFunc(ctx, id, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.VanityRoleRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, id, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVanityRoleRepository_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockVanityRoleRepository_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id string
//   - tx ...*sql.Tx
func (_e *MockVanityRoleRepository_Expecter) GetByID(ctx any, id any, tx ...any) *MockVanityRoleRepository_GetByID_Call {
	return &MockVanityRoleRepository_GetByID_Call{Call: _e.mock.On("GetByID",
		append([]any{ctx, id}, tx...)...)}
}

func (_c *MockVanityRoleRepository_GetByID_Call) Run(run func(ctx context.Context, id string, tx ...*sql.Tx)) *MockVanityRoleRepository_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockVanityRoleRepository_GetByID_Call) Return(vanityRoleRow *model.VanityRoleRow, err error) *MockVanityRoleRepository_GetByID_Call {
	_c.Call.Return(vanityRoleRow, err)
	return _c
}

func (_c *MockVanityRoleRepository_GetByID_Call) RunAndReturn(run func(ctx context.Context, id string, tx ...*sql.Tx) (*model.VanityRoleRow, error)) *MockVanityRoleRepository_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// GetRolesForUser provides a mock function for the type MockVanityRoleRepository
func (_mock *MockVanityRoleRepository) GetRolesForUser(ctx context.Context, userID uuid.UUID, tx ...*sql.Tx) ([]model.VanityRoleRow, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, userID, tx)
	} else {
		tmpRet = _mock.Called(ctx, userID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetRolesForUser")
	}

	var r0 []model.VanityRoleRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...*sql.Tx) ([]model.VanityRoleRow, error)); ok {
		return returnFunc(ctx, userID, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...*sql.Tx) []model.VanityRoleRow); ok {
		r0 = returnFunc(ctx, userID, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.VanityRoleRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, userID, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVanityRoleRepository_GetRolesForUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRolesForUser'
type MockVanityRoleRepository_GetRolesForUser_Call struct {
	*mock.Call
}

// GetRolesForUser is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - tx ...*sql.Tx
func (_e *MockVanityRoleRepository_Expecter) GetRolesForUser(ctx any, userID any, tx ...any) *MockVanityRoleRepository_GetRolesForUser_Call {
	return &MockVanityRoleRepository_GetRolesForUser_Call{Call: _e.mock.On("GetRolesForUser",
		append([]any{ctx, userID}, tx...)...)}
}

func (_c *MockVanityRoleRepository_GetRolesForUser_Call) Run(run func(ctx context.Context, userID uuid.UUID, tx ...*sql.Tx)) *MockVanityRoleRepository_GetRolesForUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockVanityRoleRepository_GetRolesForUser_Call) Return(vanityRoleRows []model.VanityRoleRow, err error) *MockVanityRoleRepository_GetRolesForUser_Call {
	_c.Call.Return(vanityRoleRows, err)
	return _c
}

func (_c *MockVanityRoleRepository_GetRolesForUser_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, tx ...*sql.Tx) ([]model.VanityRoleRow, error)) *MockVanityRoleRepository_GetRolesForUser_Call {
	_c.Call.Return(run)
	return _c
}

// GetRolesForUsersBatch provides a mock function for the type MockVanityRoleRepository
func (_mock *MockVanityRoleRepository) GetRolesForUsersBatch(ctx context.Context, userIDs []uuid.UUID, tx ...*sql.Tx) (map[uuid.UUID][]model.VanityRoleRow, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, userIDs, tx)
	} else {
		tmpRet = _mock.Called(ctx, userIDs)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetRolesForUsersBatch")
	}

	var r0 map[uuid.UUID][]model.VanityRoleRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID, ...*sql.Tx) (map[uuid.UUID][]model.VanityRoleRow, error)); ok {
		return returnFunc(ctx, userIDs, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, []uuid.UUID, ...*sql.Tx) map[uuid.UUID][]model.VanityRoleRow); ok {
		r0 = returnFunc(ctx, userIDs, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[uuid.UUID][]model.VanityRoleRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, []uuid.UUID, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, userIDs, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVanityRoleRepository_GetRolesForUsersBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetRolesForUsersBatch'
type MockVanityRoleRepository_GetRolesForUsersBatch_Call struct {
	*mock.Call
}

// GetRolesForUsersBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - userIDs []uuid.UUID
//   - tx ...*sql.Tx
func (_e *MockVanityRoleRepository_Expecter) GetRolesForUsersBatch(ctx any, userIDs any, tx ...any) *MockVanityRoleRepository_GetRolesForUsersBatch_Call {
	return &MockVanityRoleRepository_GetRolesForUsersBatch_Call{Call: _e.mock.On("GetRolesForUsersBatch",
		append([]any{ctx, userIDs}, tx...)...)}
}

func (_c *MockVanityRoleRepository_GetRolesForUsersBatch_Call) Run(run func(ctx context.Context, userIDs []uuid.UUID, tx ...*sql.Tx)) *MockVanityRoleRepository_GetRolesForUsersBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []uuid.UUID
		if args[1] != nil {
			arg1 = args[1].([]uuid.UUID)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockVanityRoleRepository_GetRolesForUsersBatch_Call) Return(uUIDToVanityRoleRows map[uuid.UUID][]model.VanityRoleRow, err error) *MockVanityRoleRepository_GetRolesForUsersBatch_Call {
	_c.Call.Return(uUIDToVanityRoleRows, err)
	return _c
}

func (_c *MockVanityRoleRepository_GetRolesForUsersBatch_Call) RunAndReturn(run func(ctx context.Context, userIDs []uuid.UUID, tx ...*sql.Tx) (map[uuid.UUID][]model.VanityRoleRow, error)) *MockVanityRoleRepository_GetRolesForUsersBatch_Call {
	_c.Call.Return(run)
	return _c
}

// GetUsersForRole provides a mock function for the type MockVanityRoleRepository
func (_mock *MockVanityRoleRepository) GetUsersForRole(ctx context.Context, q spec.VanityRoleUserQuery, tx ...*sql.Tx) ([]model.VanityRoleUserRow, int, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, q, tx)
	} else {
		tmpRet = _mock.Called(ctx, q)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetUsersForRole")
	}

	var r0 []model.VanityRoleUserRow
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.VanityRoleUserQuery, ...*sql.Tx) ([]model.VanityRoleUserRow, int, error)); ok {
		return returnFunc(ctx, q, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.VanityRoleUserQuery, ...*sql.Tx) []model.VanityRoleUserRow); ok {
		r0 = returnFunc(ctx, q, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.VanityRoleUserRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, spec.VanityRoleUserQuery, ...*sql.Tx) int); ok {
		r1 = returnFunc(ctx, q, tx...)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, spec.VanityRoleUserQuery, ...*sql.Tx) error); ok {
		r2 = returnFunc(ctx, q, tx...)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockVanityRoleRepository_GetUsersForRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetUsersForRole'
type MockVanityRoleRepository_GetUsersForRole_Call struct {
	*mock.Call
}

// GetUsersForRole is a helper method to define mock.On call
//   - ctx context.Context
//   - q spec.VanityRoleUserQuery
//   - tx ...*sql.Tx
func (_e *MockVanityRoleRepository_Expecter) GetUsersForRole(ctx any, q any, tx ...any) *MockVanityRoleRepository_GetUsersForRole_Call {
	return &MockVanityRoleRepository_GetUsersForRole_Call{Call: _e.mock.On("GetUsersForRole",
		append([]any{ctx, q}, tx...)...)}
}

func (_c *MockVanityRoleRepository_GetUsersForRole_Call) Run(run func(ctx context.Context, q spec.VanityRoleUserQuery, tx ...*sql.Tx)) *MockVanityRoleRepository_GetUsersForRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.VanityRoleUserQuery
		if args[1] != nil {
			arg1 = args[1].(spec.VanityRoleUserQuery)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockVanityRoleRepository_GetUsersForRole_Call) Return(vanityRoleUserRows []model.VanityRoleUserRow, n int, err error) *MockVanityRoleRepository_GetUsersForRole_Call {
	_c.Call.Return(vanityRoleUserRows, n, err)
	return _c
}

func (_c *MockVanityRoleRepository_GetUsersForRole_Call) RunAndReturn(run func(ctx context.Context, q spec.VanityRoleUserQuery, tx ...*sql.Tx) ([]model.VanityRoleUserRow, int, error)) *MockVanityRoleRepository_GetUsersForRole_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockVanityRoleRepository
func (_mock *MockVanityRoleRepository) List(ctx context.Context, tx ...*sql.Tx) ([]model.VanityRoleRow, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, tx)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.VanityRoleRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...*sql.Tx) ([]model.VanityRoleRow, error)); ok {
		return returnFunc(ctx, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...*sql.Tx) []model.VanityRoleRow); ok {
		r0 = returnFunc(ctx, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.VanityRoleRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockVanityRoleRepository_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockVanityRoleRepository_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - tx ...*sql.Tx
func (_e *MockVanityRoleRepository_Expecter) List(ctx any, tx ...any) *MockVanityRoleRepository_List_Call {
	return &MockVanityRoleRepository_List_Call{Call: _e.mock.On("List",
		append([]any{ctx}, tx...)...)}
}

func (_c *MockVanityRoleRepository_List_Call) Run(run func(ctx context.Context, tx ...*sql.Tx)) *MockVanityRoleRepository_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 1 {
			variadicArgs = args[1].([]*sql.Tx)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockVanityRoleRepository_List_Call) Return(vanityRoleRows []model.VanityRoleRow, err error) *MockVanityRoleRepository_List_Call {
	_c.Call.Return(vanityRoleRows, err)
	return _c
}

func (_c *MockVanityRoleRepository_List_Call) RunAndReturn(run func(ctx context.Context, tx ...*sql.Tx) ([]model.VanityRoleRow, error)) *MockVanityRoleRepository_List_Call {
	_c.Call.Return(run)
	return _c
}

// MoveUserRole provides a mock function for the type MockVanityRoleRepository
func (_mock *MockVanityRoleRepository) MoveUserRole(ctx context.Context, move spec.VanityRoleMove, tx ...*sql.Tx) error {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, move, tx)
	} else {
		tmpRet = _mock.Called(ctx, move)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for MoveUserRole")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.VanityRoleMove, ...*sql.Tx) error); ok {
		r0 = returnFunc(ctx, move, tx...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVanityRoleRepository_MoveUserRole_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MoveUserRole'
type MockVanityRoleRepository_MoveUserRole_Call struct {
	*mock.Call
}

// MoveUserRole is a helper method to define mock.On call
//   - ctx context.Context
//   - move spec.VanityRoleMove
//   - tx ...*sql.Tx
func (_e *MockVanityRoleRepository_Expecter) MoveUserRole(ctx any, move any, tx ...any) *MockVanityRoleRepository_MoveUserRole_Call {
	return &MockVanityRoleRepository_MoveUserRole_Call{Call: _e.mock.On("MoveUserRole",
		append([]any{ctx, move}, tx...)...)}
}

func (_c *MockVanityRoleRepository_MoveUserRole_Call) Run(run func(ctx context.Context, move spec.VanityRoleMove, tx ...*sql.Tx)) *MockVanityRoleRepository_MoveUserRole_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.VanityRoleMove
		if args[1] != nil {
			arg1 = args[1].(spec.VanityRoleMove)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockVanityRoleRepository_MoveUserRole_Call) Return(err error) *MockVanityRoleRepository_MoveUserRole_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVanityRoleRepository_MoveUserRole_Call) RunAndReturn(run func(ctx context.Context, move spec.VanityRoleMove, tx ...*sql.Tx) error) *MockVanityRoleRepository_MoveUserRole_Call {
	_c.Call.Return(run)
	return _c
}

// UnassignFromUser provides a mock function for the type MockVanityRoleRepository
func (_mock *MockVanityRoleRepository) UnassignFromUser(ctx context.Context, s spec.VanityRoleAssignment, tx ...*sql.Tx) error {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, s, tx)
	} else {
		tmpRet = _mock.Called(ctx, s)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UnassignFromUser")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.VanityRoleAssignment, ...*sql.Tx) error); ok {
		r0 = returnFunc(ctx, s, tx...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVanityRoleRepository_UnassignFromUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnassignFromUser'
type MockVanityRoleRepository_UnassignFromUser_Call struct {
	*mock.Call
}

// UnassignFromUser is a helper method to define mock.On call
//   - ctx context.Context
//   - s spec.VanityRoleAssignment
//   - tx ...*sql.Tx
func (_e *MockVanityRoleRepository_Expecter) UnassignFromUser(ctx any, s any, tx ...any) *MockVanityRoleRepository_UnassignFromUser_Call {
	return &MockVanityRoleRepository_UnassignFromUser_Call{Call: _e.mock.On("UnassignFromUser",
		append([]any{ctx, s}, tx...)...)}
}

func (_c *MockVanityRoleRepository_UnassignFromUser_Call) Run(run func(ctx context.Context, s spec.VanityRoleAssignment, tx ...*sql.Tx)) *MockVanityRoleRepository_UnassignFromUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.VanityRoleAssignment
		if args[1] != nil {
			arg1 = args[1].(spec.VanityRoleAssignment)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockVanityRoleRepository_UnassignFromUser_Call) Return(err error) *MockVanityRoleRepository_UnassignFromUser_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVanityRoleRepository_UnassignFromUser_Call) RunAndReturn(run func(ctx context.Context, s spec.VanityRoleAssignment, tx ...*sql.Tx) error) *MockVanityRoleRepository_UnassignFromUser_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockVanityRoleRepository
func (_mock *MockVanityRoleRepository) Update(ctx context.Context, s spec.VanityRoleUpdate, tx ...*sql.Tx) error {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, s, tx)
	} else {
		tmpRet = _mock.Called(ctx, s)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.VanityRoleUpdate, ...*sql.Tx) error); ok {
		r0 = returnFunc(ctx, s, tx...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockVanityRoleRepository_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockVanityRoleRepository_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - s spec.VanityRoleUpdate
//   - tx ...*sql.Tx
func (_e *MockVanityRoleRepository_Expecter) Update(ctx any, s any, tx ...any) *MockVanityRoleRepository_Update_Call {
	return &MockVanityRoleRepository_Update_Call{Call: _e.mock.On("Update",
		append([]any{ctx, s}, tx...)...)}
}

func (_c *MockVanityRoleRepository_Update_Call) Run(run func(ctx context.Context, s spec.VanityRoleUpdate, tx ...*sql.Tx)) *MockVanityRoleRepository_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.VanityRoleUpdate
		if args[1] != nil {
			arg1 = args[1].(spec.VanityRoleUpdate)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockVanityRoleRepository_Update_Call) Return(err error) *MockVanityRoleRepository_Update_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockVanityRoleRepository_Update_Call) RunAndReturn(run func(ctx context.Context, s spec.VanityRoleUpdate, tx ...*sql.Tx) error) *MockVanityRoleRepository_Update_Call {
	_c.Call.Return(run)
	return _c
}
