package audit

type (
	Action     string
	TargetType string
)

const (
	ActionUserCreated   Action = "user_created"
	ActionPasswordReset Action = "password_reset"

	ActionSetRole            Action = "set_role"
	ActionRemoveRole         Action = "remove_role"
	ActionBanUser            Action = "ban_user"
	ActionUnbanUser          Action = "unban_user"
	ActionLockUser           Action = "lock_user"
	ActionUnlockUser         Action = "unlock_user"
	ActionApproveUser        Action = "approve_user"
	ActionUnapproveUser      Action = "unapprove_user"
	ActionDeleteUser         Action = "delete_user"
	ActionResetPassword      Action = "reset_password"
	ActionSetUserEmail       Action = "set_user_email"
	ActionVerifyUserEmail    Action = "verify_user_email"
	ActionUnverifyUserEmail  Action = "unverify_user_email"
	ActionSetDisplayName     Action = "set_display_name"
	ActionLockDisplayName    Action = "lock_display_name"
	ActionUnlockDisplayName  Action = "unlock_display_name"
	ActionForceLogout        Action = "force_logout"
	ActionUpdateSettings     Action = "update_settings"
	ActionSendTestEmail      Action = "send_test_email"
	ActionCreateInvite       Action = "create_invite"
	ActionDeleteInvite       Action = "delete_invite"
	ActionCreateVanityRole   Action = "create_vanity_role"
	ActionUpdateVanityRole   Action = "update_vanity_role"
	ActionDeleteVanityRole   Action = "delete_vanity_role"
	ActionAssignVanityRole   Action = "assign_vanity_role"
	ActionUnassignVanityRole Action = "unassign_vanity_role"

	ActionUpdateRolePermissions       Action = "update_role_permissions"
	ActionUpdateVanityRolePermissions Action = "update_vanity_role_permissions"

	ActionChatRoomBan                Action = "chat_room_ban"
	ActionChatRoomUnban              Action = "chat_room_unban"
	ActionChatWordFilterKick         Action = "chat_word_filter_kick"
	ActionChatWordFilterDelete       Action = "chat_word_filter_delete"
	ActionChatRoomBannedWordCreate   Action = "chat_room_banned_word_create"
	ActionChatRoomBannedWordUpdate   Action = "chat_room_banned_word_update"
	ActionChatRoomBannedWordDelete   Action = "chat_room_banned_word_delete"
	ActionChatGlobalBannedWordCreate Action = "chat_global_banned_word_create"
	ActionChatGlobalBannedWordUpdate Action = "chat_global_banned_word_update"
	ActionChatGlobalBannedWordDelete Action = "chat_global_banned_word_delete"

	ActionChatMessageDelete    Action = "chat_message_delete"
	ActionChatMessageDeleteMod Action = "chat_message_delete_mod"
	ActionChatRoomDelete       Action = "chat_room_delete"
	ActionChatRoomUpdate       Action = "chat_room_update"
	ActionChatRoomKick         Action = "chat_room_kick"
	ActionChatRoomTimeout      Action = "chat_room_timeout"

	ActionWatchPartyStart        Action = "watch_party.start"
	ActionWatchPartyEnd          Action = "watch_party.end"
	ActionWatchPartyKick         Action = "watch_party.kick"
	ActionWatchPartyGrantControl Action = "watch_party.grant_control"

	ActionPostCommentDelete              Action = "post_comment_delete"
	ActionPostCommentDeleteAdmin         Action = "post_comment_delete_admin"
	ActionArtCommentDelete               Action = "art_comment_delete"
	ActionArtCommentDeleteAdmin          Action = "art_comment_delete_admin"
	ActionFanficCommentDelete            Action = "fanfic_comment_delete"
	ActionFanficCommentDeleteAdmin       Action = "fanfic_comment_delete_admin"
	ActionMysteryCommentDelete           Action = "mystery_comment_delete"
	ActionMysteryCommentDeleteAdmin      Action = "mystery_comment_delete_admin"
	ActionJournalCommentDelete           Action = "journal_comment_delete"
	ActionJournalCommentDeleteAdmin      Action = "journal_comment_delete_admin"
	ActionShipCommentDelete              Action = "ship_comment_delete"
	ActionShipCommentDeleteAdmin         Action = "ship_comment_delete_admin"
	ActionSecretCommentDelete            Action = "secret_comment_delete"
	ActionSecretCommentDeleteAdmin       Action = "secret_comment_delete_admin"
	ActionAnnouncementCommentDelete      Action = "announcement_comment_delete"
	ActionAnnouncementCommentDeleteAdmin Action = "announcement_comment_delete_admin"
	ActionOCCommentDelete                Action = "oc_comment_delete"
	ActionOCCommentDeleteAdmin           Action = "oc_comment_delete_admin"

	ActionPostCommentUpdateAdmin         Action = "post_comment_update_admin"
	ActionArtCommentUpdateAdmin          Action = "art_comment_update_admin"
	ActionFanficCommentUpdateAdmin       Action = "fanfic_comment_update_admin"
	ActionMysteryCommentUpdateAdmin      Action = "mystery_comment_update_admin"
	ActionJournalCommentUpdateAdmin      Action = "journal_comment_update_admin"
	ActionShipCommentUpdateAdmin         Action = "ship_comment_update_admin"
	ActionSecretCommentUpdateAdmin       Action = "secret_comment_update_admin"
	ActionAnnouncementCommentUpdateAdmin Action = "announcement_comment_update_admin"
	ActionOCCommentUpdateAdmin           Action = "oc_comment_update_admin"

	ActionPostDelete               Action = "post_delete"
	ActionPostDeleteAdmin          Action = "post_delete_admin"
	ActionArtDelete                Action = "art_delete"
	ActionArtDeleteAdmin           Action = "art_delete_admin"
	ActionGalleryDelete            Action = "gallery_delete"
	ActionFanficDelete             Action = "fanfic_delete"
	ActionFanficDeleteAdmin        Action = "fanfic_delete_admin"
	ActionFanficUpdateAdmin        Action = "fanfic_update_admin"
	ActionFanficChapterDelete      Action = "fanfic_chapter_delete"
	ActionFanficChapterDeleteAdmin Action = "fanfic_chapter_delete_admin"
	ActionFanficChapterUpdateAdmin Action = "fanfic_chapter_update_admin"
	ActionJournalDelete            Action = "journal_delete"
	ActionJournalDeleteAdmin       Action = "journal_delete_admin"
	ActionJournalUpdateAdmin       Action = "journal_update_admin"
	ActionJournalEntryDelete       Action = "journal_entry_delete"
	ActionJournalEntryDeleteAdmin  Action = "journal_entry_delete_admin"
	ActionJournalEntryCreateAdmin  Action = "journal_entry_create_admin"
	ActionJournalEntryUpdateAdmin  Action = "journal_entry_update_admin"
	ActionShipDelete               Action = "ship_delete"
	ActionShipDeleteAdmin          Action = "ship_delete_admin"
	ActionShipUpdateAdmin          Action = "ship_update_admin"
	ActionOCDelete                 Action = "oc_delete"
	ActionOCDeleteAdmin            Action = "oc_delete_admin"
	ActionAnnouncementCreate       Action = "announcement_create"
	ActionAnnouncementUpdate       Action = "announcement_update"
	ActionAnnouncementDelete       Action = "announcement_delete"
	ActionAnnouncementPin          Action = "announcement_pin"

	ActionMysteryDelete             Action = "mystery_delete"
	ActionMysteryDeleteAdmin        Action = "mystery_delete_admin"
	ActionMysteryUpdateAdmin        Action = "mystery_update_admin"
	ActionMysterySolved             Action = "mystery_solved"
	ActionMysteryClosed             Action = "mystery_closed"
	ActionMysteryClueUpdate         Action = "mystery_clue_update"
	ActionMysteryClueDelete         Action = "mystery_clue_delete"
	ActionMysteryAttemptDeleteAdmin Action = "mystery_attempt_delete_admin"
	ActionTheoryDelete              Action = "theory_delete"
	ActionTheoryDeleteAdmin         Action = "theory_delete_admin"
	ActionTheoryUpdateAdmin         Action = "theory_update_admin"
	ActionTheoryRefuted             Action = "theory_refuted"
	ActionTheoryResponseDeleteAdmin Action = "theory_response_delete_admin"
	ActionMysteryScoreAdjust        Action = "mystery_score_adjust"
	ActionGMScoreAdjust             Action = "gm_score_adjust"

	ActionChatbotCreate           Action = "chatbot_create"
	ActionChatbotUpdate           Action = "chatbot_update"
	ActionChatbotDelete           Action = "chatbot_delete"
	ActionChatbotBasePromptCreate Action = "chatbot_base_prompt_create"
	ActionChatbotBasePromptUpdate Action = "chatbot_base_prompt_update"
	ActionChatbotBasePromptDelete Action = "chatbot_base_prompt_delete"
	ActionChatbotOptInRoleMigrate Action = "chatbot_opt_in_role_migrate"

	ActionChangePassword  Action = "change_password"
	ActionChangeEmail     Action = "change_email"
	ActionDeleteAccount   Action = "delete_account"
	ActionLoginBanned     Action = "login_banned"
	ActionBannedGifCreate Action = "banned_gif_create"
	ActionBannedGifDelete Action = "banned_gif_delete"
)

const (
	TargetUser       TargetType = "user"
	TargetSettings   TargetType = "settings"
	TargetInvite     TargetType = "invite"
	TargetRole       TargetType = "role"
	TargetVanityRole TargetType = "vanity_role"

	TargetChatRoom              TargetType = "chat_room"
	TargetBannedWord            TargetType = "banned_word"
	TargetChatWatchPartySession TargetType = "chat_watch_party_session"

	TargetPost              TargetType = "post"
	TargetArt               TargetType = "art"
	TargetGallery           TargetType = "gallery"
	TargetFanfic            TargetType = "fanfic"
	TargetFanficChapter     TargetType = "fanfic_chapter"
	TargetJournal           TargetType = "journal"
	TargetJournalEntry      TargetType = "journal_entry"
	TargetShip              TargetType = "ship"
	TargetOC                TargetType = "oc"
	TargetAnnouncement      TargetType = "announcement"
	TargetMystery           TargetType = "mystery"
	TargetMysteryAttempt    TargetType = "mystery_attempt"
	TargetTheory            TargetType = "theory"
	TargetTheoryResponse    TargetType = "theory_response"
	TargetChatbot           TargetType = "chatbot"
	TargetChatbotBasePrompt TargetType = "chatbot_base_prompt"
	TargetBannedGif         TargetType = "banned_gif"

	TargetPostComment         TargetType = "post_comment"
	TargetArtComment          TargetType = "art_comment"
	TargetFanficComment       TargetType = "fanfic_comment"
	TargetMysteryComment      TargetType = "mystery_comment"
	TargetJournalComment      TargetType = "journal_comment"
	TargetShipComment         TargetType = "ship_comment"
	TargetSecretComment       TargetType = "secret_comment"
	TargetAnnouncementComment TargetType = "announcement_comment"
	TargetOCComment           TargetType = "oc_comment"
)
