// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package journal

import (
	"context"
	"io"
	"umineko_city_of_books/internal/bounds"
	"umineko_city_of_books/internal/dto"
	"umineko_city_of_books/internal/journal/params"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockService creates a new instance of MockService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockService(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockService {
	mock := &MockService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockService is an autogenerated mock type for the Service type
type MockService struct {
	mock.Mock
}

type MockService_Expecter struct {
	mock *mock.Mock
}

func (_m *MockService) EXPECT() *MockService_Expecter {
	return &MockService_Expecter{mock: &_m.Mock}
}

// ArchiveStale provides a mock function for the type MockService
func (_mock *MockService) ArchiveStale(ctx context.Context) (int, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for ArchiveStale")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (int, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) int); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ArchiveStale_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ArchiveStale'
type MockService_ArchiveStale_Call struct {
	*mock.Call
}

// ArchiveStale is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockService_Expecter) ArchiveStale(ctx any) *MockService_ArchiveStale_Call {
	return &MockService_ArchiveStale_Call{Call: _e.mock.On("ArchiveStale", ctx)}
}

func (_c *MockService_ArchiveStale_Call) Run(run func(ctx context.Context)) *MockService_ArchiveStale_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockService_ArchiveStale_Call) Return(n int, err error) *MockService_ArchiveStale_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockService_ArchiveStale_Call) RunAndReturn(run func(ctx context.Context) (int, error)) *MockService_ArchiveStale_Call {
	_c.Call.Return(run)
	return _c
}

// CreateComment provides a mock function for the type MockService
func (_mock *MockService) CreateComment(ctx context.Context, journalID uuid.UUID, userID uuid.UUID, entryID *uuid.UUID, parentID *uuid.UUID, body string) (uuid.UUID, error) {
	ret := _mock.Called(ctx, journalID, userID, entryID, parentID, body)

	if len(ret) == 0 {
		panic("no return value specified for CreateComment")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, *uuid.UUID, *uuid.UUID, string) (uuid.UUID, error)); ok {
		return returnFunc(ctx, journalID, userID, entryID, parentID, body)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, *uuid.UUID, *uuid.UUID, string) uuid.UUID); ok {
		r0 = returnFunc(ctx, journalID, userID, entryID, parentID, body)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, *uuid.UUID, *uuid.UUID, string) error); ok {
		r1 = returnFunc(ctx, journalID, userID, entryID, parentID, body)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_CreateComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateComment'
type MockService_CreateComment_Call struct {
	*mock.Call
}

// CreateComment is a helper method to define mock.On call
//   - ctx context.Context
//   - journalID uuid.UUID
//   - userID uuid.UUID
//   - entryID *uuid.UUID
//   - parentID *uuid.UUID
//   - body string
func (_e *MockService_Expecter) CreateComment(ctx any, journalID any, userID any, entryID any, parentID any, body any) *MockService_CreateComment_Call {
	return &MockService_CreateComment_Call{Call: _e.mock.On("CreateComment", ctx, journalID, userID, entryID, parentID, body)}
}

func (_c *MockService_CreateComment_Call) Run(run func(ctx context.Context, journalID uuid.UUID, userID uuid.UUID, entryID *uuid.UUID, parentID *uuid.UUID, body string)) *MockService_CreateComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 *uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(*uuid.UUID)
		}
		var arg4 *uuid.UUID
		if args[4] != nil {
			arg4 = args[4].(*uuid.UUID)
		}
		var arg5 string
		if args[5] != nil {
			arg5 = args[5].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
		)
	})
	return _c
}

func (_c *MockService_CreateComment_Call) Return(uUID uuid.UUID, err error) *MockService_CreateComment_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockService_CreateComment_Call) RunAndReturn(run func(ctx context.Context, journalID uuid.UUID, userID uuid.UUID, entryID *uuid.UUID, parentID *uuid.UUID, body string) (uuid.UUID, error)) *MockService_CreateComment_Call {
	_c.Call.Return(run)
	return _c
}

// CreateEntry provides a mock function for the type MockService
func (_mock *MockService) CreateEntry(ctx context.Context, journalID uuid.UUID, userID uuid.UUID, req dto.CreateJournalEntryRequest) (uuid.UUID, int, error) {
	ret := _mock.Called(ctx, journalID, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateEntry")
	}

	var r0 uuid.UUID
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, dto.CreateJournalEntryRequest) (uuid.UUID, int, error)); ok {
		return returnFunc(ctx, journalID, userID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, dto.CreateJournalEntryRequest) uuid.UUID); ok {
		r0 = returnFunc(ctx, journalID, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, dto.CreateJournalEntryRequest) int); ok {
		r1 = returnFunc(ctx, journalID, userID, req)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uuid.UUID, uuid.UUID, dto.CreateJournalEntryRequest) error); ok {
		r2 = returnFunc(ctx, journalID, userID, req)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockService_CreateEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateEntry'
type MockService_CreateEntry_Call struct {
	*mock.Call
}

// CreateEntry is a helper method to define mock.On call
//   - ctx context.Context
//   - journalID uuid.UUID
//   - userID uuid.UUID
//   - req dto.CreateJournalEntryRequest
func (_e *MockService_Expecter) CreateEntry(ctx any, journalID any, userID any, req any) *MockService_CreateEntry_Call {
	return &MockService_CreateEntry_Call{Call: _e.mock.On("CreateEntry", ctx, journalID, userID, req)}
}

func (_c *MockService_CreateEntry_Call) Run(run func(ctx context.Context, journalID uuid.UUID, userID uuid.UUID, req dto.CreateJournalEntryRequest)) *MockService_CreateEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 dto.CreateJournalEntryRequest
		if args[3] != nil {
			arg3 = args[3].(dto.CreateJournalEntryRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_CreateEntry_Call) Return(uUID uuid.UUID, n int, err error) *MockService_CreateEntry_Call {
	_c.Call.Return(uUID, n, err)
	return _c
}

func (_c *MockService_CreateEntry_Call) RunAndReturn(run func(ctx context.Context, journalID uuid.UUID, userID uuid.UUID, req dto.CreateJournalEntryRequest) (uuid.UUID, int, error)) *MockService_CreateEntry_Call {
	_c.Call.Return(run)
	return _c
}

// CreateJournal provides a mock function for the type MockService
func (_mock *MockService) CreateJournal(ctx context.Context, userID uuid.UUID, req dto.CreateJournalRequest) (uuid.UUID, error) {
	ret := _mock.Called(ctx, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for CreateJournal")
	}

	var r0 uuid.UUID
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.CreateJournalRequest) (uuid.UUID, error)); ok {
		return returnFunc(ctx, userID, req)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, dto.CreateJournalRequest) uuid.UUID); ok {
		r0 = returnFunc(ctx, userID, req)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(uuid.UUID)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, dto.CreateJournalRequest) error); ok {
		r1 = returnFunc(ctx, userID, req)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_CreateJournal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateJournal'
type MockService_CreateJournal_Call struct {
	*mock.Call
}

// CreateJournal is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - req dto.CreateJournalRequest
func (_e *MockService_Expecter) CreateJournal(ctx any, userID any, req any) *MockService_CreateJournal_Call {
	return &MockService_CreateJournal_Call{Call: _e.mock.On("CreateJournal", ctx, userID, req)}
}

func (_c *MockService_CreateJournal_Call) Run(run func(ctx context.Context, userID uuid.UUID, req dto.CreateJournalRequest)) *MockService_CreateJournal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 dto.CreateJournalRequest
		if args[2] != nil {
			arg2 = args[2].(dto.CreateJournalRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_CreateJournal_Call) Return(uUID uuid.UUID, err error) *MockService_CreateJournal_Call {
	_c.Call.Return(uUID, err)
	return _c
}

func (_c *MockService_CreateJournal_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, req dto.CreateJournalRequest) (uuid.UUID, error)) *MockService_CreateJournal_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteComment provides a mock function for the type MockService
func (_mock *MockService) DeleteComment(ctx context.Context, id uuid.UUID, userID uuid.UUID) error {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteComment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_DeleteComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteComment'
type MockService_DeleteComment_Call struct {
	*mock.Call
}

// DeleteComment is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userID uuid.UUID
func (_e *MockService_Expecter) DeleteComment(ctx any, id any, userID any) *MockService_DeleteComment_Call {
	return &MockService_DeleteComment_Call{Call: _e.mock.On("DeleteComment", ctx, id, userID)}
}

func (_c *MockService_DeleteComment_Call) Run(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID)) *MockService_DeleteComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_DeleteComment_Call) Return(err error) *MockService_DeleteComment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_DeleteComment_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID) error) *MockService_DeleteComment_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteEntry provides a mock function for the type MockService
func (_mock *MockService) DeleteEntry(ctx context.Context, entryID uuid.UUID, userID uuid.UUID) error {
	ret := _mock.Called(ctx, entryID, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteEntry")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, entryID, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_DeleteEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteEntry'
type MockService_DeleteEntry_Call struct {
	*mock.Call
}

// DeleteEntry is a helper method to define mock.On call
//   - ctx context.Context
//   - entryID uuid.UUID
//   - userID uuid.UUID
func (_e *MockService_Expecter) DeleteEntry(ctx any, entryID any, userID any) *MockService_DeleteEntry_Call {
	return &MockService_DeleteEntry_Call{Call: _e.mock.On("DeleteEntry", ctx, entryID, userID)}
}

func (_c *MockService_DeleteEntry_Call) Run(run func(ctx context.Context, entryID uuid.UUID, userID uuid.UUID)) *MockService_DeleteEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_DeleteEntry_Call) Return(err error) *MockService_DeleteEntry_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_DeleteEntry_Call) RunAndReturn(run func(ctx context.Context, entryID uuid.UUID, userID uuid.UUID) error) *MockService_DeleteEntry_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteEntryMedia provides a mock function for the type MockService
func (_mock *MockService) DeleteEntryMedia(ctx context.Context, entryID uuid.UUID, mediaID int64, userID uuid.UUID) error {
	ret := _mock.Called(ctx, entryID, mediaID, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteEntryMedia")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int64, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, entryID, mediaID, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_DeleteEntryMedia_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteEntryMedia'
type MockService_DeleteEntryMedia_Call struct {
	*mock.Call
}

// DeleteEntryMedia is a helper method to define mock.On call
//   - ctx context.Context
//   - entryID uuid.UUID
//   - mediaID int64
//   - userID uuid.UUID
func (_e *MockService_Expecter) DeleteEntryMedia(ctx any, entryID any, mediaID any, userID any) *MockService_DeleteEntryMedia_Call {
	return &MockService_DeleteEntryMedia_Call{Call: _e.mock.On("DeleteEntryMedia", ctx, entryID, mediaID, userID)}
}

func (_c *MockService_DeleteEntryMedia_Call) Run(run func(ctx context.Context, entryID uuid.UUID, mediaID int64, userID uuid.UUID)) *MockService_DeleteEntryMedia_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 int64
		if args[2] != nil {
			arg2 = args[2].(int64)
		}
		var arg3 uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_DeleteEntryMedia_Call) Return(err error) *MockService_DeleteEntryMedia_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_DeleteEntryMedia_Call) RunAndReturn(run func(ctx context.Context, entryID uuid.UUID, mediaID int64, userID uuid.UUID) error) *MockService_DeleteEntryMedia_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteJournal provides a mock function for the type MockService
func (_mock *MockService) DeleteJournal(ctx context.Context, id uuid.UUID, userID uuid.UUID) error {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for DeleteJournal")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_DeleteJournal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteJournal'
type MockService_DeleteJournal_Call struct {
	*mock.Call
}

// DeleteJournal is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userID uuid.UUID
func (_e *MockService_Expecter) DeleteJournal(ctx any, id any, userID any) *MockService_DeleteJournal_Call {
	return &MockService_DeleteJournal_Call{Call: _e.mock.On("DeleteJournal", ctx, id, userID)}
}

func (_c *MockService_DeleteJournal_Call) Run(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID)) *MockService_DeleteJournal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_DeleteJournal_Call) Return(err error) *MockService_DeleteJournal_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_DeleteJournal_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID) error) *MockService_DeleteJournal_Call {
	_c.Call.Return(run)
	return _c
}

// FollowJournal provides a mock function for the type MockService
func (_mock *MockService) FollowJournal(ctx context.Context, id uuid.UUID, userID uuid.UUID) error {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for FollowJournal")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_FollowJournal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FollowJournal'
type MockService_FollowJournal_Call struct {
	*mock.Call
}

// FollowJournal is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userID uuid.UUID
func (_e *MockService_Expecter) FollowJournal(ctx any, id any, userID any) *MockService_FollowJournal_Call {
	return &MockService_FollowJournal_Call{Call: _e.mock.On("FollowJournal", ctx, id, userID)}
}

func (_c *MockService_FollowJournal_Call) Run(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID)) *MockService_FollowJournal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_FollowJournal_Call) Return(err error) *MockService_FollowJournal_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_FollowJournal_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID) error) *MockService_FollowJournal_Call {
	_c.Call.Return(run)
	return _c
}

// GetEntry provides a mock function for the type MockService
func (_mock *MockService) GetEntry(ctx context.Context, journalID uuid.UUID, entryNumber int, viewerID uuid.UUID) (*dto.JournalEntryResponse, []dto.JournalCommentResponse, error) {
	ret := _mock.Called(ctx, journalID, entryNumber, viewerID)

	if len(ret) == 0 {
		panic("no return value specified for GetEntry")
	}

	var r0 *dto.JournalEntryResponse
	var r1 []dto.JournalCommentResponse
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, uuid.UUID) (*dto.JournalEntryResponse, []dto.JournalCommentResponse, error)); ok {
		return returnFunc(ctx, journalID, entryNumber, viewerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, int, uuid.UUID) *dto.JournalEntryResponse); ok {
		r0 = returnFunc(ctx, journalID, entryNumber, viewerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.JournalEntryResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, int, uuid.UUID) []dto.JournalCommentResponse); ok {
		r1 = returnFunc(ctx, journalID, entryNumber, viewerID)
	} else {
		if ret.Get(1) != nil {
			r1 = ret.Get(1).([]dto.JournalCommentResponse)
		}
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, uuid.UUID, int, uuid.UUID) error); ok {
		r2 = returnFunc(ctx, journalID, entryNumber, viewerID)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockService_GetEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetEntry'
type MockService_GetEntry_Call struct {
	*mock.Call
}

// GetEntry is a helper method to define mock.On call
//   - ctx context.Context
//   - journalID uuid.UUID
//   - entryNumber int
//   - viewerID uuid.UUID
func (_e *MockService_Expecter) GetEntry(ctx any, journalID any, entryNumber any, viewerID any) *MockService_GetEntry_Call {
	return &MockService_GetEntry_Call{Call: _e.mock.On("GetEntry", ctx, journalID, entryNumber, viewerID)}
}

func (_c *MockService_GetEntry_Call) Run(run func(ctx context.Context, journalID uuid.UUID, entryNumber int, viewerID uuid.UUID)) *MockService_GetEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 int
		if args[2] != nil {
			arg2 = args[2].(int)
		}
		var arg3 uuid.UUID
		if args[3] != nil {
			arg3 = args[3].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_GetEntry_Call) Return(journalEntryResponse *dto.JournalEntryResponse, journalCommentResponses []dto.JournalCommentResponse, err error) *MockService_GetEntry_Call {
	_c.Call.Return(journalEntryResponse, journalCommentResponses, err)
	return _c
}

func (_c *MockService_GetEntry_Call) RunAndReturn(run func(ctx context.Context, journalID uuid.UUID, entryNumber int, viewerID uuid.UUID) (*dto.JournalEntryResponse, []dto.JournalCommentResponse, error)) *MockService_GetEntry_Call {
	_c.Call.Return(run)
	return _c
}

// GetJournalDetail provides a mock function for the type MockService
func (_mock *MockService) GetJournalDetail(ctx context.Context, id uuid.UUID, viewerID uuid.UUID) (*dto.JournalDetailResponse, error) {
	ret := _mock.Called(ctx, id, viewerID)

	if len(ret) == 0 {
		panic("no return value specified for GetJournalDetail")
	}

	var r0 *dto.JournalDetailResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) (*dto.JournalDetailResponse, error)); ok {
		return returnFunc(ctx, id, viewerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) *dto.JournalDetailResponse); ok {
		r0 = returnFunc(ctx, id, viewerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.JournalDetailResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, id, viewerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_GetJournalDetail_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetJournalDetail'
type MockService_GetJournalDetail_Call struct {
	*mock.Call
}

// GetJournalDetail is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - viewerID uuid.UUID
func (_e *MockService_Expecter) GetJournalDetail(ctx any, id any, viewerID any) *MockService_GetJournalDetail_Call {
	return &MockService_GetJournalDetail_Call{Call: _e.mock.On("GetJournalDetail", ctx, id, viewerID)}
}

func (_c *MockService_GetJournalDetail_Call) Run(run func(ctx context.Context, id uuid.UUID, viewerID uuid.UUID)) *MockService_GetJournalDetail_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_GetJournalDetail_Call) Return(journalDetailResponse *dto.JournalDetailResponse, err error) *MockService_GetJournalDetail_Call {
	_c.Call.Return(journalDetailResponse, err)
	return _c
}

func (_c *MockService_GetJournalDetail_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, viewerID uuid.UUID) (*dto.JournalDetailResponse, error)) *MockService_GetJournalDetail_Call {
	_c.Call.Return(run)
	return _c
}

// LikeComment provides a mock function for the type MockService
func (_mock *MockService) LikeComment(ctx context.Context, id uuid.UUID, userID uuid.UUID) error {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for LikeComment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_LikeComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LikeComment'
type MockService_LikeComment_Call struct {
	*mock.Call
}

// LikeComment is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userID uuid.UUID
func (_e *MockService_Expecter) LikeComment(ctx any, id any, userID any) *MockService_LikeComment_Call {
	return &MockService_LikeComment_Call{Call: _e.mock.On("LikeComment", ctx, id, userID)}
}

func (_c *MockService_LikeComment_Call) Run(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID)) *MockService_LikeComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_LikeComment_Call) Return(err error) *MockService_LikeComment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_LikeComment_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID) error) *MockService_LikeComment_Call {
	_c.Call.Return(run)
	return _c
}

// ListFollowedByUser provides a mock function for the type MockService
func (_mock *MockService) ListFollowedByUser(ctx context.Context, followerID uuid.UUID, viewerID uuid.UUID, page bounds.Page) (*dto.JournalListResponse, error) {
	ret := _mock.Called(ctx, followerID, viewerID, page)

	if len(ret) == 0 {
		panic("no return value specified for ListFollowedByUser")
	}

	var r0 *dto.JournalListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, bounds.Page) (*dto.JournalListResponse, error)); ok {
		return returnFunc(ctx, followerID, viewerID, page)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, bounds.Page) *dto.JournalListResponse); ok {
		r0 = returnFunc(ctx, followerID, viewerID, page)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.JournalListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, bounds.Page) error); ok {
		r1 = returnFunc(ctx, followerID, viewerID, page)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ListFollowedByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListFollowedByUser'
type MockService_ListFollowedByUser_Call struct {
	*mock.Call
}

// ListFollowedByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - followerID uuid.UUID
//   - viewerID uuid.UUID
//   - page bounds.Page
func (_e *MockService_Expecter) ListFollowedByUser(ctx any, followerID any, viewerID any, page any) *MockService_ListFollowedByUser_Call {
	return &MockService_ListFollowedByUser_Call{Call: _e.mock.On("ListFollowedByUser", ctx, followerID, viewerID, page)}
}

func (_c *MockService_ListFollowedByUser_Call) Run(run func(ctx context.Context, followerID uuid.UUID, viewerID uuid.UUID, page bounds.Page)) *MockService_ListFollowedByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 bounds.Page
		if args[3] != nil {
			arg3 = args[3].(bounds.Page)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_ListFollowedByUser_Call) Return(journalListResponse *dto.JournalListResponse, err error) *MockService_ListFollowedByUser_Call {
	_c.Call.Return(journalListResponse, err)
	return _c
}

func (_c *MockService_ListFollowedByUser_Call) RunAndReturn(run func(ctx context.Context, followerID uuid.UUID, viewerID uuid.UUID, page bounds.Page) (*dto.JournalListResponse, error)) *MockService_ListFollowedByUser_Call {
	_c.Call.Return(run)
	return _c
}

// ListJournals provides a mock function for the type MockService
func (_mock *MockService) ListJournals(ctx context.Context, p params.ListParams, viewerID uuid.UUID) (*dto.JournalListResponse, error) {
	ret := _mock.Called(ctx, p, viewerID)

	if len(ret) == 0 {
		panic("no return value specified for ListJournals")
	}

	var r0 *dto.JournalListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, params.ListParams, uuid.UUID) (*dto.JournalListResponse, error)); ok {
		return returnFunc(ctx, p, viewerID)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, params.ListParams, uuid.UUID) *dto.JournalListResponse); ok {
		r0 = returnFunc(ctx, p, viewerID)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.JournalListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, params.ListParams, uuid.UUID) error); ok {
		r1 = returnFunc(ctx, p, viewerID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ListJournals_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListJournals'
type MockService_ListJournals_Call struct {
	*mock.Call
}

// ListJournals is a helper method to define mock.On call
//   - ctx context.Context
//   - p params.ListParams
//   - viewerID uuid.UUID
func (_e *MockService_Expecter) ListJournals(ctx any, p any, viewerID any) *MockService_ListJournals_Call {
	return &MockService_ListJournals_Call{Call: _e.mock.On("ListJournals", ctx, p, viewerID)}
}

func (_c *MockService_ListJournals_Call) Run(run func(ctx context.Context, p params.ListParams, viewerID uuid.UUID)) *MockService_ListJournals_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 params.ListParams
		if args[1] != nil {
			arg1 = args[1].(params.ListParams)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_ListJournals_Call) Return(journalListResponse *dto.JournalListResponse, err error) *MockService_ListJournals_Call {
	_c.Call.Return(journalListResponse, err)
	return _c
}

func (_c *MockService_ListJournals_Call) RunAndReturn(run func(ctx context.Context, p params.ListParams, viewerID uuid.UUID) (*dto.JournalListResponse, error)) *MockService_ListJournals_Call {
	_c.Call.Return(run)
	return _c
}

// ListJournalsByUser provides a mock function for the type MockService
func (_mock *MockService) ListJournalsByUser(ctx context.Context, authorID uuid.UUID, viewerID uuid.UUID, limit int, offset int) (*dto.JournalListResponse, error) {
	ret := _mock.Called(ctx, authorID, viewerID, limit, offset)

	if len(ret) == 0 {
		panic("no return value specified for ListJournalsByUser")
	}

	var r0 *dto.JournalListResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, int, int) (*dto.JournalListResponse, error)); ok {
		return returnFunc(ctx, authorID, viewerID, limit, offset)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, int, int) *dto.JournalListResponse); ok {
		r0 = returnFunc(ctx, authorID, viewerID, limit, offset)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.JournalListResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, int, int) error); ok {
		r1 = returnFunc(ctx, authorID, viewerID, limit, offset)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_ListJournalsByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListJournalsByUser'
type MockService_ListJournalsByUser_Call struct {
	*mock.Call
}

// ListJournalsByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - authorID uuid.UUID
//   - viewerID uuid.UUID
//   - limit int
//   - offset int
func (_e *MockService_Expecter) ListJournalsByUser(ctx any, authorID any, viewerID any, limit any, offset any) *MockService_ListJournalsByUser_Call {
	return &MockService_ListJournalsByUser_Call{Call: _e.mock.On("ListJournalsByUser", ctx, authorID, viewerID, limit, offset)}
}

func (_c *MockService_ListJournalsByUser_Call) Run(run func(ctx context.Context, authorID uuid.UUID, viewerID uuid.UUID, limit int, offset int)) *MockService_ListJournalsByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 int
		if args[3] != nil {
			arg3 = args[3].(int)
		}
		var arg4 int
		if args[4] != nil {
			arg4 = args[4].(int)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
		)
	})
	return _c
}

func (_c *MockService_ListJournalsByUser_Call) Return(journalListResponse *dto.JournalListResponse, err error) *MockService_ListJournalsByUser_Call {
	_c.Call.Return(journalListResponse, err)
	return _c
}

func (_c *MockService_ListJournalsByUser_Call) RunAndReturn(run func(ctx context.Context, authorID uuid.UUID, viewerID uuid.UUID, limit int, offset int) (*dto.JournalListResponse, error)) *MockService_ListJournalsByUser_Call {
	_c.Call.Return(run)
	return _c
}

// SetJournalPaused provides a mock function for the type MockService
func (_mock *MockService) SetJournalPaused(ctx context.Context, id uuid.UUID, userID uuid.UUID, paused bool) error {
	ret := _mock.Called(ctx, id, userID, paused)

	if len(ret) == 0 {
		panic("no return value specified for SetJournalPaused")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, bool) error); ok {
		r0 = returnFunc(ctx, id, userID, paused)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_SetJournalPaused_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SetJournalPaused'
type MockService_SetJournalPaused_Call struct {
	*mock.Call
}

// SetJournalPaused is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userID uuid.UUID
//   - paused bool
func (_e *MockService_Expecter) SetJournalPaused(ctx any, id any, userID any, paused any) *MockService_SetJournalPaused_Call {
	return &MockService_SetJournalPaused_Call{Call: _e.mock.On("SetJournalPaused", ctx, id, userID, paused)}
}

func (_c *MockService_SetJournalPaused_Call) Run(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID, paused bool)) *MockService_SetJournalPaused_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 bool
		if args[3] != nil {
			arg3 = args[3].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_SetJournalPaused_Call) Return(err error) *MockService_SetJournalPaused_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_SetJournalPaused_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID, paused bool) error) *MockService_SetJournalPaused_Call {
	_c.Call.Return(run)
	return _c
}

// UnfollowJournal provides a mock function for the type MockService
func (_mock *MockService) UnfollowJournal(ctx context.Context, id uuid.UUID, userID uuid.UUID) error {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for UnfollowJournal")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_UnfollowJournal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnfollowJournal'
type MockService_UnfollowJournal_Call struct {
	*mock.Call
}

// UnfollowJournal is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userID uuid.UUID
func (_e *MockService_Expecter) UnfollowJournal(ctx any, id any, userID any) *MockService_UnfollowJournal_Call {
	return &MockService_UnfollowJournal_Call{Call: _e.mock.On("UnfollowJournal", ctx, id, userID)}
}

func (_c *MockService_UnfollowJournal_Call) Run(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID)) *MockService_UnfollowJournal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_UnfollowJournal_Call) Return(err error) *MockService_UnfollowJournal_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_UnfollowJournal_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID) error) *MockService_UnfollowJournal_Call {
	_c.Call.Return(run)
	return _c
}

// UnlikeComment provides a mock function for the type MockService
func (_mock *MockService) UnlikeComment(ctx context.Context, id uuid.UUID, userID uuid.UUID) error {
	ret := _mock.Called(ctx, id, userID)

	if len(ret) == 0 {
		panic("no return value specified for UnlikeComment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID) error); ok {
		r0 = returnFunc(ctx, id, userID)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_UnlikeComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnlikeComment'
type MockService_UnlikeComment_Call struct {
	*mock.Call
}

// UnlikeComment is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userID uuid.UUID
func (_e *MockService_Expecter) UnlikeComment(ctx any, id any, userID any) *MockService_UnlikeComment_Call {
	return &MockService_UnlikeComment_Call{Call: _e.mock.On("UnlikeComment", ctx, id, userID)}
}

func (_c *MockService_UnlikeComment_Call) Run(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID)) *MockService_UnlikeComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *MockService_UnlikeComment_Call) Return(err error) *MockService_UnlikeComment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_UnlikeComment_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID) error) *MockService_UnlikeComment_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateComment provides a mock function for the type MockService
func (_mock *MockService) UpdateComment(ctx context.Context, id uuid.UUID, userID uuid.UUID, body string) error {
	ret := _mock.Called(ctx, id, userID, body)

	if len(ret) == 0 {
		panic("no return value specified for UpdateComment")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string) error); ok {
		r0 = returnFunc(ctx, id, userID, body)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_UpdateComment_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateComment'
type MockService_UpdateComment_Call struct {
	*mock.Call
}

// UpdateComment is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userID uuid.UUID
//   - body string
func (_e *MockService_Expecter) UpdateComment(ctx any, id any, userID any, body any) *MockService_UpdateComment_Call {
	return &MockService_UpdateComment_Call{Call: _e.mock.On("UpdateComment", ctx, id, userID, body)}
}

func (_c *MockService_UpdateComment_Call) Run(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID, body string)) *MockService_UpdateComment_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_UpdateComment_Call) Return(err error) *MockService_UpdateComment_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_UpdateComment_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID, body string) error) *MockService_UpdateComment_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateEntry provides a mock function for the type MockService
func (_mock *MockService) UpdateEntry(ctx context.Context, entryID uuid.UUID, userID uuid.UUID, req dto.UpdateJournalEntryRequest) error {
	ret := _mock.Called(ctx, entryID, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateEntry")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, dto.UpdateJournalEntryRequest) error); ok {
		r0 = returnFunc(ctx, entryID, userID, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_UpdateEntry_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateEntry'
type MockService_UpdateEntry_Call struct {
	*mock.Call
}

// UpdateEntry is a helper method to define mock.On call
//   - ctx context.Context
//   - entryID uuid.UUID
//   - userID uuid.UUID
//   - req dto.UpdateJournalEntryRequest
func (_e *MockService_Expecter) UpdateEntry(ctx any, entryID any, userID any, req any) *MockService_UpdateEntry_Call {
	return &MockService_UpdateEntry_Call{Call: _e.mock.On("UpdateEntry", ctx, entryID, userID, req)}
}

func (_c *MockService_UpdateEntry_Call) Run(run func(ctx context.Context, entryID uuid.UUID, userID uuid.UUID, req dto.UpdateJournalEntryRequest)) *MockService_UpdateEntry_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 dto.UpdateJournalEntryRequest
		if args[3] != nil {
			arg3 = args[3].(dto.UpdateJournalEntryRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_UpdateEntry_Call) Return(err error) *MockService_UpdateEntry_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_UpdateEntry_Call) RunAndReturn(run func(ctx context.Context, entryID uuid.UUID, userID uuid.UUID, req dto.UpdateJournalEntryRequest) error) *MockService_UpdateEntry_Call {
	_c.Call.Return(run)
	return _c
}

// UpdateJournal provides a mock function for the type MockService
func (_mock *MockService) UpdateJournal(ctx context.Context, id uuid.UUID, userID uuid.UUID, req dto.CreateJournalRequest) error {
	ret := _mock.Called(ctx, id, userID, req)

	if len(ret) == 0 {
		panic("no return value specified for UpdateJournal")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, dto.CreateJournalRequest) error); ok {
		r0 = returnFunc(ctx, id, userID, req)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockService_UpdateJournal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UpdateJournal'
type MockService_UpdateJournal_Call struct {
	*mock.Call
}

// UpdateJournal is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - userID uuid.UUID
//   - req dto.CreateJournalRequest
func (_e *MockService_Expecter) UpdateJournal(ctx any, id any, userID any, req any) *MockService_UpdateJournal_Call {
	return &MockService_UpdateJournal_Call{Call: _e.mock.On("UpdateJournal", ctx, id, userID, req)}
}

func (_c *MockService_UpdateJournal_Call) Run(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID, req dto.CreateJournalRequest)) *MockService_UpdateJournal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 dto.CreateJournalRequest
		if args[3] != nil {
			arg3 = args[3].(dto.CreateJournalRequest)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
		)
	})
	return _c
}

func (_c *MockService_UpdateJournal_Call) Return(err error) *MockService_UpdateJournal_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockService_UpdateJournal_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, userID uuid.UUID, req dto.CreateJournalRequest) error) *MockService_UpdateJournal_Call {
	_c.Call.Return(run)
	return _c
}

// UploadCommentMedia provides a mock function for the type MockService
func (_mock *MockService) UploadCommentMedia(ctx context.Context, commentID uuid.UUID, userID uuid.UUID, contentType string, filename string, fileSize int64, reader io.Reader, isSpoiler bool) (*dto.PostMediaResponse, error) {
	ret := _mock.Called(ctx, commentID, userID, contentType, filename, fileSize, reader, isSpoiler)

	if len(ret) == 0 {
		panic("no return value specified for UploadCommentMedia")
	}

	var r0 *dto.PostMediaResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, string, int64, io.Reader, bool) (*dto.PostMediaResponse, error)); ok {
		return returnFunc(ctx, commentID, userID, contentType, filename, fileSize, reader, isSpoiler)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, string, int64, io.Reader, bool) *dto.PostMediaResponse); ok {
		r0 = returnFunc(ctx, commentID, userID, contentType, filename, fileSize, reader, isSpoiler)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.PostMediaResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, string, string, int64, io.Reader, bool) error); ok {
		r1 = returnFunc(ctx, commentID, userID, contentType, filename, fileSize, reader, isSpoiler)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_UploadCommentMedia_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadCommentMedia'
type MockService_UploadCommentMedia_Call struct {
	*mock.Call
}

// UploadCommentMedia is a helper method to define mock.On call
//   - ctx context.Context
//   - commentID uuid.UUID
//   - userID uuid.UUID
//   - contentType string
//   - filename string
//   - fileSize int64
//   - reader io.Reader
//   - isSpoiler bool
func (_e *MockService_Expecter) UploadCommentMedia(ctx any, commentID any, userID any, contentType any, filename any, fileSize any, reader any, isSpoiler any) *MockService_UploadCommentMedia_Call {
	return &MockService_UploadCommentMedia_Call{Call: _e.mock.On("UploadCommentMedia", ctx, commentID, userID, contentType, filename, fileSize, reader, isSpoiler)}
}

func (_c *MockService_UploadCommentMedia_Call) Run(run func(ctx context.Context, commentID uuid.UUID, userID uuid.UUID, contentType string, filename string, fileSize int64, reader io.Reader, isSpoiler bool)) *MockService_UploadCommentMedia_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 int64
		if args[5] != nil {
			arg5 = args[5].(int64)
		}
		var arg6 io.Reader
		if args[6] != nil {
			arg6 = args[6].(io.Reader)
		}
		var arg7 bool
		if args[7] != nil {
			arg7 = args[7].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
			arg7,
		)
	})
	return _c
}

func (_c *MockService_UploadCommentMedia_Call) Return(postMediaResponse *dto.PostMediaResponse, err error) *MockService_UploadCommentMedia_Call {
	_c.Call.Return(postMediaResponse, err)
	return _c
}

func (_c *MockService_UploadCommentMedia_Call) RunAndReturn(run func(ctx context.Context, commentID uuid.UUID, userID uuid.UUID, contentType string, filename string, fileSize int64, reader io.Reader, isSpoiler bool) (*dto.PostMediaResponse, error)) *MockService_UploadCommentMedia_Call {
	_c.Call.Return(run)
	return _c
}

// UploadEntryMedia provides a mock function for the type MockService
func (_mock *MockService) UploadEntryMedia(ctx context.Context, entryID uuid.UUID, userID uuid.UUID, contentType string, filename string, fileSize int64, reader io.Reader, isSpoiler bool) (*dto.PostMediaResponse, error) {
	ret := _mock.Called(ctx, entryID, userID, contentType, filename, fileSize, reader, isSpoiler)

	if len(ret) == 0 {
		panic("no return value specified for UploadEntryMedia")
	}

	var r0 *dto.PostMediaResponse
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, string, int64, io.Reader, bool) (*dto.PostMediaResponse, error)); ok {
		return returnFunc(ctx, entryID, userID, contentType, filename, fileSize, reader, isSpoiler)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, uuid.UUID, string, string, int64, io.Reader, bool) *dto.PostMediaResponse); ok {
		r0 = returnFunc(ctx, entryID, userID, contentType, filename, fileSize, reader, isSpoiler)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*dto.PostMediaResponse)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, uuid.UUID, string, string, int64, io.Reader, bool) error); ok {
		r1 = returnFunc(ctx, entryID, userID, contentType, filename, fileSize, reader, isSpoiler)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockService_UploadEntryMedia_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UploadEntryMedia'
type MockService_UploadEntryMedia_Call struct {
	*mock.Call
}

// UploadEntryMedia is a helper method to define mock.On call
//   - ctx context.Context
//   - entryID uuid.UUID
//   - userID uuid.UUID
//   - contentType string
//   - filename string
//   - fileSize int64
//   - reader io.Reader
//   - isSpoiler bool
func (_e *MockService_Expecter) UploadEntryMedia(ctx any, entryID any, userID any, contentType any, filename any, fileSize any, reader any, isSpoiler any) *MockService_UploadEntryMedia_Call {
	return &MockService_UploadEntryMedia_Call{Call: _e.mock.On("UploadEntryMedia", ctx, entryID, userID, contentType, filename, fileSize, reader, isSpoiler)}
}

func (_c *MockService_UploadEntryMedia_Call) Run(run func(ctx context.Context, entryID uuid.UUID, userID uuid.UUID, contentType string, filename string, fileSize int64, reader io.Reader, isSpoiler bool)) *MockService_UploadEntryMedia_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 uuid.UUID
		if args[2] != nil {
			arg2 = args[2].(uuid.UUID)
		}
		var arg3 string
		if args[3] != nil {
			arg3 = args[3].(string)
		}
		var arg4 string
		if args[4] != nil {
			arg4 = args[4].(string)
		}
		var arg5 int64
		if args[5] != nil {
			arg5 = args[5].(int64)
		}
		var arg6 io.Reader
		if args[6] != nil {
			arg6 = args[6].(io.Reader)
		}
		var arg7 bool
		if args[7] != nil {
			arg7 = args[7].(bool)
		}
		run(
			arg0,
			arg1,
			arg2,
			arg3,
			arg4,
			arg5,
			arg6,
			arg7,
		)
	})
	return _c
}

func (_c *MockService_UploadEntryMedia_Call) Return(postMediaResponse *dto.PostMediaResponse, err error) *MockService_UploadEntryMedia_Call {
	_c.Call.Return(postMediaResponse, err)
	return _c
}

func (_c *MockService_UploadEntryMedia_Call) RunAndReturn(run func(ctx context.Context, entryID uuid.UUID, userID uuid.UUID, contentType string, filename string, fileSize int64, reader io.Reader, isSpoiler bool) (*dto.PostMediaResponse, error)) *MockService_UploadEntryMedia_Call {
	_c.Call.Return(run)
	return _c
}
