// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package dao

import (
	"context"
	"database/sql"
	"umineko_city_of_books/internal/model"
	"umineko_city_of_books/internal/model/spec"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockChatbotBasePromptDAO creates a new instance of MockChatbotBasePromptDAO. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockChatbotBasePromptDAO(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockChatbotBasePromptDAO {
	mock := &MockChatbotBasePromptDAO{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockChatbotBasePromptDAO is an autogenerated mock type for the ChatbotBasePromptDAO type
type MockChatbotBasePromptDAO struct {
	mock.Mock
}

type MockChatbotBasePromptDAO_Expecter struct {
	mock *mock.Mock
}

func (_m *MockChatbotBasePromptDAO) EXPECT() *MockChatbotBasePromptDAO_Expecter {
	return &MockChatbotBasePromptDAO_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockChatbotBasePromptDAO
func (_mock *MockChatbotBasePromptDAO) Create(ctx context.Context, s spec.NewChatbotBasePrompt, tx ...*sql.Tx) (*model.ChatbotBasePrompt, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, s, tx)
	} else {
		tmpRet = _mock.Called(ctx, s)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.ChatbotBasePrompt
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.NewChatbotBasePrompt, ...*sql.Tx) (*model.ChatbotBasePrompt, error)); ok {
		return returnFunc(ctx, s, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.NewChatbotBasePrompt, ...*sql.Tx) *model.ChatbotBasePrompt); ok {
		r0 = returnFunc(ctx, s, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ChatbotBasePrompt)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, spec.NewChatbotBasePrompt, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, s, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatbotBasePromptDAO_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockChatbotBasePromptDAO_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - s spec.NewChatbotBasePrompt
//   - tx ...*sql.Tx
func (_e *MockChatbotBasePromptDAO_Expecter) Create(ctx any, s any, tx ...any) *MockChatbotBasePromptDAO_Create_Call {
	return &MockChatbotBasePromptDAO_Create_Call{Call: _e.mock.On("Create",
		append([]any{ctx, s}, tx...)...)}
}

func (_c *MockChatbotBasePromptDAO_Create_Call) Run(run func(ctx context.Context, s spec.NewChatbotBasePrompt, tx ...*sql.Tx)) *MockChatbotBasePromptDAO_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.NewChatbotBasePrompt
		if args[1] != nil {
			arg1 = args[1].(spec.NewChatbotBasePrompt)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockChatbotBasePromptDAO_Create_Call) Return(chatbotBasePrompt *model.ChatbotBasePrompt, err error) *MockChatbotBasePromptDAO_Create_Call {
	_c.Call.Return(chatbotBasePrompt, err)
	return _c
}

func (_c *MockChatbotBasePromptDAO_Create_Call) RunAndReturn(run func(ctx context.Context, s spec.NewChatbotBasePrompt, tx ...*sql.Tx) (*model.ChatbotBasePrompt, error)) *MockChatbotBasePromptDAO_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockChatbotBasePromptDAO
func (_mock *MockChatbotBasePromptDAO) Delete(ctx context.Context, id uuid.UUID, tx ...*sql.Tx) error {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, id, tx)
	} else {
		tmpRet = _mock.Called(ctx, id)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...*sql.Tx) error); ok {
		r0 = returnFunc(ctx, id, tx...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockChatbotBasePromptDAO_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockChatbotBasePromptDAO_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - tx ...*sql.Tx
func (_e *MockChatbotBasePromptDAO_Expecter) Delete(ctx any, id any, tx ...any) *MockChatbotBasePromptDAO_Delete_Call {
	return &MockChatbotBasePromptDAO_Delete_Call{Call: _e.mock.On("Delete",
		append([]any{ctx, id}, tx...)...)}
}

func (_c *MockChatbotBasePromptDAO_Delete_Call) Run(run func(ctx context.Context, id uuid.UUID, tx ...*sql.Tx)) *MockChatbotBasePromptDAO_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockChatbotBasePromptDAO_Delete_Call) Return(err error) *MockChatbotBasePromptDAO_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockChatbotBasePromptDAO_Delete_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, tx ...*sql.Tx) error) *MockChatbotBasePromptDAO_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockChatbotBasePromptDAO
func (_mock *MockChatbotBasePromptDAO) GetByID(ctx context.Context, id uuid.UUID, tx ...*sql.Tx) (*model.ChatbotBasePrompt, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, id, tx)
	} else {
		tmpRet = _mock.Called(ctx, id)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.ChatbotBasePrompt
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...*sql.Tx) (*model.ChatbotBasePrompt, error)); ok {
		return returnFunc(ctx, id, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...*sql.Tx) *model.ChatbotBasePrompt); ok {
		r0 = returnFunc(ctx, id, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ChatbotBasePrompt)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, id, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatbotBasePromptDAO_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockChatbotBasePromptDAO_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - id uuid.UUID
//   - tx ...*sql.Tx
func (_e *MockChatbotBasePromptDAO_Expecter) GetByID(ctx any, id any, tx ...any) *MockChatbotBasePromptDAO_GetByID_Call {
	return &MockChatbotBasePromptDAO_GetByID_Call{Call: _e.mock.On("GetByID",
		append([]any{ctx, id}, tx...)...)}
}

func (_c *MockChatbotBasePromptDAO_GetByID_Call) Run(run func(ctx context.Context, id uuid.UUID, tx ...*sql.Tx)) *MockChatbotBasePromptDAO_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockChatbotBasePromptDAO_GetByID_Call) Return(chatbotBasePrompt *model.ChatbotBasePrompt, err error) *MockChatbotBasePromptDAO_GetByID_Call {
	_c.Call.Return(chatbotBasePrompt, err)
	return _c
}

func (_c *MockChatbotBasePromptDAO_GetByID_Call) RunAndReturn(run func(ctx context.Context, id uuid.UUID, tx ...*sql.Tx) (*model.ChatbotBasePrompt, error)) *MockChatbotBasePromptDAO_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockChatbotBasePromptDAO
func (_mock *MockChatbotBasePromptDAO) List(ctx context.Context, tx ...*sql.Tx) ([]model.ChatbotBasePrompt, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, tx)
	} else {
		tmpRet = _mock.Called(ctx)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.ChatbotBasePrompt
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...*sql.Tx) ([]model.ChatbotBasePrompt, error)); ok {
		return returnFunc(ctx, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, ...*sql.Tx) []model.ChatbotBasePrompt); ok {
		r0 = returnFunc(ctx, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.ChatbotBasePrompt)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatbotBasePromptDAO_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockChatbotBasePromptDAO_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - tx ...*sql.Tx
func (_e *MockChatbotBasePromptDAO_Expecter) List(ctx any, tx ...any) *MockChatbotBasePromptDAO_List_Call {
	return &MockChatbotBasePromptDAO_List_Call{Call: _e.mock.On("List",
		append([]any{ctx}, tx...)...)}
}

func (_c *MockChatbotBasePromptDAO_List_Call) Run(run func(ctx context.Context, tx ...*sql.Tx)) *MockChatbotBasePromptDAO_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 1 {
			variadicArgs = args[1].([]*sql.Tx)
		}
		arg1 = variadicArgs
		run(
			arg0,
			arg1...,
		)
	})
	return _c
}

func (_c *MockChatbotBasePromptDAO_List_Call) Return(chatbotBasePrompts []model.ChatbotBasePrompt, err error) *MockChatbotBasePromptDAO_List_Call {
	_c.Call.Return(chatbotBasePrompts, err)
	return _c
}

func (_c *MockChatbotBasePromptDAO_List_Call) RunAndReturn(run func(ctx context.Context, tx ...*sql.Tx) ([]model.ChatbotBasePrompt, error)) *MockChatbotBasePromptDAO_List_Call {
	_c.Call.Return(run)
	return _c
}

// Update provides a mock function for the type MockChatbotBasePromptDAO
func (_mock *MockChatbotBasePromptDAO) Update(ctx context.Context, s spec.ChatbotBasePromptUpdate, tx ...*sql.Tx) (*model.ChatbotBasePrompt, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, s, tx)
	} else {
		tmpRet = _mock.Called(ctx, s)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Update")
	}

	var r0 *model.ChatbotBasePrompt
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.ChatbotBasePromptUpdate, ...*sql.Tx) (*model.ChatbotBasePrompt, error)); ok {
		return returnFunc(ctx, s, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.ChatbotBasePromptUpdate, ...*sql.Tx) *model.ChatbotBasePrompt); ok {
		r0 = returnFunc(ctx, s, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.ChatbotBasePrompt)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, spec.ChatbotBasePromptUpdate, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, s, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockChatbotBasePromptDAO_Update_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Update'
type MockChatbotBasePromptDAO_Update_Call struct {
	*mock.Call
}

// Update is a helper method to define mock.On call
//   - ctx context.Context
//   - s spec.ChatbotBasePromptUpdate
//   - tx ...*sql.Tx
func (_e *MockChatbotBasePromptDAO_Expecter) Update(ctx any, s any, tx ...any) *MockChatbotBasePromptDAO_Update_Call {
	return &MockChatbotBasePromptDAO_Update_Call{Call: _e.mock.On("Update",
		append([]any{ctx, s}, tx...)...)}
}

func (_c *MockChatbotBasePromptDAO_Update_Call) Run(run func(ctx context.Context, s spec.ChatbotBasePromptUpdate, tx ...*sql.Tx)) *MockChatbotBasePromptDAO_Update_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.ChatbotBasePromptUpdate
		if args[1] != nil {
			arg1 = args[1].(spec.ChatbotBasePromptUpdate)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockChatbotBasePromptDAO_Update_Call) Return(chatbotBasePrompt *model.ChatbotBasePrompt, err error) *MockChatbotBasePromptDAO_Update_Call {
	_c.Call.Return(chatbotBasePrompt, err)
	return _c
}

func (_c *MockChatbotBasePromptDAO_Update_Call) RunAndReturn(run func(ctx context.Context, s spec.ChatbotBasePromptUpdate, tx ...*sql.Tx) (*model.ChatbotBasePrompt, error)) *MockChatbotBasePromptDAO_Update_Call {
	_c.Call.Return(run)
	return _c
}
