// Code generated by internal/dao/queries/expand; DO NOT EDIT.
// template: internal/dao/queries/templates/comments_bind.go.tmpl
// entity: Fanfic

package dao

import (
	"context"
	"database/sql"

	"github.com/google/uuid"

	"umineko_city_of_books/internal/dao/sqlcgen"
	"umineko_city_of_books/internal/model"
	"umineko_city_of_books/internal/model/spec"
)

type (
	fanficCommentQuerier struct{}
)

func (fanficCommentQuerier) Create(ctx context.Context, q *sqlcgen.Queries, s spec.NewComment[uuid.UUID]) (*model.CommentRow, error) {
	row, err := q.CreateFanficComment(ctx, sqlcgen.CreateFanficCommentParams{
		FanficID: s.TargetID,
		ParentID: s.ParentID,
		UserID:   s.UserID,
		Body:     s.Body,
	})
	if err != nil {
		return nil, err
	}

	return new(commentRowFromCreate(commentCreateRow(row))), nil
}

func (fanficCommentQuerier) Update(ctx context.Context, q *sqlcgen.Queries, s spec.CommentUpdate) (int64, error) {
	return q.UpdateFanficComment(ctx, sqlcgen.UpdateFanficCommentParams{
		Body:    s.Body,
		ID:      s.CommentID,
		Column3: s.AsAdmin,
		UserID:  s.UserID,
	})
}

func (fanficCommentQuerier) Delete(ctx context.Context, q *sqlcgen.Queries, s spec.CommentDeletion) (int64, error) {
	return q.DeleteFanficComment(ctx, sqlcgen.DeleteFanficCommentParams{
		ID:      s.CommentID,
		Column2: s.AsAdmin,
		UserID:  s.UserID,
	})
}

func (fanficCommentQuerier) Count(ctx context.Context, q *sqlcgen.Queries, target uuid.UUID, exclude []uuid.UUID) (int64, error) {
	return q.CountFanficComments(ctx, sqlcgen.CountFanficCommentsParams{
		FanficID: target,
		Column2:  joinUUIDs(exclude),
	})
}

func (fanficCommentQuerier) List(ctx context.Context, q *sqlcgen.Queries, s spec.CommentQuery[uuid.UUID]) ([]model.CommentRow, error) {
	rows, err := q.ListFanficComments(ctx, sqlcgen.ListFanficCommentsParams{
		UserID:   s.ViewerID,
		FanficID: s.TargetID,
		Column3:  joinUUIDs(s.ExcludeUserIDs),
		Limit:    int32(s.Limit),
		Offset:   int32(s.Offset),
	})
	if err != nil {
		return nil, err
	}

	out := make([]model.CommentRow, 0, len(rows))
	for _, row := range rows {
		out = append(out, commentRowFromList(commentListRow(row)))
	}

	return out, nil
}

func (fanficCommentQuerier) ByID(ctx context.Context, q *sqlcgen.Queries, id uuid.UUID) (*model.CommentRow, error) {
	row, err := q.GetFanficCommentByID(ctx, id)
	if err != nil {
		return nil, err
	}

	return new(commentRowFromCreate(commentCreateRow(row))), nil
}

func (fanficCommentQuerier) EntityID(ctx context.Context, q *sqlcgen.Queries, id uuid.UUID) (uuid.UUID, error) {
	return q.GetFanficCommentEntityID(ctx, id)
}

func (fanficCommentQuerier) AuthorID(ctx context.Context, q *sqlcgen.Queries, id uuid.UUID) (uuid.UUID, error) {
	return q.GetFanficCommentAuthorID(ctx, id)
}

func (fanficCommentQuerier) Like(ctx context.Context, q *sqlcgen.Queries, s spec.CommentLike) error {
	return q.LikeFanficComment(ctx, sqlcgen.LikeFanficCommentParams{UserID: s.UserID, CommentID: s.CommentID})
}

func (fanficCommentQuerier) Unlike(ctx context.Context, q *sqlcgen.Queries, s spec.CommentLike) error {
	return q.UnlikeFanficComment(ctx, sqlcgen.UnlikeFanficCommentParams{UserID: s.UserID, CommentID: s.CommentID})
}

func (fanficCommentQuerier) AddMedia(ctx context.Context, q *sqlcgen.Queries, s spec.NewMedia) (int64, error) {
	return q.AddFanficCommentMedia(ctx, sqlcgen.AddFanficCommentMediaParams{
		CommentID:    s.TargetID,
		MediaUrl:     s.MediaURL,
		MediaType:    s.MediaType,
		ThumbnailUrl: s.ThumbnailURL,
		Filename:     sql.NullString{String: s.Filename, Valid: true},
		Column6:      int32(s.SortOrder),
		IsSpoiler:    s.IsSpoiler,
	})
}

func (fanficCommentQuerier) Media(ctx context.Context, q *sqlcgen.Queries, commentID uuid.UUID) ([]model.PostMediaRow, error) {
	rows, err := q.GetFanficCommentMedia(ctx, commentID)
	if err != nil {
		return nil, err
	}

	out := make([]model.PostMediaRow, 0, len(rows))
	for _, row := range rows {
		out = append(out, mediaRowFromComment(commentMediaRow(row)))
	}

	return out, nil
}

func (fanficCommentQuerier) MediaBatch(ctx context.Context, q *sqlcgen.Queries, ids []uuid.UUID) (map[uuid.UUID][]model.PostMediaRow, error) {
	rows, err := q.GetFanficCommentMediaBatch(ctx, joinUUIDs(ids))
	if err != nil {
		return nil, err
	}

	out := make(map[uuid.UUID][]model.PostMediaRow)
	for _, row := range rows {
		out[row.CommentID] = append(out[row.CommentID], mediaRowFromComment(commentMediaRow(row)))
	}

	return out, nil
}

func (fanficCommentQuerier) SetMediaURL(ctx context.Context, q *sqlcgen.Queries, s spec.MediaURLUpdate) error {
	return q.UpdateFanficCommentMediaURL(ctx, sqlcgen.UpdateFanficCommentMediaURLParams{MediaUrl: s.URL, ID: s.ID})
}

func (fanficCommentQuerier) SetMediaThumbnail(ctx context.Context, q *sqlcgen.Queries, s spec.MediaURLUpdate) error {
	return q.UpdateFanficCommentMediaThumbnail(ctx, sqlcgen.UpdateFanficCommentMediaThumbnailParams{ThumbnailUrl: s.URL, ID: s.ID})
}

func (fanficCommentQuerier) Paths(ctx context.Context, q *sqlcgen.Queries, target uuid.UUID) ([]string, error) {
	rows, err := q.CollectFanficCommentMediaPaths(ctx, target)
	if err != nil {
		return nil, err
	}

	out := make([]mediaPathRow, 0, len(rows))
	for _, row := range rows {
		out = append(out, mediaPathRow(row))
	}

	return collectMediaPaths(out), nil
}

func (fanficCommentQuerier) SinglePaths(ctx context.Context, q *sqlcgen.Queries, commentID uuid.UUID) ([]string, error) {
	rows, err := q.CollectSingleFanficCommentMediaPaths(ctx, commentID)
	if err != nil {
		return nil, err
	}

	out := make([]mediaPathRow, 0, len(rows))
	for _, row := range rows {
		out = append(out, mediaPathRow(row))
	}

	return collectMediaPaths(out), nil
}
