// Code generated by internal/dao/queries/expand; DO NOT EDIT.
// template: internal/dao/queries/templates/comments_bind.go.tmpl
// entity: Announcement

package dao

import (
	"context"
	"database/sql"

	"github.com/google/uuid"

	"umineko_city_of_books/internal/dao/sqlcgen"
	"umineko_city_of_books/internal/model"
	"umineko_city_of_books/internal/model/spec"
)

type (
	announcementCommentQuerier struct{}
)

func (announcementCommentQuerier) Create(ctx context.Context, q *sqlcgen.Queries, s spec.NewComment[uuid.UUID]) (*model.CommentRow, error) {
	row, err := q.CreateAnnouncementComment(ctx, sqlcgen.CreateAnnouncementCommentParams{
		AnnouncementID: s.TargetID,
		ParentID:       s.ParentID,
		UserID:         s.UserID,
		Body:           s.Body,
	})
	if err != nil {
		return nil, err
	}

	return new(commentRowFromCreate(commentCreateRow(row))), nil
}

func (announcementCommentQuerier) Update(ctx context.Context, q *sqlcgen.Queries, s spec.CommentUpdate) (int64, error) {
	return q.UpdateAnnouncementComment(ctx, sqlcgen.UpdateAnnouncementCommentParams{
		Body:    s.Body,
		ID:      s.CommentID,
		Column3: s.AsAdmin,
		UserID:  s.UserID,
	})
}

func (announcementCommentQuerier) Delete(ctx context.Context, q *sqlcgen.Queries, s spec.CommentDeletion) (int64, error) {
	return q.DeleteAnnouncementComment(ctx, sqlcgen.DeleteAnnouncementCommentParams{
		ID:      s.CommentID,
		Column2: s.AsAdmin,
		UserID:  s.UserID,
	})
}

func (announcementCommentQuerier) Count(ctx context.Context, q *sqlcgen.Queries, target uuid.UUID, exclude []uuid.UUID) (int64, error) {
	return q.CountAnnouncementComments(ctx, sqlcgen.CountAnnouncementCommentsParams{
		AnnouncementID: target,
		Column2:        joinUUIDs(exclude),
	})
}

func (announcementCommentQuerier) List(ctx context.Context, q *sqlcgen.Queries, s spec.CommentQuery[uuid.UUID]) ([]model.CommentRow, error) {
	rows, err := q.ListAnnouncementComments(ctx, sqlcgen.ListAnnouncementCommentsParams{
		UserID:         s.ViewerID,
		AnnouncementID: s.TargetID,
		Column3:        joinUUIDs(s.ExcludeUserIDs),
		Limit:          int32(s.Limit),
		Offset:         int32(s.Offset),
	})
	if err != nil {
		return nil, err
	}

	out := make([]model.CommentRow, 0, len(rows))
	for _, row := range rows {
		out = append(out, commentRowFromList(commentListRow(row)))
	}

	return out, nil
}

func (announcementCommentQuerier) ByID(ctx context.Context, q *sqlcgen.Queries, id uuid.UUID) (*model.CommentRow, error) {
	row, err := q.GetAnnouncementCommentByID(ctx, id)
	if err != nil {
		return nil, err
	}

	return new(commentRowFromCreate(commentCreateRow(row))), nil
}

func (announcementCommentQuerier) EntityID(ctx context.Context, q *sqlcgen.Queries, id uuid.UUID) (uuid.UUID, error) {
	return q.GetAnnouncementCommentEntityID(ctx, id)
}

func (announcementCommentQuerier) AuthorID(ctx context.Context, q *sqlcgen.Queries, id uuid.UUID) (uuid.UUID, error) {
	return q.GetAnnouncementCommentAuthorID(ctx, id)
}

func (announcementCommentQuerier) Like(ctx context.Context, q *sqlcgen.Queries, s spec.CommentLike) error {
	return q.LikeAnnouncementComment(ctx, sqlcgen.LikeAnnouncementCommentParams{UserID: s.UserID, CommentID: s.CommentID})
}

func (announcementCommentQuerier) Unlike(ctx context.Context, q *sqlcgen.Queries, s spec.CommentLike) error {
	return q.UnlikeAnnouncementComment(ctx, sqlcgen.UnlikeAnnouncementCommentParams{UserID: s.UserID, CommentID: s.CommentID})
}

func (announcementCommentQuerier) AddMedia(ctx context.Context, q *sqlcgen.Queries, s spec.NewMedia) (int64, error) {
	return q.AddAnnouncementCommentMedia(ctx, sqlcgen.AddAnnouncementCommentMediaParams{
		CommentID:    s.TargetID,
		MediaUrl:     s.MediaURL,
		MediaType:    s.MediaType,
		ThumbnailUrl: s.ThumbnailURL,
		Filename:     sql.NullString{String: s.Filename, Valid: true},
		Column6:      int32(s.SortOrder),
		IsSpoiler:    s.IsSpoiler,
	})
}

func (announcementCommentQuerier) Media(ctx context.Context, q *sqlcgen.Queries, commentID uuid.UUID) ([]model.PostMediaRow, error) {
	rows, err := q.GetAnnouncementCommentMedia(ctx, commentID)
	if err != nil {
		return nil, err
	}

	out := make([]model.PostMediaRow, 0, len(rows))
	for _, row := range rows {
		out = append(out, mediaRowFromComment(commentMediaRow(row)))
	}

	return out, nil
}

func (announcementCommentQuerier) MediaBatch(ctx context.Context, q *sqlcgen.Queries, ids []uuid.UUID) (map[uuid.UUID][]model.PostMediaRow, error) {
	rows, err := q.GetAnnouncementCommentMediaBatch(ctx, joinUUIDs(ids))
	if err != nil {
		return nil, err
	}

	out := make(map[uuid.UUID][]model.PostMediaRow)
	for _, row := range rows {
		out[row.CommentID] = append(out[row.CommentID], mediaRowFromComment(commentMediaRow(row)))
	}

	return out, nil
}

func (announcementCommentQuerier) SetMediaURL(ctx context.Context, q *sqlcgen.Queries, s spec.MediaURLUpdate) error {
	return q.UpdateAnnouncementCommentMediaURL(ctx, sqlcgen.UpdateAnnouncementCommentMediaURLParams{MediaUrl: s.URL, ID: s.ID})
}

func (announcementCommentQuerier) SetMediaThumbnail(ctx context.Context, q *sqlcgen.Queries, s spec.MediaURLUpdate) error {
	return q.UpdateAnnouncementCommentMediaThumbnail(ctx, sqlcgen.UpdateAnnouncementCommentMediaThumbnailParams{ThumbnailUrl: s.URL, ID: s.ID})
}

func (announcementCommentQuerier) Paths(ctx context.Context, q *sqlcgen.Queries, target uuid.UUID) ([]string, error) {
	rows, err := q.CollectAnnouncementCommentMediaPaths(ctx, target)
	if err != nil {
		return nil, err
	}

	out := make([]mediaPathRow, 0, len(rows))
	for _, row := range rows {
		out = append(out, mediaPathRow(row))
	}

	return collectMediaPaths(out), nil
}

func (announcementCommentQuerier) SinglePaths(ctx context.Context, q *sqlcgen.Queries, commentID uuid.UUID) ([]string, error) {
	rows, err := q.CollectSingleAnnouncementCommentMediaPaths(ctx, commentID)
	if err != nil {
		return nil, err
	}

	out := make([]mediaPathRow, 0, len(rows))
	for _, row := range rows {
		out = append(out, mediaPathRow(row))
	}

	return collectMediaPaths(out), nil
}
