// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package dao

import (
	"context"
	"database/sql"
	"umineko_city_of_books/internal/model"
	"umineko_city_of_books/internal/model/spec"

	mock "github.com/stretchr/testify/mock"
)

// NewMockInviteDAO creates a new instance of MockInviteDAO. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInviteDAO(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInviteDAO {
	mock := &MockInviteDAO{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInviteDAO is an autogenerated mock type for the InviteDAO type
type MockInviteDAO struct {
	mock.Mock
}

type MockInviteDAO_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInviteDAO) EXPECT() *MockInviteDAO_Expecter {
	return &MockInviteDAO_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockInviteDAO
func (_mock *MockInviteDAO) Create(ctx context.Context, s spec.NewInvite, tx ...*sql.Tx) error {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, s, tx)
	} else {
		tmpRet = _mock.Called(ctx, s)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.NewInvite, ...*sql.Tx) error); ok {
		r0 = returnFunc(ctx, s, tx...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInviteDAO_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockInviteDAO_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - s spec.NewInvite
//   - tx ...*sql.Tx
func (_e *MockInviteDAO_Expecter) Create(ctx any, s any, tx ...any) *MockInviteDAO_Create_Call {
	return &MockInviteDAO_Create_Call{Call: _e.mock.On("Create",
		append([]any{ctx, s}, tx...)...)}
}

func (_c *MockInviteDAO_Create_Call) Run(run func(ctx context.Context, s spec.NewInvite, tx ...*sql.Tx)) *MockInviteDAO_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.NewInvite
		if args[1] != nil {
			arg1 = args[1].(spec.NewInvite)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockInviteDAO_Create_Call) Return(err error) *MockInviteDAO_Create_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInviteDAO_Create_Call) RunAndReturn(run func(ctx context.Context, s spec.NewInvite, tx ...*sql.Tx) error) *MockInviteDAO_Create_Call {
	_c.Call.Return(run)
	return _c
}

// Delete provides a mock function for the type MockInviteDAO
func (_mock *MockInviteDAO) Delete(ctx context.Context, code string, tx ...*sql.Tx) error {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, code, tx)
	} else {
		tmpRet = _mock.Called(ctx, code)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Delete")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...*sql.Tx) error); ok {
		r0 = returnFunc(ctx, code, tx...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInviteDAO_Delete_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Delete'
type MockInviteDAO_Delete_Call struct {
	*mock.Call
}

// Delete is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
//   - tx ...*sql.Tx
func (_e *MockInviteDAO_Expecter) Delete(ctx any, code any, tx ...any) *MockInviteDAO_Delete_Call {
	return &MockInviteDAO_Delete_Call{Call: _e.mock.On("Delete",
		append([]any{ctx, code}, tx...)...)}
}

func (_c *MockInviteDAO_Delete_Call) Run(run func(ctx context.Context, code string, tx ...*sql.Tx)) *MockInviteDAO_Delete_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockInviteDAO_Delete_Call) Return(err error) *MockInviteDAO_Delete_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInviteDAO_Delete_Call) RunAndReturn(run func(ctx context.Context, code string, tx ...*sql.Tx) error) *MockInviteDAO_Delete_Call {
	_c.Call.Return(run)
	return _c
}

// GetByCode provides a mock function for the type MockInviteDAO
func (_mock *MockInviteDAO) GetByCode(ctx context.Context, code string, tx ...*sql.Tx) (*model.Invite, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, code, tx)
	} else {
		tmpRet = _mock.Called(ctx, code)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetByCode")
	}

	var r0 *model.Invite
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...*sql.Tx) (*model.Invite, error)); ok {
		return returnFunc(ctx, code, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...*sql.Tx) *model.Invite); ok {
		r0 = returnFunc(ctx, code, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Invite)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, code, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInviteDAO_GetByCode_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByCode'
type MockInviteDAO_GetByCode_Call struct {
	*mock.Call
}

// GetByCode is a helper method to define mock.On call
//   - ctx context.Context
//   - code string
//   - tx ...*sql.Tx
func (_e *MockInviteDAO_Expecter) GetByCode(ctx any, code any, tx ...any) *MockInviteDAO_GetByCode_Call {
	return &MockInviteDAO_GetByCode_Call{Call: _e.mock.On("GetByCode",
		append([]any{ctx, code}, tx...)...)}
}

func (_c *MockInviteDAO_GetByCode_Call) Run(run func(ctx context.Context, code string, tx ...*sql.Tx)) *MockInviteDAO_GetByCode_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockInviteDAO_GetByCode_Call) Return(invite *model.Invite, err error) *MockInviteDAO_GetByCode_Call {
	_c.Call.Return(invite, err)
	return _c
}

func (_c *MockInviteDAO_GetByCode_Call) RunAndReturn(run func(ctx context.Context, code string, tx ...*sql.Tx) (*model.Invite, error)) *MockInviteDAO_GetByCode_Call {
	_c.Call.Return(run)
	return _c
}

// List provides a mock function for the type MockInviteDAO
func (_mock *MockInviteDAO) List(ctx context.Context, q spec.InviteListQuery, tx ...*sql.Tx) ([]model.Invite, int, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, q, tx)
	} else {
		tmpRet = _mock.Called(ctx, q)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for List")
	}

	var r0 []model.Invite
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.InviteListQuery, ...*sql.Tx) ([]model.Invite, int, error)); ok {
		return returnFunc(ctx, q, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.InviteListQuery, ...*sql.Tx) []model.Invite); ok {
		r0 = returnFunc(ctx, q, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.Invite)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, spec.InviteListQuery, ...*sql.Tx) int); ok {
		r1 = returnFunc(ctx, q, tx...)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, spec.InviteListQuery, ...*sql.Tx) error); ok {
		r2 = returnFunc(ctx, q, tx...)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockInviteDAO_List_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'List'
type MockInviteDAO_List_Call struct {
	*mock.Call
}

// List is a helper method to define mock.On call
//   - ctx context.Context
//   - q spec.InviteListQuery
//   - tx ...*sql.Tx
func (_e *MockInviteDAO_Expecter) List(ctx any, q any, tx ...any) *MockInviteDAO_List_Call {
	return &MockInviteDAO_List_Call{Call: _e.mock.On("List",
		append([]any{ctx, q}, tx...)...)}
}

func (_c *MockInviteDAO_List_Call) Run(run func(ctx context.Context, q spec.InviteListQuery, tx ...*sql.Tx)) *MockInviteDAO_List_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.InviteListQuery
		if args[1] != nil {
			arg1 = args[1].(spec.InviteListQuery)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockInviteDAO_List_Call) Return(invites []model.Invite, n int, err error) *MockInviteDAO_List_Call {
	_c.Call.Return(invites, n, err)
	return _c
}

func (_c *MockInviteDAO_List_Call) RunAndReturn(run func(ctx context.Context, q spec.InviteListQuery, tx ...*sql.Tx) ([]model.Invite, int, error)) *MockInviteDAO_List_Call {
	_c.Call.Return(run)
	return _c
}

// MarkUsed provides a mock function for the type MockInviteDAO
func (_mock *MockInviteDAO) MarkUsed(ctx context.Context, s spec.InviteRedemption, tx ...*sql.Tx) error {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, s, tx)
	} else {
		tmpRet = _mock.Called(ctx, s)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for MarkUsed")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.InviteRedemption, ...*sql.Tx) error); ok {
		r0 = returnFunc(ctx, s, tx...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockInviteDAO_MarkUsed_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkUsed'
type MockInviteDAO_MarkUsed_Call struct {
	*mock.Call
}

// MarkUsed is a helper method to define mock.On call
//   - ctx context.Context
//   - s spec.InviteRedemption
//   - tx ...*sql.Tx
func (_e *MockInviteDAO_Expecter) MarkUsed(ctx any, s any, tx ...any) *MockInviteDAO_MarkUsed_Call {
	return &MockInviteDAO_MarkUsed_Call{Call: _e.mock.On("MarkUsed",
		append([]any{ctx, s}, tx...)...)}
}

func (_c *MockInviteDAO_MarkUsed_Call) Run(run func(ctx context.Context, s spec.InviteRedemption, tx ...*sql.Tx)) *MockInviteDAO_MarkUsed_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.InviteRedemption
		if args[1] != nil {
			arg1 = args[1].(spec.InviteRedemption)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockInviteDAO_MarkUsed_Call) Return(err error) *MockInviteDAO_MarkUsed_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockInviteDAO_MarkUsed_Call) RunAndReturn(run func(ctx context.Context, s spec.InviteRedemption, tx ...*sql.Tx) error) *MockInviteDAO_MarkUsed_Call {
	_c.Call.Return(run)
	return _c
}
