// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package dao

import (
	"context"
	"database/sql"
	"umineko_city_of_books/internal/model"
	"umineko_city_of_books/internal/model/spec"

	"github.com/google/uuid"
	mock "github.com/stretchr/testify/mock"
)

// NewMockNotificationDAO creates a new instance of MockNotificationDAO. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockNotificationDAO(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockNotificationDAO {
	mock := &MockNotificationDAO{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockNotificationDAO is an autogenerated mock type for the NotificationDAO type
type MockNotificationDAO struct {
	mock.Mock
}

type MockNotificationDAO_Expecter struct {
	mock *mock.Mock
}

func (_m *MockNotificationDAO) EXPECT() *MockNotificationDAO_Expecter {
	return &MockNotificationDAO_Expecter{mock: &_m.Mock}
}

// Create provides a mock function for the type MockNotificationDAO
func (_mock *MockNotificationDAO) Create(ctx context.Context, s spec.NewNotification, tx ...*sql.Tx) (*model.NotificationRow, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, s, tx)
	} else {
		tmpRet = _mock.Called(ctx, s)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 *model.NotificationRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.NewNotification, ...*sql.Tx) (*model.NotificationRow, error)); ok {
		return returnFunc(ctx, s, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.NewNotification, ...*sql.Tx) *model.NotificationRow); ok {
		r0 = returnFunc(ctx, s, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.NotificationRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, spec.NewNotification, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, s, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNotificationDAO_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockNotificationDAO_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - ctx context.Context
//   - s spec.NewNotification
//   - tx ...*sql.Tx
func (_e *MockNotificationDAO_Expecter) Create(ctx any, s any, tx ...any) *MockNotificationDAO_Create_Call {
	return &MockNotificationDAO_Create_Call{Call: _e.mock.On("Create",
		append([]any{ctx, s}, tx...)...)}
}

func (_c *MockNotificationDAO_Create_Call) Run(run func(ctx context.Context, s spec.NewNotification, tx ...*sql.Tx)) *MockNotificationDAO_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.NewNotification
		if args[1] != nil {
			arg1 = args[1].(spec.NewNotification)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockNotificationDAO_Create_Call) Return(notificationRow *model.NotificationRow, err error) *MockNotificationDAO_Create_Call {
	_c.Call.Return(notificationRow, err)
	return _c
}

func (_c *MockNotificationDAO_Create_Call) RunAndReturn(run func(ctx context.Context, s spec.NewNotification, tx ...*sql.Tx) (*model.NotificationRow, error)) *MockNotificationDAO_Create_Call {
	_c.Call.Return(run)
	return _c
}

// DeleteOlderThanBatch provides a mock function for the type MockNotificationDAO
func (_mock *MockNotificationDAO) DeleteOlderThanBatch(ctx context.Context, s spec.NotificationPruneBatch, tx ...*sql.Tx) (int64, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, s, tx)
	} else {
		tmpRet = _mock.Called(ctx, s)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for DeleteOlderThanBatch")
	}

	var r0 int64
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.NotificationPruneBatch, ...*sql.Tx) (int64, error)); ok {
		return returnFunc(ctx, s, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.NotificationPruneBatch, ...*sql.Tx) int64); ok {
		r0 = returnFunc(ctx, s, tx...)
	} else {
		r0 = ret.Get(0).(int64)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, spec.NotificationPruneBatch, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, s, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNotificationDAO_DeleteOlderThanBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'DeleteOlderThanBatch'
type MockNotificationDAO_DeleteOlderThanBatch_Call struct {
	*mock.Call
}

// DeleteOlderThanBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - s spec.NotificationPruneBatch
//   - tx ...*sql.Tx
func (_e *MockNotificationDAO_Expecter) DeleteOlderThanBatch(ctx any, s any, tx ...any) *MockNotificationDAO_DeleteOlderThanBatch_Call {
	return &MockNotificationDAO_DeleteOlderThanBatch_Call{Call: _e.mock.On("DeleteOlderThanBatch",
		append([]any{ctx, s}, tx...)...)}
}

func (_c *MockNotificationDAO_DeleteOlderThanBatch_Call) Run(run func(ctx context.Context, s spec.NotificationPruneBatch, tx ...*sql.Tx)) *MockNotificationDAO_DeleteOlderThanBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.NotificationPruneBatch
		if args[1] != nil {
			arg1 = args[1].(spec.NotificationPruneBatch)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockNotificationDAO_DeleteOlderThanBatch_Call) Return(n int64, err error) *MockNotificationDAO_DeleteOlderThanBatch_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockNotificationDAO_DeleteOlderThanBatch_Call) RunAndReturn(run func(ctx context.Context, s spec.NotificationPruneBatch, tx ...*sql.Tx) (int64, error)) *MockNotificationDAO_DeleteOlderThanBatch_Call {
	_c.Call.Return(run)
	return _c
}

// GetByID provides a mock function for the type MockNotificationDAO
func (_mock *MockNotificationDAO) GetByID(ctx context.Context, s spec.NotificationLookup, tx ...*sql.Tx) (*model.NotificationRow, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, s, tx)
	} else {
		tmpRet = _mock.Called(ctx, s)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for GetByID")
	}

	var r0 *model.NotificationRow
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.NotificationLookup, ...*sql.Tx) (*model.NotificationRow, error)); ok {
		return returnFunc(ctx, s, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.NotificationLookup, ...*sql.Tx) *model.NotificationRow); ok {
		r0 = returnFunc(ctx, s, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.NotificationRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, spec.NotificationLookup, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, s, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNotificationDAO_GetByID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetByID'
type MockNotificationDAO_GetByID_Call struct {
	*mock.Call
}

// GetByID is a helper method to define mock.On call
//   - ctx context.Context
//   - s spec.NotificationLookup
//   - tx ...*sql.Tx
func (_e *MockNotificationDAO_Expecter) GetByID(ctx any, s any, tx ...any) *MockNotificationDAO_GetByID_Call {
	return &MockNotificationDAO_GetByID_Call{Call: _e.mock.On("GetByID",
		append([]any{ctx, s}, tx...)...)}
}

func (_c *MockNotificationDAO_GetByID_Call) Run(run func(ctx context.Context, s spec.NotificationLookup, tx ...*sql.Tx)) *MockNotificationDAO_GetByID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.NotificationLookup
		if args[1] != nil {
			arg1 = args[1].(spec.NotificationLookup)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockNotificationDAO_GetByID_Call) Return(notificationRow *model.NotificationRow, err error) *MockNotificationDAO_GetByID_Call {
	_c.Call.Return(notificationRow, err)
	return _c
}

func (_c *MockNotificationDAO_GetByID_Call) RunAndReturn(run func(ctx context.Context, s spec.NotificationLookup, tx ...*sql.Tx) (*model.NotificationRow, error)) *MockNotificationDAO_GetByID_Call {
	_c.Call.Return(run)
	return _c
}

// HasRecentDuplicate provides a mock function for the type MockNotificationDAO
func (_mock *MockNotificationDAO) HasRecentDuplicate(ctx context.Context, q spec.NotificationDuplicateCheck, tx ...*sql.Tx) (bool, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, q, tx)
	} else {
		tmpRet = _mock.Called(ctx, q)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for HasRecentDuplicate")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.NotificationDuplicateCheck, ...*sql.Tx) (bool, error)); ok {
		return returnFunc(ctx, q, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.NotificationDuplicateCheck, ...*sql.Tx) bool); ok {
		r0 = returnFunc(ctx, q, tx...)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, spec.NotificationDuplicateCheck, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, q, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNotificationDAO_HasRecentDuplicate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasRecentDuplicate'
type MockNotificationDAO_HasRecentDuplicate_Call struct {
	*mock.Call
}

// HasRecentDuplicate is a helper method to define mock.On call
//   - ctx context.Context
//   - q spec.NotificationDuplicateCheck
//   - tx ...*sql.Tx
func (_e *MockNotificationDAO_Expecter) HasRecentDuplicate(ctx any, q any, tx ...any) *MockNotificationDAO_HasRecentDuplicate_Call {
	return &MockNotificationDAO_HasRecentDuplicate_Call{Call: _e.mock.On("HasRecentDuplicate",
		append([]any{ctx, q}, tx...)...)}
}

func (_c *MockNotificationDAO_HasRecentDuplicate_Call) Run(run func(ctx context.Context, q spec.NotificationDuplicateCheck, tx ...*sql.Tx)) *MockNotificationDAO_HasRecentDuplicate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.NotificationDuplicateCheck
		if args[1] != nil {
			arg1 = args[1].(spec.NotificationDuplicateCheck)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockNotificationDAO_HasRecentDuplicate_Call) Return(b bool, err error) *MockNotificationDAO_HasRecentDuplicate_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockNotificationDAO_HasRecentDuplicate_Call) RunAndReturn(run func(ctx context.Context, q spec.NotificationDuplicateCheck, tx ...*sql.Tx) (bool, error)) *MockNotificationDAO_HasRecentDuplicate_Call {
	_c.Call.Return(run)
	return _c
}

// HasRecentFromActor provides a mock function for the type MockNotificationDAO
func (_mock *MockNotificationDAO) HasRecentFromActor(ctx context.Context, q spec.NotificationActorRecency, tx ...*sql.Tx) (bool, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, q, tx)
	} else {
		tmpRet = _mock.Called(ctx, q)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for HasRecentFromActor")
	}

	var r0 bool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.NotificationActorRecency, ...*sql.Tx) (bool, error)); ok {
		return returnFunc(ctx, q, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.NotificationActorRecency, ...*sql.Tx) bool); ok {
		r0 = returnFunc(ctx, q, tx...)
	} else {
		r0 = ret.Get(0).(bool)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, spec.NotificationActorRecency, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, q, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNotificationDAO_HasRecentFromActor_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'HasRecentFromActor'
type MockNotificationDAO_HasRecentFromActor_Call struct {
	*mock.Call
}

// HasRecentFromActor is a helper method to define mock.On call
//   - ctx context.Context
//   - q spec.NotificationActorRecency
//   - tx ...*sql.Tx
func (_e *MockNotificationDAO_Expecter) HasRecentFromActor(ctx any, q any, tx ...any) *MockNotificationDAO_HasRecentFromActor_Call {
	return &MockNotificationDAO_HasRecentFromActor_Call{Call: _e.mock.On("HasRecentFromActor",
		append([]any{ctx, q}, tx...)...)}
}

func (_c *MockNotificationDAO_HasRecentFromActor_Call) Run(run func(ctx context.Context, q spec.NotificationActorRecency, tx ...*sql.Tx)) *MockNotificationDAO_HasRecentFromActor_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.NotificationActorRecency
		if args[1] != nil {
			arg1 = args[1].(spec.NotificationActorRecency)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockNotificationDAO_HasRecentFromActor_Call) Return(b bool, err error) *MockNotificationDAO_HasRecentFromActor_Call {
	_c.Call.Return(b, err)
	return _c
}

func (_c *MockNotificationDAO_HasRecentFromActor_Call) RunAndReturn(run func(ctx context.Context, q spec.NotificationActorRecency, tx ...*sql.Tx) (bool, error)) *MockNotificationDAO_HasRecentFromActor_Call {
	_c.Call.Return(run)
	return _c
}

// ListByUser provides a mock function for the type MockNotificationDAO
func (_mock *MockNotificationDAO) ListByUser(ctx context.Context, q spec.NotificationListing, tx ...*sql.Tx) ([]model.NotificationRow, int, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, q, tx)
	} else {
		tmpRet = _mock.Called(ctx, q)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for ListByUser")
	}

	var r0 []model.NotificationRow
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.NotificationListing, ...*sql.Tx) ([]model.NotificationRow, int, error)); ok {
		return returnFunc(ctx, q, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.NotificationListing, ...*sql.Tx) []model.NotificationRow); ok {
		r0 = returnFunc(ctx, q, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.NotificationRow)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, spec.NotificationListing, ...*sql.Tx) int); ok {
		r1 = returnFunc(ctx, q, tx...)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, spec.NotificationListing, ...*sql.Tx) error); ok {
		r2 = returnFunc(ctx, q, tx...)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockNotificationDAO_ListByUser_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ListByUser'
type MockNotificationDAO_ListByUser_Call struct {
	*mock.Call
}

// ListByUser is a helper method to define mock.On call
//   - ctx context.Context
//   - q spec.NotificationListing
//   - tx ...*sql.Tx
func (_e *MockNotificationDAO_Expecter) ListByUser(ctx any, q any, tx ...any) *MockNotificationDAO_ListByUser_Call {
	return &MockNotificationDAO_ListByUser_Call{Call: _e.mock.On("ListByUser",
		append([]any{ctx, q}, tx...)...)}
}

func (_c *MockNotificationDAO_ListByUser_Call) Run(run func(ctx context.Context, q spec.NotificationListing, tx ...*sql.Tx)) *MockNotificationDAO_ListByUser_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.NotificationListing
		if args[1] != nil {
			arg1 = args[1].(spec.NotificationListing)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockNotificationDAO_ListByUser_Call) Return(notificationRows []model.NotificationRow, n int, err error) *MockNotificationDAO_ListByUser_Call {
	_c.Call.Return(notificationRows, n, err)
	return _c
}

func (_c *MockNotificationDAO_ListByUser_Call) RunAndReturn(run func(ctx context.Context, q spec.NotificationListing, tx ...*sql.Tx) ([]model.NotificationRow, int, error)) *MockNotificationDAO_ListByUser_Call {
	_c.Call.Return(run)
	return _c
}

// MarkAllRead provides a mock function for the type MockNotificationDAO
func (_mock *MockNotificationDAO) MarkAllRead(ctx context.Context, userID uuid.UUID, tx ...*sql.Tx) error {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, userID, tx)
	} else {
		tmpRet = _mock.Called(ctx, userID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for MarkAllRead")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...*sql.Tx) error); ok {
		r0 = returnFunc(ctx, userID, tx...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNotificationDAO_MarkAllRead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkAllRead'
type MockNotificationDAO_MarkAllRead_Call struct {
	*mock.Call
}

// MarkAllRead is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - tx ...*sql.Tx
func (_e *MockNotificationDAO_Expecter) MarkAllRead(ctx any, userID any, tx ...any) *MockNotificationDAO_MarkAllRead_Call {
	return &MockNotificationDAO_MarkAllRead_Call{Call: _e.mock.On("MarkAllRead",
		append([]any{ctx, userID}, tx...)...)}
}

func (_c *MockNotificationDAO_MarkAllRead_Call) Run(run func(ctx context.Context, userID uuid.UUID, tx ...*sql.Tx)) *MockNotificationDAO_MarkAllRead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockNotificationDAO_MarkAllRead_Call) Return(err error) *MockNotificationDAO_MarkAllRead_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNotificationDAO_MarkAllRead_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, tx ...*sql.Tx) error) *MockNotificationDAO_MarkAllRead_Call {
	_c.Call.Return(run)
	return _c
}

// MarkRead provides a mock function for the type MockNotificationDAO
func (_mock *MockNotificationDAO) MarkRead(ctx context.Context, s spec.NotificationLookup, tx ...*sql.Tx) error {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, s, tx)
	} else {
		tmpRet = _mock.Called(ctx, s)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for MarkRead")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.NotificationLookup, ...*sql.Tx) error); ok {
		r0 = returnFunc(ctx, s, tx...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNotificationDAO_MarkRead_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkRead'
type MockNotificationDAO_MarkRead_Call struct {
	*mock.Call
}

// MarkRead is a helper method to define mock.On call
//   - ctx context.Context
//   - s spec.NotificationLookup
//   - tx ...*sql.Tx
func (_e *MockNotificationDAO_Expecter) MarkRead(ctx any, s any, tx ...any) *MockNotificationDAO_MarkRead_Call {
	return &MockNotificationDAO_MarkRead_Call{Call: _e.mock.On("MarkRead",
		append([]any{ctx, s}, tx...)...)}
}

func (_c *MockNotificationDAO_MarkRead_Call) Run(run func(ctx context.Context, s spec.NotificationLookup, tx ...*sql.Tx)) *MockNotificationDAO_MarkRead_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.NotificationLookup
		if args[1] != nil {
			arg1 = args[1].(spec.NotificationLookup)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockNotificationDAO_MarkRead_Call) Return(err error) *MockNotificationDAO_MarkRead_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNotificationDAO_MarkRead_Call) RunAndReturn(run func(ctx context.Context, s spec.NotificationLookup, tx ...*sql.Tx) error) *MockNotificationDAO_MarkRead_Call {
	_c.Call.Return(run)
	return _c
}

// MarkReadByReference provides a mock function for the type MockNotificationDAO
func (_mock *MockNotificationDAO) MarkReadByReference(ctx context.Context, s spec.NotificationReferenceRead, tx ...*sql.Tx) error {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, s, tx)
	} else {
		tmpRet = _mock.Called(ctx, s)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for MarkReadByReference")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.NotificationReferenceRead, ...*sql.Tx) error); ok {
		r0 = returnFunc(ctx, s, tx...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockNotificationDAO_MarkReadByReference_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MarkReadByReference'
type MockNotificationDAO_MarkReadByReference_Call struct {
	*mock.Call
}

// MarkReadByReference is a helper method to define mock.On call
//   - ctx context.Context
//   - s spec.NotificationReferenceRead
//   - tx ...*sql.Tx
func (_e *MockNotificationDAO_Expecter) MarkReadByReference(ctx any, s any, tx ...any) *MockNotificationDAO_MarkReadByReference_Call {
	return &MockNotificationDAO_MarkReadByReference_Call{Call: _e.mock.On("MarkReadByReference",
		append([]any{ctx, s}, tx...)...)}
}

func (_c *MockNotificationDAO_MarkReadByReference_Call) Run(run func(ctx context.Context, s spec.NotificationReferenceRead, tx ...*sql.Tx)) *MockNotificationDAO_MarkReadByReference_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.NotificationReferenceRead
		if args[1] != nil {
			arg1 = args[1].(spec.NotificationReferenceRead)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockNotificationDAO_MarkReadByReference_Call) Return(err error) *MockNotificationDAO_MarkReadByReference_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockNotificationDAO_MarkReadByReference_Call) RunAndReturn(run func(ctx context.Context, s spec.NotificationReferenceRead, tx ...*sql.Tx) error) *MockNotificationDAO_MarkReadByReference_Call {
	_c.Call.Return(run)
	return _c
}

// UnreadCount provides a mock function for the type MockNotificationDAO
func (_mock *MockNotificationDAO) UnreadCount(ctx context.Context, userID uuid.UUID, tx ...*sql.Tx) (int, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, userID, tx)
	} else {
		tmpRet = _mock.Called(ctx, userID)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for UnreadCount")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...*sql.Tx) (int, error)); ok {
		return returnFunc(ctx, userID, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, uuid.UUID, ...*sql.Tx) int); ok {
		r0 = returnFunc(ctx, userID, tx...)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, uuid.UUID, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, userID, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockNotificationDAO_UnreadCount_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UnreadCount'
type MockNotificationDAO_UnreadCount_Call struct {
	*mock.Call
}

// UnreadCount is a helper method to define mock.On call
//   - ctx context.Context
//   - userID uuid.UUID
//   - tx ...*sql.Tx
func (_e *MockNotificationDAO_Expecter) UnreadCount(ctx any, userID any, tx ...any) *MockNotificationDAO_UnreadCount_Call {
	return &MockNotificationDAO_UnreadCount_Call{Call: _e.mock.On("UnreadCount",
		append([]any{ctx, userID}, tx...)...)}
}

func (_c *MockNotificationDAO_UnreadCount_Call) Run(run func(ctx context.Context, userID uuid.UUID, tx ...*sql.Tx)) *MockNotificationDAO_UnreadCount_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 uuid.UUID
		if args[1] != nil {
			arg1 = args[1].(uuid.UUID)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockNotificationDAO_UnreadCount_Call) Return(n int, err error) *MockNotificationDAO_UnreadCount_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockNotificationDAO_UnreadCount_Call) RunAndReturn(run func(ctx context.Context, userID uuid.UUID, tx ...*sql.Tx) (int, error)) *MockNotificationDAO_UnreadCount_Call {
	_c.Call.Return(run)
	return _c
}
