// Code generated by internal/dao/queries/expand; DO NOT EDIT.
// template: internal/dao/queries/templates/owned_bind.go.tmpl
// entity: Mystery

package dao

import (
	"context"

	"github.com/google/uuid"

	"umineko_city_of_books/internal/dao/sqlcgen"
	"umineko_city_of_books/internal/model/spec"
)

type (
	mysteryOwnedQuerier struct{}
)

func (mysteryOwnedQuerier) Delete(ctx context.Context, q *sqlcgen.Queries, s spec.OwnedDeletion) (int64, error) {
	return q.DeleteOwnedMystery(ctx, sqlcgen.DeleteOwnedMysteryParams{ID: s.ID, UserID: s.UserID})
}

func (mysteryOwnedQuerier) DeleteAsAdmin(ctx context.Context, q *sqlcgen.Queries, id uuid.UUID) error {
	return q.DeleteOwnedMysteryAsAdmin(ctx, id)
}

func (mysteryOwnedQuerier) AuthorID(ctx context.Context, q *sqlcgen.Queries, id uuid.UUID) (uuid.UUID, error) {
	return q.GetOwnedMysteryAuthorID(ctx, id)
}

func (mysteryOwnedQuerier) IncrementViewCount(ctx context.Context, q *sqlcgen.Queries, id uuid.UUID) error {
	return q.IncrementMysteryViewCount(ctx, id)
}
