// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package dao

import (
	"context"
	"database/sql"
	"umineko_city_of_books/internal/model"
	"umineko_city_of_books/internal/model/spec"

	mock "github.com/stretchr/testify/mock"
)

// NewMockSearchDAO creates a new instance of MockSearchDAO. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSearchDAO(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSearchDAO {
	mock := &MockSearchDAO{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSearchDAO is an autogenerated mock type for the SearchDAO type
type MockSearchDAO struct {
	mock.Mock
}

type MockSearchDAO_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSearchDAO) EXPECT() *MockSearchDAO_Expecter {
	return &MockSearchDAO_Expecter{mock: &_m.Mock}
}

// QuickSearch provides a mock function for the type MockSearchDAO
func (_mock *MockSearchDAO) QuickSearch(ctx context.Context, s spec.QuickSearchQuery, tx ...*sql.Tx) ([]model.SearchResult, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, s, tx)
	} else {
		tmpRet = _mock.Called(ctx, s)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for QuickSearch")
	}

	var r0 []model.SearchResult
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.QuickSearchQuery, ...*sql.Tx) ([]model.SearchResult, error)); ok {
		return returnFunc(ctx, s, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.QuickSearchQuery, ...*sql.Tx) []model.SearchResult); ok {
		r0 = returnFunc(ctx, s, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.SearchResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, spec.QuickSearchQuery, ...*sql.Tx) error); ok {
		r1 = returnFunc(ctx, s, tx...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSearchDAO_QuickSearch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QuickSearch'
type MockSearchDAO_QuickSearch_Call struct {
	*mock.Call
}

// QuickSearch is a helper method to define mock.On call
//   - ctx context.Context
//   - s spec.QuickSearchQuery
//   - tx ...*sql.Tx
func (_e *MockSearchDAO_Expecter) QuickSearch(ctx any, s any, tx ...any) *MockSearchDAO_QuickSearch_Call {
	return &MockSearchDAO_QuickSearch_Call{Call: _e.mock.On("QuickSearch",
		append([]any{ctx, s}, tx...)...)}
}

func (_c *MockSearchDAO_QuickSearch_Call) Run(run func(ctx context.Context, s spec.QuickSearchQuery, tx ...*sql.Tx)) *MockSearchDAO_QuickSearch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.QuickSearchQuery
		if args[1] != nil {
			arg1 = args[1].(spec.QuickSearchQuery)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockSearchDAO_QuickSearch_Call) Return(searchResults []model.SearchResult, err error) *MockSearchDAO_QuickSearch_Call {
	_c.Call.Return(searchResults, err)
	return _c
}

func (_c *MockSearchDAO_QuickSearch_Call) RunAndReturn(run func(ctx context.Context, s spec.QuickSearchQuery, tx ...*sql.Tx) ([]model.SearchResult, error)) *MockSearchDAO_QuickSearch_Call {
	_c.Call.Return(run)
	return _c
}

// Search provides a mock function for the type MockSearchDAO
func (_mock *MockSearchDAO) Search(ctx context.Context, s spec.SearchQuery, tx ...*sql.Tx) ([]model.SearchResult, int, error) {
	var tmpRet mock.Arguments
	if len(tx) > 0 {
		tmpRet = _mock.Called(ctx, s, tx)
	} else {
		tmpRet = _mock.Called(ctx, s)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Search")
	}

	var r0 []model.SearchResult
	var r1 int
	var r2 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.SearchQuery, ...*sql.Tx) ([]model.SearchResult, int, error)); ok {
		return returnFunc(ctx, s, tx...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, spec.SearchQuery, ...*sql.Tx) []model.SearchResult); ok {
		r0 = returnFunc(ctx, s, tx...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]model.SearchResult)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, spec.SearchQuery, ...*sql.Tx) int); ok {
		r1 = returnFunc(ctx, s, tx...)
	} else {
		r1 = ret.Get(1).(int)
	}
	if returnFunc, ok := ret.Get(2).(func(context.Context, spec.SearchQuery, ...*sql.Tx) error); ok {
		r2 = returnFunc(ctx, s, tx...)
	} else {
		r2 = ret.Error(2)
	}
	return r0, r1, r2
}

// MockSearchDAO_Search_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Search'
type MockSearchDAO_Search_Call struct {
	*mock.Call
}

// Search is a helper method to define mock.On call
//   - ctx context.Context
//   - s spec.SearchQuery
//   - tx ...*sql.Tx
func (_e *MockSearchDAO_Expecter) Search(ctx any, s any, tx ...any) *MockSearchDAO_Search_Call {
	return &MockSearchDAO_Search_Call{Call: _e.mock.On("Search",
		append([]any{ctx, s}, tx...)...)}
}

func (_c *MockSearchDAO_Search_Call) Run(run func(ctx context.Context, s spec.SearchQuery, tx ...*sql.Tx)) *MockSearchDAO_Search_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 spec.SearchQuery
		if args[1] != nil {
			arg1 = args[1].(spec.SearchQuery)
		}
		var arg2 []*sql.Tx
		var variadicArgs []*sql.Tx
		if len(args) > 2 {
			variadicArgs = args[2].([]*sql.Tx)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *MockSearchDAO_Search_Call) Return(searchResults []model.SearchResult, n int, err error) *MockSearchDAO_Search_Call {
	_c.Call.Return(searchResults, n, err)
	return _c
}

func (_c *MockSearchDAO_Search_Call) RunAndReturn(run func(ctx context.Context, s spec.SearchQuery, tx ...*sql.Tx) ([]model.SearchResult, int, error)) *MockSearchDAO_Search_Call {
	_c.Call.Return(run)
	return _c
}
