// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package dao

import (
	"context"
	"umineko_city_of_books/internal/dao/sqlcgen"
	"umineko_city_of_books/internal/model/spec"

	mock "github.com/stretchr/testify/mock"
)

// newMockvoteQuerier creates a new instance of mockvoteQuerier. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func newMockvoteQuerier(t interface {
	mock.TestingT
	Cleanup(func())
}) *mockvoteQuerier {
	mock := &mockvoteQuerier{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// mockvoteQuerier is an autogenerated mock type for the voteQuerier type
type mockvoteQuerier struct {
	mock.Mock
}

type mockvoteQuerier_Expecter struct {
	mock *mock.Mock
}

func (_m *mockvoteQuerier) EXPECT() *mockvoteQuerier_Expecter {
	return &mockvoteQuerier_Expecter{mock: &_m.Mock}
}

// Clear provides a mock function for the type mockvoteQuerier
func (_mock *mockvoteQuerier) Clear(ctx context.Context, q *sqlcgen.Queries, s spec.Vote) error {
	ret := _mock.Called(ctx, q, s)

	if len(ret) == 0 {
		panic("no return value specified for Clear")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sqlcgen.Queries, spec.Vote) error); ok {
		r0 = returnFunc(ctx, q, s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockvoteQuerier_Clear_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Clear'
type mockvoteQuerier_Clear_Call struct {
	*mock.Call
}

// Clear is a helper method to define mock.On call
//   - ctx context.Context
//   - q *sqlcgen.Queries
//   - s spec.Vote
func (_e *mockvoteQuerier_Expecter) Clear(ctx any, q any, s any) *mockvoteQuerier_Clear_Call {
	return &mockvoteQuerier_Clear_Call{Call: _e.mock.On("Clear", ctx, q, s)}
}

func (_c *mockvoteQuerier_Clear_Call) Run(run func(ctx context.Context, q *sqlcgen.Queries, s spec.Vote)) *mockvoteQuerier_Clear_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sqlcgen.Queries
		if args[1] != nil {
			arg1 = args[1].(*sqlcgen.Queries)
		}
		var arg2 spec.Vote
		if args[2] != nil {
			arg2 = args[2].(spec.Vote)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockvoteQuerier_Clear_Call) Return(err error) *mockvoteQuerier_Clear_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockvoteQuerier_Clear_Call) RunAndReturn(run func(ctx context.Context, q *sqlcgen.Queries, s spec.Vote) error) *mockvoteQuerier_Clear_Call {
	_c.Call.Return(run)
	return _c
}

// Upsert provides a mock function for the type mockvoteQuerier
func (_mock *mockvoteQuerier) Upsert(ctx context.Context, q *sqlcgen.Queries, s spec.Vote) error {
	ret := _mock.Called(ctx, q, s)

	if len(ret) == 0 {
		panic("no return value specified for Upsert")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, *sqlcgen.Queries, spec.Vote) error); ok {
		r0 = returnFunc(ctx, q, s)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// mockvoteQuerier_Upsert_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Upsert'
type mockvoteQuerier_Upsert_Call struct {
	*mock.Call
}

// Upsert is a helper method to define mock.On call
//   - ctx context.Context
//   - q *sqlcgen.Queries
//   - s spec.Vote
func (_e *mockvoteQuerier_Expecter) Upsert(ctx any, q any, s any) *mockvoteQuerier_Upsert_Call {
	return &mockvoteQuerier_Upsert_Call{Call: _e.mock.On("Upsert", ctx, q, s)}
}

func (_c *mockvoteQuerier_Upsert_Call) Run(run func(ctx context.Context, q *sqlcgen.Queries, s spec.Vote)) *mockvoteQuerier_Upsert_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *sqlcgen.Queries
		if args[1] != nil {
			arg1 = args[1].(*sqlcgen.Queries)
		}
		var arg2 spec.Vote
		if args[2] != nil {
			arg2 = args[2].(spec.Vote)
		}
		run(
			arg0,
			arg1,
			arg2,
		)
	})
	return _c
}

func (_c *mockvoteQuerier_Upsert_Call) Return(err error) *mockvoteQuerier_Upsert_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *mockvoteQuerier_Upsert_Call) RunAndReturn(run func(ctx context.Context, q *sqlcgen.Queries, s spec.Vote) error) *mockvoteQuerier_Upsert_Call {
	_c.Call.Return(run)
	return _c
}
