// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: audit_log.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const countAuditLog = `-- name: CountAuditLog :one
SELECT COUNT(*)
FROM audit_log a
WHERE ($1::text = '' OR a.action = $1::text)
`

func (q *Queries) CountAuditLog(ctx context.Context, dollar_1 string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAuditLog, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countAuditLogForUser = `-- name: CountAuditLogForUser :one
SELECT COUNT(*)
FROM audit_log a
WHERE ((a.target_type = 'user' AND a.target_id = $1::text) OR a.subject_id = $1::text::uuid)
`

func (q *Queries) CountAuditLogForUser(ctx context.Context, dollar_1 string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAuditLogForUser, dollar_1)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAuditLogEntry = `-- name: CreateAuditLogEntry :exec
INSERT INTO audit_log (actor_id, action, target_type, target_id, details, subject_id)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateAuditLogEntryParams struct {
	ActorID    *uuid.UUID
	Action     string
	TargetType string
	TargetID   sql.NullString
	Details    string
	SubjectID  *uuid.UUID
}

func (q *Queries) CreateAuditLogEntry(ctx context.Context, arg CreateAuditLogEntryParams) error {
	_, err := q.db.ExecContext(ctx, createAuditLogEntry,
		arg.ActorID,
		arg.Action,
		arg.TargetType,
		arg.TargetID,
		arg.Details,
		arg.SubjectID,
	)
	return err
}

const listAuditLog = `-- name: ListAuditLog :many
SELECT a.id, a.actor_id,
       COALESCE(u.display_name, '')::text AS actor_name,
       a.action, a.target_type, a.target_id, a.details, a.created_at, a.subject_id,
       COALESCE(s.display_name, '')::text AS subject_name,
       COALESCE(s.username, '')::text AS subject_username
FROM audit_log a
LEFT JOIN users u ON a.actor_id = u.id
LEFT JOIN users s ON a.subject_id = s.id
WHERE ($1::text = '' OR a.action = $1::text)
ORDER BY a.created_at DESC
LIMIT $2 OFFSET $3
`

type ListAuditLogParams struct {
	Column1 string
	Limit   int32
	Offset  int32
}

type ListAuditLogRow struct {
	ID              int64
	ActorID         *uuid.UUID
	ActorName       string
	Action          string
	TargetType      string
	TargetID        sql.NullString
	Details         string
	CreatedAt       time.Time
	SubjectID       *uuid.UUID
	SubjectName     string
	SubjectUsername string
}

func (q *Queries) ListAuditLog(ctx context.Context, arg ListAuditLogParams) ([]ListAuditLogRow, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLog, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditLogRow{}
	for rows.Next() {
		var i ListAuditLogRow
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.ActorName,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Details,
			&i.CreatedAt,
			&i.SubjectID,
			&i.SubjectName,
			&i.SubjectUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogForUser = `-- name: ListAuditLogForUser :many
SELECT a.id, a.actor_id,
       COALESCE(u.display_name, '')::text AS actor_name,
       a.action, a.target_type, a.target_id, a.details, a.created_at, a.subject_id,
       COALESCE(s.display_name, '')::text AS subject_name,
       COALESCE(s.username, '')::text AS subject_username
FROM audit_log a
LEFT JOIN users u ON a.actor_id = u.id
LEFT JOIN users s ON a.subject_id = s.id
WHERE ((a.target_type = 'user' AND a.target_id = $1::text) OR a.subject_id = $1::text::uuid)
ORDER BY a.created_at DESC
LIMIT $2 OFFSET $3
`

type ListAuditLogForUserParams struct {
	Column1 string
	Limit   int32
	Offset  int32
}

type ListAuditLogForUserRow struct {
	ID              int64
	ActorID         *uuid.UUID
	ActorName       string
	Action          string
	TargetType      string
	TargetID        sql.NullString
	Details         string
	CreatedAt       time.Time
	SubjectID       *uuid.UUID
	SubjectName     string
	SubjectUsername string
}

func (q *Queries) ListAuditLogForUser(ctx context.Context, arg ListAuditLogForUserParams) ([]ListAuditLogForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listAuditLogForUser, arg.Column1, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAuditLogForUserRow{}
	for rows.Next() {
		var i ListAuditLogForUserRow
		if err := rows.Scan(
			&i.ID,
			&i.ActorID,
			&i.ActorName,
			&i.Action,
			&i.TargetType,
			&i.TargetID,
			&i.Details,
			&i.CreatedAt,
			&i.SubjectID,
			&i.SubjectName,
			&i.SubjectUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
