// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: device_token.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const deleteDeviceToken = `-- name: DeleteDeviceToken :exec
DELETE FROM device_tokens WHERE token = $1 AND user_id = $2
`

type DeleteDeviceTokenParams struct {
	Token  string
	UserID uuid.UUID
}

func (q *Queries) DeleteDeviceToken(ctx context.Context, arg DeleteDeviceTokenParams) error {
	_, err := q.db.ExecContext(ctx, deleteDeviceToken, arg.Token, arg.UserID)
	return err
}

const listDeviceTokensForUser = `-- name: ListDeviceTokensForUser :many
SELECT token, platform FROM device_tokens WHERE user_id = $1
`

type ListDeviceTokensForUserRow struct {
	Token    string
	Platform string
}

func (q *Queries) ListDeviceTokensForUser(ctx context.Context, userID uuid.UUID) ([]ListDeviceTokensForUserRow, error) {
	rows, err := q.db.QueryContext(ctx, listDeviceTokensForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeviceTokensForUserRow{}
	for rows.Next() {
		var i ListDeviceTokensForUserRow
		if err := rows.Scan(&i.Token, &i.Platform); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertDeviceToken = `-- name: UpsertDeviceToken :exec
INSERT INTO device_tokens (token, user_id, platform, last_seen)
VALUES ($1, $2, $3, NOW())
ON CONFLICT (token) DO UPDATE
   SET user_id = excluded.user_id,
       platform = excluded.platform,
       last_seen = NOW()
`

type UpsertDeviceTokenParams struct {
	Token    string
	UserID   uuid.UUID
	Platform string
}

func (q *Queries) UpsertDeviceToken(ctx context.Context, arg UpsertDeviceTokenParams) error {
	_, err := q.db.ExecContext(ctx, upsertDeviceToken, arg.Token, arg.UserID, arg.Platform)
	return err
}
