// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: home_feed.sql

package sqlcgen

import (
	"context"
	"database/sql"
	"time"

	"github.com/google/uuid"
)

const listHomeCornerActivity24h = `-- name: ListHomeCornerActivity24h :many
SELECT p.corner,
       COUNT(*) AS post_count,
       COUNT(DISTINCT p.user_id) AS unique_posters,
       MAX(p.created_at)::timestamptz AS last_post_at
FROM posts p
JOIN users u ON u.id = p.user_id
WHERE p.created_at > NOW() - INTERVAL '1 day' AND u.banned_at IS NULL
GROUP BY p.corner
`

type ListHomeCornerActivity24hRow struct {
	Corner        string
	PostCount     int64
	UniquePosters int64
	LastPostAt    time.Time
}

func (q *Queries) ListHomeCornerActivity24h(ctx context.Context) ([]ListHomeCornerActivity24hRow, error) {
	rows, err := q.db.QueryContext(ctx, listHomeCornerActivity24h)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHomeCornerActivity24hRow{}
	for rows.Next() {
		var i ListHomeCornerActivity24hRow
		if err := rows.Scan(
			&i.Corner,
			&i.PostCount,
			&i.UniquePosters,
			&i.LastPostAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHomeEchoes = `-- name: ListHomeEchoes :many
WITH feed AS (
    SELECT 'theory'::text AS kind, t.id AS id, t.title AS title, substr(t.body, 1, 200)::text AS body,
           t.series AS corner, t.episode AS episode, FALSE::boolean AS is_spoiler, t.created_at AS created_at, t.user_id AS author_id
    FROM theories t
    UNION ALL
    SELECT 'post'::text AS kind, p.id AS id, ''::text AS title, substr(p.body, 1, 200)::text AS body,
           p.corner AS corner, 0::integer AS episode, FALSE::boolean AS is_spoiler, p.created_at AS created_at, p.user_id AS author_id
    FROM posts p
    UNION ALL
    SELECT 'journal'::text AS kind, j.id AS id, j.title AS title,
           substr(COALESCE((SELECT je.body FROM journal_entries je WHERE je.journal_id = j.id AND NOT je.is_draft ORDER BY je.entry_number DESC LIMIT 1), ''), 1, 200)::text AS body,
           j.work AS corner, 0::integer AS episode, FALSE::boolean AS is_spoiler, j.created_at AS created_at, j.user_id AS author_id
    FROM journals j
    WHERE j.archived_at IS NULL
    UNION ALL
    SELECT 'art'::text AS kind, a.id AS id, a.title AS title, substr(a.description, 1, 200)::text AS body,
           a.corner AS corner, 0::integer AS episode, a.is_spoiler AS is_spoiler, a.created_at AS created_at, a.user_id AS author_id
    FROM art a
)
SELECT f.kind, f.id, f.title, f.body, f.corner, f.episode, f.is_spoiler, f.created_at,
       f.author_id, u.username, u.display_name, u.avatar_url
FROM feed f
JOIN users u ON u.id = f.author_id
WHERE u.banned_at IS NULL AND NOT u.is_bot AND u.echoes_enabled
  AND f.created_at >= (CURRENT_DATE - $1::text::interval)
  AND f.created_at < (CURRENT_DATE - $1::text::interval + INTERVAL '1 day')
ORDER BY f.created_at DESC
LIMIT $2::int
`

type ListHomeEchoesParams struct {
	Ago      string
	RowLimit int32
}

type ListHomeEchoesRow struct {
	Kind        string
	ID          uuid.UUID
	Title       string
	Body        string
	Corner      string
	Episode     int32
	IsSpoiler   bool
	CreatedAt   time.Time
	AuthorID    uuid.UUID
	Username    string
	DisplayName string
	AvatarUrl   string
}

func (q *Queries) ListHomeEchoes(ctx context.Context, arg ListHomeEchoesParams) ([]ListHomeEchoesRow, error) {
	rows, err := q.db.QueryContext(ctx, listHomeEchoes, arg.Ago, arg.RowLimit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHomeEchoesRow{}
	for rows.Next() {
		var i ListHomeEchoesRow
		if err := rows.Scan(
			&i.Kind,
			&i.ID,
			&i.Title,
			&i.Body,
			&i.Corner,
			&i.Episode,
			&i.IsSpoiler,
			&i.CreatedAt,
			&i.AuthorID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHomePublicRooms = `-- name: ListHomePublicRooms :many
SELECT cr.id, cr.name, cr.description,
       (SELECT COUNT(*) FROM chat_room_members m WHERE m.room_id = cr.id) AS member_count,
       cr.last_message_at
FROM chat_rooms cr
WHERE cr.type = 'group' AND cr.is_public = TRUE AND cr.is_system = FALSE AND cr.archived_at IS NULL
ORDER BY COALESCE(cr.last_message_at, cr.created_at) DESC
LIMIT $1
`

type ListHomePublicRoomsRow struct {
	ID            uuid.UUID
	Name          string
	Description   string
	MemberCount   int64
	LastMessageAt sql.NullTime
}

func (q *Queries) ListHomePublicRooms(ctx context.Context, limit int32) ([]ListHomePublicRoomsRow, error) {
	rows, err := q.db.QueryContext(ctx, listHomePublicRooms, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHomePublicRoomsRow{}
	for rows.Next() {
		var i ListHomePublicRoomsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.MemberCount,
			&i.LastMessageAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHomeRecentActivity = `-- name: ListHomeRecentActivity :many
WITH feed AS (
    SELECT 'theory'::text AS kind, t.id AS id, t.title AS title, substr(t.body, 1, 200)::text AS body,
           t.series AS corner, t.created_at AS created_at, t.user_id AS author_id
    FROM theories t
    UNION ALL
    SELECT 'post'::text AS kind, p.id AS id, ''::text AS title, substr(p.body, 1, 200)::text AS body,
           p.corner AS corner, p.created_at AS created_at, p.user_id AS author_id
    FROM posts p
    UNION ALL
    SELECT 'journal'::text AS kind, j.id AS id, j.title AS title,
           substr(COALESCE((SELECT je.body FROM journal_entries je WHERE je.journal_id = j.id AND NOT je.is_draft ORDER BY je.entry_number DESC LIMIT 1), ''), 1, 200)::text AS body,
           j.work AS corner, j.created_at AS created_at, j.user_id AS author_id
    FROM journals j
    WHERE j.archived_at IS NULL
    UNION ALL
    SELECT 'art'::text AS kind, a.id AS id, a.title AS title, substr(a.description, 1, 200)::text AS body,
           a.corner AS corner, a.created_at AS created_at, a.user_id AS author_id
    FROM art a
)
SELECT f.kind, f.id, f.title, f.body, f.corner, f.created_at,
       f.author_id, u.username, u.display_name, u.avatar_url
FROM feed f
JOIN users u ON u.id = f.author_id
WHERE u.banned_at IS NULL
ORDER BY f.created_at DESC
LIMIT $1
`

type ListHomeRecentActivityRow struct {
	Kind        string
	ID          uuid.UUID
	Title       string
	Body        string
	Corner      string
	CreatedAt   time.Time
	AuthorID    uuid.UUID
	Username    string
	DisplayName string
	AvatarUrl   string
}

func (q *Queries) ListHomeRecentActivity(ctx context.Context, limit int32) ([]ListHomeRecentActivityRow, error) {
	rows, err := q.db.QueryContext(ctx, listHomeRecentActivity, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHomeRecentActivityRow{}
	for rows.Next() {
		var i ListHomeRecentActivityRow
		if err := rows.Scan(
			&i.Kind,
			&i.ID,
			&i.Title,
			&i.Body,
			&i.Corner,
			&i.CreatedAt,
			&i.AuthorID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHomeRecentMembers = `-- name: ListHomeRecentMembers :many
SELECT id, username, display_name, avatar_url, created_at
FROM users
WHERE banned_at IS NULL AND NOT is_bot
ORDER BY created_at DESC
LIMIT $1
`

type ListHomeRecentMembersRow struct {
	ID          uuid.UUID
	Username    string
	DisplayName string
	AvatarUrl   string
	CreatedAt   time.Time
}

func (q *Queries) ListHomeRecentMembers(ctx context.Context, limit int32) ([]ListHomeRecentMembersRow, error) {
	rows, err := q.db.QueryContext(ctx, listHomeRecentMembers, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHomeRecentMembersRow{}
	for rows.Next() {
		var i ListHomeRecentMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listHomeSidebarActivity = `-- name: ListHomeSidebarActivity :many
SELECT ('game_board_' || corner)::text AS key, MAX(created_at)::timestamptz AS latest_at FROM posts GROUP BY corner
UNION ALL
SELECT ('gallery_' || corner)::text AS key, MAX(created_at)::timestamptz AS latest_at FROM art GROUP BY corner
UNION ALL
SELECT ('theories_' || series)::text AS key, MAX(created_at)::timestamptz AS latest_at FROM theories GROUP BY series
UNION ALL
SELECT 'mysteries'::text AS key, MAX(created_at)::timestamptz AS latest_at FROM mysteries HAVING COUNT(*) > 0
UNION ALL
SELECT 'secrets'::text AS key, MAX(created_at)::timestamptz AS latest_at FROM secret_comments HAVING COUNT(*) > 0
UNION ALL
SELECT 'ships'::text AS key, MAX(created_at)::timestamptz AS latest_at FROM ships HAVING COUNT(*) > 0
UNION ALL
SELECT 'fanfiction'::text AS key, MAX(created_at)::timestamptz AS latest_at FROM fanfics HAVING COUNT(*) > 0
UNION ALL
SELECT 'journals'::text AS key, MAX(created_at)::timestamptz AS latest_at FROM journals WHERE archived_at IS NULL HAVING COUNT(*) > 0
UNION ALL
SELECT 'rooms'::text AS key, MAX(created_at)::timestamptz AS latest_at FROM chat_rooms WHERE type = 'group' AND is_public = TRUE AND is_system = FALSE HAVING COUNT(*) > 0
`

type ListHomeSidebarActivityRow struct {
	Key      string
	LatestAt time.Time
}

func (q *Queries) ListHomeSidebarActivity(ctx context.Context) ([]ListHomeSidebarActivityRow, error) {
	rows, err := q.db.QueryContext(ctx, listHomeSidebarActivity)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListHomeSidebarActivityRow{}
	for rows.Next() {
		var i ListHomeSidebarActivityRow
		if err := rows.Scan(&i.Key, &i.LatestAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
