// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: likes_post_likes.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const getPostLikedBy = `-- name: GetPostLikedBy :many
SELECT u.id, u.username, u.display_name, u.avatar_url,
       COALESCE(r.role, '')::text AS role
FROM post_likes lk
JOIN users u ON lk.user_id = u.id
LEFT JOIN user_roles r ON r.user_id = u.id
WHERE lk.post_id = $1
  AND ($2::text = '' OR lk.user_id <> ALL(string_to_array($2::text, ',')::uuid[]))
ORDER BY lk.created_at DESC
`

type GetPostLikedByParams struct {
	PostID  uuid.UUID
	Column2 string
}

type GetPostLikedByRow struct {
	ID          uuid.UUID
	Username    string
	DisplayName string
	AvatarUrl   string
	Role        string
}

func (q *Queries) GetPostLikedBy(ctx context.Context, arg GetPostLikedByParams) ([]GetPostLikedByRow, error) {
	rows, err := q.db.QueryContext(ctx, getPostLikedBy, arg.PostID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPostLikedByRow{}
	for rows.Next() {
		var i GetPostLikedByRow
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.DisplayName,
			&i.AvatarUrl,
			&i.Role,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const likePost = `-- name: LikePost :exec
INSERT INTO post_likes (user_id, post_id) VALUES ($1, $2) ON CONFLICT DO NOTHING
`

type LikePostParams struct {
	UserID uuid.UUID
	PostID uuid.UUID
}

func (q *Queries) LikePost(ctx context.Context, arg LikePostParams) error {
	_, err := q.db.ExecContext(ctx, likePost, arg.UserID, arg.PostID)
	return err
}

const unlikePost = `-- name: UnlikePost :exec
DELETE FROM post_likes WHERE user_id = $1 AND post_id = $2
`

type UnlikePostParams struct {
	UserID uuid.UUID
	PostID uuid.UUID
}

func (q *Queries) UnlikePost(ctx context.Context, arg UnlikePostParams) error {
	_, err := q.db.ExecContext(ctx, unlikePost, arg.UserID, arg.PostID)
	return err
}
