// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notification.sql

package sqlcgen

import (
	"context"
	"time"

	"github.com/google/uuid"
)

const countRecentDuplicateNotifications = `-- name: CountRecentDuplicateNotifications :one
SELECT COUNT(*) FROM notifications
WHERE user_id = $1 AND type = $2 AND reference_id = $3 AND actor_id = $4
  AND created_at > NOW() - INTERVAL '1 hour'
`

type CountRecentDuplicateNotificationsParams struct {
	UserID      uuid.UUID
	Type        string
	ReferenceID string
	ActorID     *uuid.UUID
}

func (q *Queries) CountRecentDuplicateNotifications(ctx context.Context, arg CountRecentDuplicateNotificationsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRecentDuplicateNotifications,
		arg.UserID,
		arg.Type,
		arg.ReferenceID,
		arg.ActorID,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countRecentNotificationsFromActor = `-- name: CountRecentNotificationsFromActor :one
SELECT COUNT(*) FROM notifications
WHERE type = $1 AND actor_id = $2
  AND created_at > NOW() - make_interval(secs => $3::double precision)
`

type CountRecentNotificationsFromActorParams struct {
	Type    string
	ActorID *uuid.UUID
	Column3 float64
}

func (q *Queries) CountRecentNotificationsFromActor(ctx context.Context, arg CountRecentNotificationsFromActorParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countRecentNotificationsFromActor, arg.Type, arg.ActorID, arg.Column3)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnreadNotifications = `-- name: CountUnreadNotifications :one
SELECT COUNT(*) FROM notifications WHERE user_id = $1 AND read = FALSE
`

func (q *Queries) CountUnreadNotifications(ctx context.Context, userID uuid.UUID) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUnreadNotifications, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserNotifications = `-- name: CountUserNotifications :one
SELECT (
    (SELECT COUNT(DISTINCT (g.type, g.reference_id)) FROM notifications g
       WHERE g.user_id = $1 AND g.type = ANY(string_to_array($2::text, ',')) AND g.read = FALSE)
    +
    (SELECT COUNT(*) FROM notifications p
       WHERE p.user_id = $1 AND NOT (p.type = ANY(string_to_array($2::text, ',')) AND p.read = FALSE))
)::bigint AS total
`

type CountUserNotificationsParams struct {
	UserID  uuid.UUID
	Column2 string
}

func (q *Queries) CountUserNotifications(ctx context.Context, arg CountUserNotificationsParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserNotifications, arg.UserID, arg.Column2)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const createNotification = `-- name: CreateNotification :one
WITH n AS (
    INSERT INTO notifications (user_id, type, reference_id, reference_type, actor_id, message)
    VALUES ($1, $2, $3, $4, $5, $6)
    RETURNING id, user_id, type, reference_id, reference_type, actor_id, message, read, created_at
)
SELECT n.id, n.user_id, n.type, n.reference_id, n.reference_type, n.actor_id,
       COALESCE(n.message, '')::text AS message, n.read, n.created_at,
       COALESCE(u.username, '')::text AS actor_username,
       COALESCE(u.display_name, '')::text AS actor_display_name,
       COALESCE(u.avatar_url, '')::text AS actor_avatar_url,
       COALESCE(ur.role, '')::text AS actor_role
FROM n
LEFT JOIN users u ON n.actor_id = u.id
LEFT JOIN user_roles ur ON n.actor_id = ur.user_id
`

type CreateNotificationParams struct {
	UserID        uuid.UUID
	Type          string
	ReferenceID   string
	ReferenceType string
	ActorID       *uuid.UUID
	Message       string
}

type CreateNotificationRow struct {
	ID               int64
	UserID           uuid.UUID
	Type             string
	ReferenceID      string
	ReferenceType    string
	ActorID          *uuid.UUID
	Message          string
	Read             bool
	CreatedAt        time.Time
	ActorUsername    string
	ActorDisplayName string
	ActorAvatarUrl   string
	ActorRole        string
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (CreateNotificationRow, error) {
	row := q.db.QueryRowContext(ctx, createNotification,
		arg.UserID,
		arg.Type,
		arg.ReferenceID,
		arg.ReferenceType,
		arg.ActorID,
		arg.Message,
	)
	var i CreateNotificationRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.ReferenceID,
		&i.ReferenceType,
		&i.ActorID,
		&i.Message,
		&i.Read,
		&i.CreatedAt,
		&i.ActorUsername,
		&i.ActorDisplayName,
		&i.ActorAvatarUrl,
		&i.ActorRole,
	)
	return i, err
}

const deleteNotificationsOlderThanBatch = `-- name: DeleteNotificationsOlderThanBatch :execrows
DELETE FROM notifications
WHERE id IN (
    SELECT o.id FROM notifications o
    WHERE o.created_at < $1
    ORDER BY o.id
    LIMIT $2
)
`

type DeleteNotificationsOlderThanBatchParams struct {
	CreatedAt time.Time
	Limit     int32
}

func (q *Queries) DeleteNotificationsOlderThanBatch(ctx context.Context, arg DeleteNotificationsOlderThanBatchParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, deleteNotificationsOlderThanBatch, arg.CreatedAt, arg.Limit)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const getNotificationByID = `-- name: GetNotificationByID :one
SELECT n.id, n.user_id, n.type, n.reference_id, n.reference_type, n.actor_id,
       COALESCE(n.message, '')::text AS message, n.read, n.created_at,
       COALESCE(u.username, '')::text AS actor_username,
       COALESCE(u.display_name, '')::text AS actor_display_name,
       COALESCE(u.avatar_url, '')::text AS actor_avatar_url,
       COALESCE(ur.role, '')::text AS actor_role
FROM notifications n
LEFT JOIN users u ON n.actor_id = u.id
LEFT JOIN user_roles ur ON n.actor_id = ur.user_id
WHERE n.id = $1 AND n.user_id = $2
`

type GetNotificationByIDParams struct {
	ID     int64
	UserID uuid.UUID
}

type GetNotificationByIDRow struct {
	ID               int64
	UserID           uuid.UUID
	Type             string
	ReferenceID      string
	ReferenceType    string
	ActorID          *uuid.UUID
	Message          string
	Read             bool
	CreatedAt        time.Time
	ActorUsername    string
	ActorDisplayName string
	ActorAvatarUrl   string
	ActorRole        string
}

func (q *Queries) GetNotificationByID(ctx context.Context, arg GetNotificationByIDParams) (GetNotificationByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getNotificationByID, arg.ID, arg.UserID)
	var i GetNotificationByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Type,
		&i.ReferenceID,
		&i.ReferenceType,
		&i.ActorID,
		&i.Message,
		&i.Read,
		&i.CreatedAt,
		&i.ActorUsername,
		&i.ActorDisplayName,
		&i.ActorAvatarUrl,
		&i.ActorRole,
	)
	return i, err
}

const getNotificationReadState = `-- name: GetNotificationReadState :one
SELECT type, reference_id, read FROM notifications WHERE id = $1 AND user_id = $2
`

type GetNotificationReadStateParams struct {
	ID     int64
	UserID uuid.UUID
}

type GetNotificationReadStateRow struct {
	Type        string
	ReferenceID string
	Read        bool
}

func (q *Queries) GetNotificationReadState(ctx context.Context, arg GetNotificationReadStateParams) (GetNotificationReadStateRow, error) {
	row := q.db.QueryRowContext(ctx, getNotificationReadState, arg.ID, arg.UserID)
	var i GetNotificationReadStateRow
	err := row.Scan(&i.Type, &i.ReferenceID, &i.Read)
	return i, err
}

const listUserNotifications = `-- name: ListUserNotifications :many
WITH chat_grouped AS (
    SELECT
      g.id, g.user_id, g.type, g.reference_id, g.reference_type, g.actor_id, g.message, g.read, g.created_at,
      ROW_NUMBER() OVER (PARTITION BY g.type, g.reference_id ORDER BY g.created_at DESC, g.id DESC) AS rn,
      COUNT(*) OVER (PARTITION BY g.type, g.reference_id) AS grp_count
    FROM notifications g
    WHERE g.user_id = $1 AND g.type = ANY(string_to_array($2::text, ',')) AND g.read = FALSE
),
combined AS (
    SELECT cg.id, cg.user_id, cg.type, cg.reference_id, cg.reference_type, cg.actor_id,
           COALESCE(cg.message, '')::text AS message, cg.read, cg.created_at, cg.grp_count::bigint AS count
    FROM chat_grouped cg
    WHERE cg.rn = 1
    UNION ALL
    SELECT p.id, p.user_id, p.type, p.reference_id, p.reference_type, p.actor_id,
           COALESCE(p.message, '')::text AS message, p.read, p.created_at, 1::bigint AS count
    FROM notifications p
    WHERE p.user_id = $1 AND NOT (p.type = ANY(string_to_array($2::text, ',')) AND p.read = FALSE)
)
SELECT c.id, c.user_id, c.type, c.reference_id, c.reference_type, c.actor_id,
       c.message, c.read, c.created_at, c.count,
       COALESCE(u.username, '')::text AS actor_username,
       COALESCE(u.display_name, '')::text AS actor_display_name,
       COALESCE(u.avatar_url, '')::text AS actor_avatar_url,
       COALESCE(ur.role, '')::text AS actor_role
FROM combined c
LEFT JOIN users u ON c.actor_id = u.id
LEFT JOIN user_roles ur ON c.actor_id = ur.user_id
ORDER BY c.created_at DESC
LIMIT $3 OFFSET $4
`

type ListUserNotificationsParams struct {
	UserID  uuid.UUID
	Column2 string
	Limit   int32
	Offset  int32
}

type ListUserNotificationsRow struct {
	ID               int64
	UserID           uuid.UUID
	Type             string
	ReferenceID      string
	ReferenceType    string
	ActorID          *uuid.UUID
	Message          string
	Read             bool
	CreatedAt        time.Time
	Count            int64
	ActorUsername    string
	ActorDisplayName string
	ActorAvatarUrl   string
	ActorRole        string
}

func (q *Queries) ListUserNotifications(ctx context.Context, arg ListUserNotificationsParams) ([]ListUserNotificationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listUserNotifications,
		arg.UserID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUserNotificationsRow{}
	for rows.Next() {
		var i ListUserNotificationsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Type,
			&i.ReferenceID,
			&i.ReferenceType,
			&i.ActorID,
			&i.Message,
			&i.Read,
			&i.CreatedAt,
			&i.Count,
			&i.ActorUsername,
			&i.ActorDisplayName,
			&i.ActorAvatarUrl,
			&i.ActorRole,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsRead = `-- name: MarkAllNotificationsRead :exec
UPDATE notifications SET read = TRUE WHERE user_id = $1 AND read = FALSE
`

func (q *Queries) MarkAllNotificationsRead(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, markAllNotificationsRead, userID)
	return err
}

const markGroupedNotificationsRead = `-- name: MarkGroupedNotificationsRead :exec
UPDATE notifications SET read = TRUE
WHERE user_id = $1 AND type = $2 AND reference_id = $3 AND read = FALSE
`

type MarkGroupedNotificationsReadParams struct {
	UserID      uuid.UUID
	Type        string
	ReferenceID string
}

func (q *Queries) MarkGroupedNotificationsRead(ctx context.Context, arg MarkGroupedNotificationsReadParams) error {
	_, err := q.db.ExecContext(ctx, markGroupedNotificationsRead, arg.UserID, arg.Type, arg.ReferenceID)
	return err
}

const markNotificationRead = `-- name: MarkNotificationRead :exec
UPDATE notifications SET read = TRUE WHERE id = $1 AND user_id = $2
`

type MarkNotificationReadParams struct {
	ID     int64
	UserID uuid.UUID
}

func (q *Queries) MarkNotificationRead(ctx context.Context, arg MarkNotificationReadParams) error {
	_, err := q.db.ExecContext(ctx, markNotificationRead, arg.ID, arg.UserID)
	return err
}

const markNotificationsReadByReference = `-- name: MarkNotificationsReadByReference :exec
UPDATE notifications SET read = TRUE
WHERE user_id = $1 AND reference_id = $2 AND read = FALSE AND type = ANY(string_to_array($3::text, ','))
`

type MarkNotificationsReadByReferenceParams struct {
	UserID      uuid.UUID
	ReferenceID string
	Column3     string
}

func (q *Queries) MarkNotificationsReadByReference(ctx context.Context, arg MarkNotificationsReadByReferenceParams) error {
	_, err := q.db.ExecContext(ctx, markNotificationsReadByReference, arg.UserID, arg.ReferenceID, arg.Column3)
	return err
}
