// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: role.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const clearUserRoles = `-- name: ClearUserRoles :exec
DELETE FROM user_roles WHERE user_id = $1
`

func (q *Queries) ClearUserRoles(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, clearUserRoles, userID)
	return err
}

const countUserRole = `-- name: CountUserRole :one
SELECT COUNT(*) FROM user_roles WHERE user_id = $1 AND role = $2
`

type CountUserRoleParams struct {
	UserID uuid.UUID
	Role   string
}

func (q *Queries) CountUserRole(ctx context.Context, arg CountUserRoleParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countUserRole, arg.UserID, arg.Role)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteUserRole = `-- name: DeleteUserRole :exec
DELETE FROM user_roles WHERE user_id = $1 AND role = $2
`

type DeleteUserRoleParams struct {
	UserID uuid.UUID
	Role   string
}

func (q *Queries) DeleteUserRole(ctx context.Context, arg DeleteUserRoleParams) error {
	_, err := q.db.ExecContext(ctx, deleteUserRole, arg.UserID, arg.Role)
	return err
}

const getUserRole = `-- name: GetUserRole :one
SELECT role FROM user_roles WHERE user_id = $1 LIMIT 1
`

func (q *Queries) GetUserRole(ctx context.Context, userID uuid.UUID) (string, error) {
	row := q.db.QueryRowContext(ctx, getUserRole, userID)
	var role string
	err := row.Scan(&role)
	return role, err
}

const getUserRolesBatch = `-- name: GetUserRolesBatch :many
SELECT user_id, role FROM user_roles WHERE user_id = ANY(string_to_array($1::text, ',')::uuid[])
`

func (q *Queries) GetUserRolesBatch(ctx context.Context, dollar_1 string) ([]UserRole, error) {
	rows, err := q.db.QueryContext(ctx, getUserRolesBatch, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UserRole{}
	for rows.Next() {
		var i UserRole
		if err := rows.Scan(&i.UserID, &i.Role); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUsersByRoles = `-- name: GetUsersByRoles :many
SELECT DISTINCT user_id FROM user_roles WHERE role = ANY(string_to_array($1::text, ','))
`

func (q *Queries) GetUsersByRoles(ctx context.Context, dollar_1 string) ([]uuid.UUID, error) {
	rows, err := q.db.QueryContext(ctx, getUsersByRoles, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []uuid.UUID{}
	for rows.Next() {
		var user_id uuid.UUID
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertUserRole = `-- name: InsertUserRole :exec
INSERT INTO user_roles (user_id, role) VALUES ($1, $2)
`

type InsertUserRoleParams struct {
	UserID uuid.UUID
	Role   string
}

func (q *Queries) InsertUserRole(ctx context.Context, arg InsertUserRoleParams) error {
	_, err := q.db.ExecContext(ctx, insertUserRole, arg.UserID, arg.Role)
	return err
}
