// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stream_credentials.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const deleteStreamCredentials = `-- name: DeleteStreamCredentials :exec
DELETE FROM stream_credentials WHERE user_id = $1
`

func (q *Queries) DeleteStreamCredentials(ctx context.Context, userID uuid.UUID) error {
	_, err := q.db.ExecContext(ctx, deleteStreamCredentials, userID)
	return err
}

const getStreamCredentials = `-- name: GetStreamCredentials :one
SELECT user_id, ingress_id, whip_url, stream_key, room
FROM stream_credentials
WHERE user_id = $1
`

type GetStreamCredentialsRow struct {
	UserID    uuid.UUID
	IngressID string
	WhipUrl   string
	StreamKey string
	Room      string
}

func (q *Queries) GetStreamCredentials(ctx context.Context, userID uuid.UUID) (GetStreamCredentialsRow, error) {
	row := q.db.QueryRowContext(ctx, getStreamCredentials, userID)
	var i GetStreamCredentialsRow
	err := row.Scan(
		&i.UserID,
		&i.IngressID,
		&i.WhipUrl,
		&i.StreamKey,
		&i.Room,
	)
	return i, err
}

const upsertStreamCredentials = `-- name: UpsertStreamCredentials :exec
INSERT INTO stream_credentials (user_id, ingress_id, whip_url, stream_key, room)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (user_id) DO UPDATE
   SET ingress_id = excluded.ingress_id,
       whip_url = excluded.whip_url,
       stream_key = excluded.stream_key,
       room = excluded.room,
       updated_at = NOW()
`

type UpsertStreamCredentialsParams struct {
	UserID    uuid.UUID
	IngressID string
	WhipUrl   string
	StreamKey string
	Room      string
}

func (q *Queries) UpsertStreamCredentials(ctx context.Context, arg UpsertStreamCredentialsParams) error {
	_, err := q.db.ExecContext(ctx, upsertStreamCredentials,
		arg.UserID,
		arg.IngressID,
		arg.WhipUrl,
		arg.StreamKey,
		arg.Room,
	)
	return err
}
