// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: votes_oc_votes.sql

package sqlcgen

import (
	"context"

	"github.com/google/uuid"
)

const deleteOCVote = `-- name: DeleteOCVote :exec
DELETE FROM oc_votes WHERE user_id = $1 AND oc_id = $2
`

type DeleteOCVoteParams struct {
	UserID uuid.UUID
	OcID   uuid.UUID
}

func (q *Queries) DeleteOCVote(ctx context.Context, arg DeleteOCVoteParams) error {
	_, err := q.db.ExecContext(ctx, deleteOCVote, arg.UserID, arg.OcID)
	return err
}

const upsertOCVote = `-- name: UpsertOCVote :exec
INSERT INTO oc_votes (user_id, oc_id, value) VALUES ($1, $2, $3)
ON CONFLICT (user_id, oc_id) DO UPDATE SET value = EXCLUDED.value
`

type UpsertOCVoteParams struct {
	UserID uuid.UUID
	OcID   uuid.UUID
	Value  int32
}

func (q *Queries) UpsertOCVote(ctx context.Context, arg UpsertOCVoteParams) error {
	_, err := q.db.ExecContext(ctx, upsertOCVote, arg.UserID, arg.OcID, arg.Value)
	return err
}
